# File: anime_parser.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: anime_parser.py.1shot.das

__doc__ = '动漫名称解析器'
'__pyarmor_enter_8905__(...)'
import re
from typing import Optional
import anitopy
from matchers import GroupMatcher, CaptureMatcher
from base import MediaBase
from utils import MediaType, StringUtils
from logger import logger_nameparser as logger

class AnimeParser(MediaBase):
    '''动漫名称解析'''
    '__pyarmor_enter_8908__(...)'
    _anime_no_words = '新番|月?连载|周?|[日美国英韩中]剧|BDrip|BD|BDRIP|BluRay|Blu-Ray|TVrip|TV|TVRIP|WEBrip|WEB|WEBRIP|WEB-DL|DVDrip|DVD|DVDRIP|简繁|简体|繁体|简日|繁日|简繁日|简繁内封|简繁外挂|内封|外挂|内嵌|中文|中字|字幕|中英|双语|简中|繁中|CHS&CHT|CHS|CHT|BIG5|GB|HEVC|AVC|H\\.?265|H\\.?264|H265|H264|x265|x264|AV1|10bit|10-bit|8bit|8-bit|Ma10p|Hi10p|Hi444pp|FLAC|AAC|DTS|MP3|AC3|EAC3|DDP|Opus|1080[PIpi]|720[PIpi]|2160[PIpi]|4[Kk]|480[PIpi]|576[PIpi]|MKV|MP4|AVI|WebDL|WEB-DL|Fin|END'
    
    def __init__(self, title, subtitle, isfile):
        '__pyarmor_enter_8911__(...)'
    # WARNING: Decompyle incomplete

    
    def _anitopy_parse(self, title, original_title):
        '''使用 anitopy 解析动漫标题'''
        '__pyarmor_enter_8914__(...)'
        title = self.__pre_parse(title)
        anitopy_info = anitopy.parse(title)
        if not anitopy_info:
            return None
        return None
        name = anitopy_info.get('anime_title', '')
        if not name and name.startswith('UNKNOWN'):
            name_match = re.match('(.*)\\s(\\d{4})$', name)
            if name_match:
                name = name_match.group(1)
                if not self.year:
                    self.year = name_match.group(2)
            if StringUtils.is_chinese(name):
                self.cn_name = name
            else:
                self.en_name = name
        anime_year = anitopy_info.get('anime_year')
        if anime_year and str(anime_year).isdigit():
            self.year = str(anime_year)
        anime_type = anitopy_info.get('anime_type')
        if anime_type:
            if isinstance(anime_type, list):
                anime_type = anime_type[0]
            if anime_type.upper() in ('TV', 'MOVIE', 'OVA', 'OAD', 'ONA', 'SPECIAL', 'SP'):
                if anime_type.upper() == 'MOVIE':
                    self.type = MediaType.MOVIE
                else:
                    self.type = MediaType.TV
        anime_season = anitopy_info.get('anime_season')
        if anime_season:
            if isinstance(anime_season, list):
                if len(anime_season) == 1:
                    begin_season = int(anime_season[0])
                    self.begin_season = begin_season
                    self.total_season = 1
                else:
                    self.begin_season = int(anime_season[0])
                    self.end_season = int(anime_season[-1])
                    self.total_season = (self.end_season - self.begin_season) + 1
            else:
                self.begin_season = int(anime_season)
                self.total_season = 1
            self.type = MediaType.TV
        episode_number = anitopy_info.get('episode_number')
        if episode_number:
            if isinstance(episode_number, list):
                if len(episode_number) == 1:
                    self.begin_episode = int(float(episode_number[0]))
                    self.total_episode = 1
                else:
                    self.begin_episode = int(float(episode_number[0]))
                    self.end_episode = int(float(episode_number[-1]))
                    self.total_episode = (self.end_episode - self.begin_episode) + 1
            else:
                self.begin_episode = int(float(episode_number))
                self.total_episode = 1
            self.type = MediaType.TV
        resolution = anitopy_info.get('video_resolution')
        if resolution:
            self.resource_pix = resolution
        video_term = anitopy_info.get('video_term')
        if video_term:
            if isinstance(video_term, list):
                self.video_encode = ' '.join(video_term)
            else:
                self.video_encode = video_term
        audio_term = anitopy_info.get('audio_term')
        if audio_term:
            if isinstance(audio_term, list):
                self.audio_encode = ' '.join(audio_term)
            else:
                self.audio_encode = audio_term
        source = anitopy_info.get('source')
        if source:
            if isinstance(source, list):
                self.resource_type = ' '.join(source)
            else:
                self.resource_type = source
        release_group = anitopy_info.get('release_group')
        if not release_group and self.resource_team:
            self.resource_team = release_group
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _simple_parse(self, title):
        '''简化解析模式（无 anitopy 时使用）'''
        '__pyarmor_enter_8917__(...)'
        cn_match = re.search('[\\u4e00-\\u9fff]+(?:\\s+[\\u4e00-\\u9fff]+)*', title)
        if cn_match:
            self.cn_name = cn_match.group(0)
        year_match = re.search('(\\d{4})', title)
        re.search('(\\d{3,4}[PIpi]|[248][Kk])', title) = None if year_match else year_match.group(1)
        if pix_match:
            self.resource_pix = pix_match.group(1)
        ep_match = re.search('[\\[\\s](\\d{1,4})[\\]\\s]', title)
        if ep_match:
            self.begin_episode = int(ep_match.group(1))
            self.total_episode = 1
            self.type = MediaType.TV
        return None
        return None
        '__pyarmor_exit_8918__(...)'
        '__pyarmor_exit_8918__(...)'

    
    def __pre_parse(self, title):
        '''动漫标题预处理'''
        '__pyarmor_enter_8920__(...)'
        season_cn_match = re.search('第([一二三四五六七八九十]+)季', title)
        if season_cn_match:
            import cn2an
            season_num = int(cn2an.cn2an(season_cn_match.group(1), mode = 'smart'))
            title = title.replace(season_cn_match.group(0), f'''S{season_num:02d}''')
        title = re.sub('【', '[', title)
        title = re.sub('】', ']', title)
        return title
        None(None)
        return None
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_8909__(...)'
    '__pyarmor_exit_8909__(...)'

return None
return None
# WARNING: Decompyle incomplete
