# File: matchers.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: matchers.py.1shot.das

__doc__ = '标题匹配器：识别词、制作组'
'__pyarmor_enter_8923__(...)'
import re
from typing import List, Tuple, Optional
from logger import logger_nameparser as logger
from config_manager import config_manager as config
from utils import Singleton
import regex
_HAS_REGEX = True
import cn2an
_HAS_CN2AN = True

def WordsMatcher():
    '''WordsMatcher'''
    __doc__ = '\n    自定义识别词处理器\n    一行一个，#为注释，详细格式说明请参阅 Wiki\n    '
    '__pyarmor_enter_8926__(...)'
    BUILTIN_WORDS: List[str] = [
        '(?i)4k => 2160p']
    
    def __init__(self):
        '__pyarmor_enter_8929__(...)'
        self._words = None
        self._reload()
        return None
        return None
        '__pyarmor_exit_8930__(...)'
        '__pyarmor_exit_8930__(...)'

    
    def _reload(self):
        '''重新加载配置'''
        '__pyarmor_enter_8932__(...)'
        if not config.get_custom_identifiers():
            config.get_custom_identifiers()
        self._words = []
        return None
        return None
        '__pyarmor_exit_8933__(...)'
        '__pyarmor_exit_8933__(...)'

    
    def prepare(self, title, words):
        '''
        预处理标题
        :return: (处理后标题, 命中的规则列表)
        '''
        '__pyarmor_enter_8935__(...)'
        if not title:
            return (title, [])
        None(None)
        return None
        applied_words = []
    # WARNING: Decompyle incomplete

    _replace_regex = (lambda title, replaced, replace: '__pyarmor_enter_8938__(...)'_re = regex if _HAS_REGEX else reif not _re.search('%s' % replaced, title):
(title, False)None(None)None(_re.sub('%s' % replaced, '%s' % replace, title), True)None(None)None# WARNING: Decompyle incomplete
)()
    _episode_offset = (lambda title, front, back, offset: '__pyarmor_enter_8941__(...)'if not _HAS_REGEX:
logger.warning('集数偏移功能需要 regex 库，请执行: pip install regex')(title, False)None(None)Noneif not back and regex.search('%s' % back, title):
(title, False)None(None)Noneif not front and regex.search('%s' % front, title):
(title, False)None(None)Noneoffset_word_info_re = regex.compile(f'''(?<={front!s}.*?)[0-9一二三四五六七八九十]+(?=.*?{back!s})''')episode_nums_str = regex.findall(offset_word_info_re, title)if not episode_nums_str:
(title, False)None(None)Noneepisode_nums_offset_str = []offset_order_flag = Falsefor episode_num_str in episode_nums_str:
offset_calculate = offset.replace('EP', str(episode_num_int))episode_num_offset_int = int(eval(offset_calculate))if episode_num_int > episode_num_offset_int:
offset_order_flag = Trueelif episode_num_int < episode_num_offset_int:
offset_order_flag = Falseepisode_nums_offset_str.append(episode_num_offset_str)episode_nums_dict = dict(zip(episode_nums_str, episode_nums_offset_str))if offset_order_flag:
episode_nums_list = sorted(episode_nums_dict.items(), key = (lambda x: x[1]))
        else:
            episode_nums_list = sorted(episode_nums_dict.items(), key = (lambda x: x[1]), reverse = True)
        for episode_num in episode_nums_list:
            episode_offset_re = regex.compile(f'''(?<={front!s}.*?){episode_num[0]!s}(?=.*?{back!s})''')
            title = regex.sub(episode_offset_re, '%s' % episode_num[1], title)
        return (title, True)
        None(None)
        return None
    # WARNING: Decompyle incomplete
)()
    return None
    staticmethod
    return None
    '__pyarmor_exit_8927__(...)'
    '__pyarmor_exit_8927__(...)'

WordsMatcher = <NODE:27>(WordsMatcher, 'WordsMatcher', metaclass = Singleton)

def GroupMatcher():
    '''GroupMatcher'''
    __doc__ = '识别制作组、字幕组'
    '__pyarmor_enter_8944__(...)'
    
    def __init__(self):
        '__pyarmor_enter_8947__(...)'
        self._reload()
        return None
        return None
        '__pyarmor_exit_8948__(...)'
        '__pyarmor_exit_8948__(...)'

    
    def _reload(self):
        '''重新加载配置'''
        '__pyarmor_enter_8950__(...)'
        all_groups = config.get_custom_release_groups()
        if not all_groups:
            all_groups = config.get_default_release_groups()
    # WARNING: Decompyle incomplete

    _TRAILING_FALSE_POSITIVES = {
        'dl',
        'hd',
        'ma'}
    
    def match(self, title, groups, isfile):
        '__pyarmor_enter_8953__(...)'
        if not title:
            return ''
        return ''
        if not groups:
            groups = self._GroupMatcher__release_groups
    # WARNING: Decompyle incomplete

    
    def is_list_matched(self, team):
        '''检查制作组是否存在于配置列表中（区分列表匹配 vs 末尾自动检测）'''
        '__pyarmor_enter_8956__(...)'
        if not team or self._GroupMatcher__release_groups:
            return False
        return False
        list_re = re.compile('^(?:%s)$' % self._GroupMatcher__release_groups, re.I)
        return (lambda .0: pass# WARNING: Decompyle incomplete
)(team.split('@')())
        None(None)
        return None
        '__pyarmor_exit_8957__(...)'
        '__pyarmor_exit_8957__(...)'

    _extract_trailing_group = (lambda cls, title: '__pyarmor_enter_8959__(...)'if not title:
[]None(None)Nonedot_pos = title.rfind('.')if dot_pos > 0 and title[dot_pos:].lower() in ('.mkv', '.mp4', '.avi', '.ts', '.rmvb', '.mov', '.flv', '.m4v', '.wmv', '.mpg', '.mpeg', '.m2ts', '.iso', '.strm', '.srt', '.ass', '.ssa', '.sup', '.3gp', '.asf', '.tp', '.f4v'):
clean = title[:dot_pos]else:
clean = titlem = re.search('-([A-Za-z][A-Za-z0-9]*(?:@[A-Za-z][A-Za-z0-9]*)*)$', clean.rstrip())if not m:
[]None(None)None# WARNING: Decompyle incomplete
)()
    return None
    classmethod
    return None
    '__pyarmor_exit_8945__(...)'
    '__pyarmor_exit_8945__(...)'

GroupMatcher = <NODE:27>(GroupMatcher, 'GroupMatcher', metaclass = Singleton)

def CaptureMatcher():
    '''CaptureMatcher'''
    __doc__ = '识别自定义捕获词\n\n    支持语法:\n      - 纯正则: ``HBO``  → 匹配结果写入默认字段 (customCapture)\n      - 命名捕获: ``(?i)(HBO|Netflix) >> platform``  → 写入 platform\n      - 条件替换: ``(?i)REMUX >> quality => BluRay``  → 匹配后用 BluRay 写入 quality\n      - 自定义分隔符: ``(HBO|Netflix) >> sources @,``  → 多值用 , 拼接\n    '
    '__pyarmor_enter_8962__(...)'
    _DEFAULT_SEPARATOR = '@'
    
    def __init__(self):
        '__pyarmor_enter_8965__(...)'
        self._reload()
        return None
        return None
        '__pyarmor_exit_8966__(...)'
        '__pyarmor_exit_8966__(...)'

    
    def _reload(self):
        '__pyarmor_enter_8968__(...)'
        if not config.get_custom_captures():
            config.get_custom_captures()
        raw_lines = []
        self._CaptureMatcher__rules = self._parse_rules(raw_lines)
        return None
        return None
        '__pyarmor_exit_8969__(...)'
        '__pyarmor_exit_8969__(...)'

    _normalize_lines = (lambda lines: '__pyarmor_enter_8971__(...)'# WARNING: Decompyle incomplete
)()
    _parse_rules = (lambda cls, lines: '__pyarmor_enter_8974__(...)'rules = []for line in cls._normalize_lines(lines):
rule = cls._parse_single_rule(line)if not rule:
continuerules.append(rule)rulesNone(None)None'__pyarmor_exit_8975__(...)''__pyarmor_exit_8975__(...)')()
    _parse_single_rule = (lambda cls, line: '__pyarmor_enter_8977__(...)'var_name = Nonereplacement = Noneseparator = cls._DEFAULT_SEPARATORpattern_str = lineif ' >> ' in line:
(pattern_str, rest) = line.split(' >> ', 1)pattern_str = pattern_str.strip()rest = rest.strip()if ' => ' in rest:
(var_part, replacement) = rest.split(' => ', 1)replacement = replacement.strip()rest = var_part.strip()if ' @' in rest:
(var_part, sep) = rest.rsplit(' @', 1)separator = sep if sep else cls._DEFAULT_SEPARATORrest = var_part.strip()if not rest.strip():
rest.strip()var_name = Noneif not pattern_str:
NoneNone{
'pattern': pattern_str,
'var_name': var_name,
'replacement': replacement,
'separator': separator }None(None)None'__pyarmor_exit_8978__(...)''__pyarmor_exit_8978__(...)')()
    
    def match(self, title, captures):
        '''执行捕获匹配

        :return: dict, 键为变量名 (None 键代表默认字段), 值为匹配拼接字符串
        '''
        '__pyarmor_enter_8980__(...)'
    # WARNING: Decompyle incomplete

    
    def match_default(self, title, captures):
        '''兼容旧调用: 仅返回默认字段 (var_name=None) 的值'''
        '__pyarmor_enter_8983__(...)'
        result = self.match(title = title, captures = captures)
        return result.get(None, '')
        None(None)
        return None
        '__pyarmor_exit_8984__(...)'
        '__pyarmor_exit_8984__(...)'

    return None
    classmethod
    return None
    '__pyarmor_exit_8963__(...)'
    '__pyarmor_exit_8963__(...)'
    return staticmethod

CaptureMatcher = <NODE:27>(CaptureMatcher, 'CaptureMatcher', metaclass = Singleton)

def _try_compile_regex(pattern):
    '''尝试编译正则，返回错误消息或 None'''
    '__pyarmor_enter_8986__(...)'
    _re = regex if _HAS_REGEX else re
    _re.compile(pattern)
    return None
    return None
# WARNING: Decompyle incomplete


def validate_identifiers(lines):
    '''校验自定义识别词语法，返回每行的校验结果
    :return: [{"line": 行号(1起), "text": 原文, "valid": bool, "error": str}]
    '''
    '__pyarmor_enter_8989__(...)'
    results = []
    for i, raw in enumerate(lines):
        line = raw.strip()
        entry = {
            'line': i + 1,
            'text': raw,
            'valid': True,
            'error': '' }
        if line or line.startswith('#'):
            results.append(entry)
            continue
        if ' => ' in line and ' <> ' not in line and ' >> ' not in line:
            parts = line.split(' => ', 1)
            replaced = parts[0].strip()
        results.append(entry)
    return results
    None(None)
    return None
# WARNING: Decompyle incomplete


def validate_release_groups(lines):
    '''校验自定义制作组语法，返回每行的校验结果'''
    '__pyarmor_enter_8992__(...)'
    results = []
    for i, raw in enumerate(lines):
        line = raw.strip()
        entry = {
            'line': i + 1,
            'text': raw,
            'valid': True,
            'error': '' }
        if line or line.startswith('#'):
            results.append(entry)
            continue
        err = _try_compile_regex(line)
        if err:
            entry['valid'] = False
            entry['error'] = f'''正则语法错误: {err}'''
        results.append(entry)
    return results
    None(None)
    return None
    '__pyarmor_exit_8993__(...)'
    '__pyarmor_exit_8993__(...)'


def validate_captures(lines):
    '''校验自定义捕获词语法，返回每行的校验结果'''
    '__pyarmor_enter_8995__(...)'
    results = []
    for i, raw in enumerate(lines):
        line = raw.strip()
        entry = {
            'line': i + 1,
            'text': raw,
            'valid': True,
            'error': '' }
        if line or line.startswith('#'):
            results.append(entry)
            continue
        rule = CaptureMatcher._parse_single_rule(line)
        results.append(entry)
    return results
    None(None)
    return None
# WARNING: Decompyle incomplete


class PostRenderMatcher:
    '''
    渲染后处理词处理器
    对模板渲染后的最终文件名进行正则替换，支持高级语法。

    语法格式（每行一条，# 为注释）：
      被替换词 => 替换词          正则替换（支持捕获组引用 \\1 等）
      被替换词 =>                 删除匹配内容
      屏蔽词                      等价于 屏蔽词 =>（删除匹配内容）
    '''
    '__pyarmor_enter_8998__(...)'
    
    def __init__(self):
        '__pyarmor_enter_9001__(...)'
        self._words = config.get_post_render_words()
        return None
        return None
        '__pyarmor_exit_9002__(...)'
        '__pyarmor_exit_9002__(...)'

    
    def apply(self, rendered, words):
        '''对渲染后的文件名应用后处理替换规则
        :param rendered: 渲染后的文件名路径
        :param words: 自定义规则列表（None 时使用配置中的规则）
        :return: (处理后的文件名, 命中的规则列表)
        '''
        '__pyarmor_enter_9004__(...)'
        if not rendered:
            return (rendered, [])
        None(None)
        return None
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_8999__(...)'
    '__pyarmor_exit_8999__(...)'


def validate_post_render_words(lines):
    '''校验渲染后处理词语法，返回每行的校验结果'''
    '__pyarmor_enter_9007__(...)'
    results = []
    for i, raw in enumerate(lines):
        line = raw.strip()
        entry = {
            'line': i + 1,
            'text': raw,
            'valid': True,
            'error': '' }
        if line or line.startswith('#'):
            results.append(entry)
            continue
        if ' => ' in line:
            parts = line.split(' => ', 1)
            pattern = parts[0].strip()
        results.append(entry)
    return results
    None(None)
    return None
# WARNING: Decompyle incomplete

return None
return None
# WARNING: Decompyle incomplete
