# File: video_parser.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: video_parser.py.1shot.das

__doc__ = '影视名称解析器（电影、电视剧）'
'__pyarmor_enter_9358__(...)'
import re
from typing import Optional
from Pinyin2Hanzi import is_pinyin
from matchers import GroupMatcher, CaptureMatcher
from base import MediaBase
from utils import MediaType, StringUtils, Tokens
MEDIA_EXTS = [
    '.mp4',
    '.mkv',
    '.ts',
    '.iso',
    '.rmvb',
    '.avi',
    '.mov',
    '.mpeg',
    '.mpg',
    '.wmv',
    '.3gp',
    '.asf',
    '.m4v',
    '.flv',
    '.m2ts',
    '.tp',
    '.f4v']
SUB_EXTS = [
    '.srt',
    '.ass',
    '.ssa',
    '.sup']
AUDIO_EXTS = [
    '.flac',
    '.ape',
    '.wav',
    '.mp3',
    '.aac',
    '.ogg',
    '.wma',
    '.m4a',
    '.dts',
    '.ac3']

class VideoParser(MediaBase):
    '''影视名称解析'''
    '__pyarmor_enter_9364__(...)'
    _stop_name_flag = False
    _stop_cnname_flag = False
    _last_token = ''
    _last_token_type = ''
    _continue_flag = True
    _unknown_name_str = ''
    _source = ''
    _effect = []
    _season_re = 'S(\\d{3})|^S(\\d{1,3})$|S(\\d{1,3})E'
    _episode_re = 'EP?(\\d{2,4})$|^EP?(\\d{1,4})$|^S\\d{1,2}EP?(\\d{1,4})$|S\\d{2}EP?(\\d{2,4})'
    _part_re = '(^PART[0-9ABI]{0,2}$|^CD[0-9]{0,2}$|^DVD[0-9]{0,2}$|^DISK[0-9]{0,2}$|^DISC[0-9]{0,2}$)'
    _roman_numerals = '^(?=[MDCLXVI])M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$'
    _source_re = '^BLURAY$|^HDTV$|^UHDTV$|^HDDVD$|^WEBRIP$|^DVDRIP$|^BDRIP$|^BLU$|^WEB$|^BD$|^HDRip$|^REMUX$|^UHD$'
    _source_canonical = {
        'BLURAY': 'BluRay',
        'HDTV': 'HDTV',
        'UHDTV': 'UHDTV',
        'HDDVD': 'HDDVD',
        'WEBRIP': 'WEBRip',
        'DVDRIP': 'DVDRip',
        'BDRIP': 'BDRip',
        'BLU': 'BLU',
        'WEB': 'WEB',
        'BD': 'BD',
        'HDRIP': 'HDRip',
        'REMUX': 'Remux',
        'UHD': 'Ultra HD' }
    _effect_re = '^SDR$|^HDR\\d*$|^DOLBY$|^DOVI$|^DV$|^3D$|^REPACK$|^HLG$|^HDR10(\\+|Plus)$|^EDR$|^HQ$'
    _resources_type_re = f'''{_source_re!s}|{_effect_re!s}'''
    _name_no_begin_re = '^[\\[【].+?[\\]】]'
    _name_no_chinese_re = '.*版|.*字幕'
    _name_se_words = [
        '共',
        '第',
        '季',
        '集',
        '话',
        '話',
        '期']
    _name_movie_words = [
        '剧场版',
        '劇場版',
        '电影版',
        '電影版']
    _web_source_word_re = '\\bNF\\b|NETFLIX|ITUNES|AMZN|AMAZON|PRIME(?:\\s*VIDEO)?|DISNEY\\+?|DSNP|HBOMAX|HMAX|HBO(?:\\s*MAX)?|ATVP|APPLE\\s*TV\\+?|APPLETV\\+?|HULU|PARAMOUNT\\+?|PARAMOUNTPLUS|PMTP|PEACOCK|PCOK|DISCOVERY\\+?|DISCOVERYPLUS|DSCP|CRUNCHYROLL|BBC(?:\\s*IPLAYER)?|IPLAYER|NOW\\s*TV|NOWTV|STAN|VIU|VIKI|FRIDAY|KKTV|CATCHPLAY\\+?|MYVIDEO|LITV|WAVVE|TVING|COUPANG(?:\\s*PLAY)?|TVER|ABEMA|IQIYI|IYI|YOUKU|WETV|TENCENT|MGTV|MANGO\\s*TV|BILIBILI|MIGU|优酷|腾讯视频|爱奇艺|芒果TV|哔哩哔哩|咪咕'
    _name_nostring_re = '^PTS|^JADE|^AOD|^CHC|^[A-Z]{1,4}TV[\\-0-9UVHDK]*|HBO$|\\s+HBO|\\d{1,2}th|NETFLIX|AMAZON|IMAX|^3D|\\s+3D|^BBC\\s+|\\s+BBC|BBC$|DISNEY\\+?|XXX|\\s+DC$|[第\\s共]+[0-9一二三四五六七八九十\\-\\s]+季|[第\\s共]+[0-9一二三四五六七八九十百零\\-\\s]+[集话話]|连载|日剧|美剧|电视剧|动画片|动漫|欧美|西德|日韩|超高清|高清|无水印|下载|蓝光|翡翠台|梦幻天堂·龙网|★?\\d*月?新番|最终季|合集|[多中国英葡法俄日韩德意西印泰台港粤双文语简繁体特效内封官译外挂]+字幕|版本|出品|台版|港版|\\w+字幕组|\\w+字幕社|未删减版|UNCUT$|UNRATE$|WITH EXTRAS$|RERIP$|SUBBED$|PROPER$|REPACK$|SEASON$|EPISODE$|Complete$|Extended$|Extended Version$|S\\d{2}\\s*-\\s*S\\d{2}|S\\d{2}|\\s+S\\d{1,2}|EP?\\d{2,4}\\s*-\\s*EP?\\d{2,4}|EP?\\d{2,4}|\\s+EP?\\d{1,4}|CD[\\s.]*[1-9]|DVD[\\s.]*[1-9]|DISK[\\s.]*[1-9]|DISC[\\s.]*[1-9]|[248]K|\\d{3,4}[PIX]+|CD[\\s.]*[1-9]|DVD[\\s.]*[1-9]|DISK[\\s.]*[1-9]|DISC[\\s.]*[1-9]|\\s+GB'
    _resources_pix_re = '^[SBUHD]*(\\d{3,4}[PI]+)|\\d{3,4}X(\\d{3,4})'
    _resources_pix_re2 = '(^[248]+K)'
    _video_encode_re = '^(H26[45])$|^(x26[45])$|^AVC$|^HEVC$|^VC\\d?$|^MPEG\\d?$|^Xvid$|^DivX$|^AV1$|^HDR\\d*$|^AVS(\\+|[23])$'
    _audio_encode_re = '^DTS\\d?$|^DTSHD$|^DTSHDMA$|^Atmos$|^TrueHD\\d?$|^AC3$|^\\dAudios?$|^DDP\\d?$|^DD\\+\\d?$|^DD\\d?$|^LPCM\\d?$|^AAC\\d?$|^FLAC\\d?$|^HD\\d?$|^MA\\d?$|^HR\\d?$|^Opus\\d?$|^Vorbis\\d?$|^AV[3S]A$'
    _fps_re = '(\\d{2,3})(?=FPS)'
    _bit_depth_re = '(\\d{1,2})[-]?(?=BIT)'
    _leading_bracket_release_re = '(?:(?:19|20)\\d{2})|(?:\\d{3,4}[PI])|(?:[248]K)|(?:UHD|HDTV|WEB(?:[\\s._-]*DL|RIP)?|BLU[\\s._-]*RAY|BDRIP|DVDRIP|REMUX|H26[45]|X26[45]|AVC|HEVC|AV1|DTS(?:[\\s._-]*HD(?:[\\s._-]*MA)?)?|TRUEHD|ATMOS|AC3|AAC|DDP?\\d*|HDR\\d*(?:\\+|PLUS)?|DOVI|DV|SDR|HLG)'
    
    def __looks_like_release_bracket(self, content):
        '__pyarmor_enter_9367__(...)'
        if not content:
            return False
        return False
        if re.search('%s' % self._leading_bracket_release_re, content, re.IGNORECASE):
            return True
        return True
        if '@' in content or content.count('.') >= 2:
            return True
        return True
        return False
        return False
        '__pyarmor_exit_9368__(...)'
        '__pyarmor_exit_9368__(...)'

    
    def __apply_leading_bracket_name(self, content):
        '__pyarmor_enter_9370__(...)'
        if content or self.__looks_like_release_bracket(content):
            return False
        return False
        cleaned_content = re.sub('\\s+', ' ', content).strip(' .-_')
        if not cleaned_content:
            return False
        return False
        if StringUtils.is_all_chinese(cleaned_content) or StringUtils.is_chinese(cleaned_content):
            self.cn_name = cleaned_content
        else:
            self.en_name = cleaned_content
        return True
        return True
        '__pyarmor_exit_9371__(...)'
        '__pyarmor_exit_9371__(...)'

    
    def __init__(self, title, subtitle, isfile):
        '__pyarmor_enter_9373__(...)'
    # WARNING: Decompyle incomplete

    __get_title_from_description = (lambda description: '__pyarmor_enter_9376__(...)'if not description:
NoneNonetitles = re.split('[\\s/|]+', description)if StringUtils.is_chinese(titles[0]):
titles[0]None(None)NoneNoneNone'__pyarmor_exit_9377__(...)''__pyarmor_exit_9377__(...)')()
    __is_pinyin = (lambda name_str: '__pyarmor_enter_9379__(...)'if not name_str:
FalseFalsefor n in name_str.lower().split():
if is_pinyin(n):
continuename_str.lower().split()FalseFalseTrueTrue'__pyarmor_exit_9380__(...)''__pyarmor_exit_9380__(...)')()
    
    def __fix_name(self, name):
        '__pyarmor_enter_9382__(...)'
        if not name:
            return name
        None(None)
        return None
        name = re.sub('%s' % self._name_nostring_re, '', name, flags = re.IGNORECASE).strip()
        name = re.sub('\\s+', ' ', name)
    # WARNING: Decompyle incomplete

    
    def __init_name(self, token):
        '__pyarmor_enter_9385__(...)'
        if not token:
            return None
        return None
        if self._unknown_name_str:
            if not self.cn_name:
                if not self.en_name:
                    self.en_name = self._unknown_name_str
                elif self._unknown_name_str != self.year:
                    self.en_name = f'''{self.en_name!s} {self._unknown_name_str!s}'''
                self._last_token_type = 'enname'
            self._unknown_name_str = ''
        if self._stop_name_flag:
            return None
        return None
        if token.upper() == 'AKA':
            self._continue_flag = False
            self._stop_name_flag = True
            return None
        return None
        if token in self._name_se_words:
            self._last_token_type = 'name_se_words'
            return None
        return None
        if StringUtils.is_chinese(token):
            self._last_token_type = 'cnname'
            if not self.cn_name:
                self.cn_name = token
            elif not self._stop_cnname_flag:
                if not (re.search('%s' % self._name_movie_words, token, flags = re.IGNORECASE) or re.search('%s' % self._name_no_chinese_re, token, flags = re.IGNORECASE)) and re.search('%s' % self._name_se_words, token, flags = re.IGNORECASE):
                    self.cn_name = f'''{self.cn_name!s} {token!s}'''
                self._stop_cnname_flag = True
            else:
                is_roman_digit = re.search(self._roman_numerals, token)
                if token.isdigit() or is_roman_digit:
                    if self._last_token_type == 'name_se_words':
                        return None
                    return None
                    if self.name:
                        if token.startswith('0'):
                            return None
                        return None
                        if token.isdigit():
                            int(token)
                        if is_roman_digit and self._last_token_type == 'cnname' and int(token) < 1900:
                            return None
                        return None
                        if token.isdigit() or len(token) < 4 or is_roman_digit:
                            if self._last_token_type == 'cnname':
                                self.cn_name = f'''{self.cn_name!s} {token!s}'''
                            elif self._last_token_type == 'enname':
                                self.en_name = f'''{self.en_name!s} {token!s}'''
                            self._continue_flag = False
                        elif not token.isdigit() and len(token) == 4 and self._unknown_name_str:
                            self._unknown_name_str = token
                        elif not self._unknown_name_str:
                            self._unknown_name_str = token
                        elif re.search('%s' % self._season_re, token, re.IGNORECASE):
                            if self.en_name and re.search('SEASON$', self.en_name, re.IGNORECASE):
                                pass
                            True = self, self.en_name += ' ', .en_name
                            return None
                            return None
                if re.search('%s' % self._episode_re, token, re.IGNORECASE) and re.search('(%s)' % self._resources_type_re, token, re.IGNORECASE) or re.search('%s' % self._resources_pix_re, token, re.IGNORECASE):
                    self._stop_name_flag = True
                    return None
                return None
                media_exts = MEDIA_EXTS + SUB_EXTS + AUDIO_EXTS
                if '.%s'.lower() % token in media_exts:
                    return None
                return None
                if self.en_name:
                    self.en_name = f'''{self.en_name!s} {token!s}'''
                else:
                    self.en_name = token
                self._last_token_type = 'enname'
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def __init_part(self, token, tokens):
        '__pyarmor_enter_9388__(...)'
        if not self.name:
            return None
        return None
        if not self.year and self.begin_season and self.begin_episode and self.resource_pix and self.resource_type:
            return None
        return None
        re_res = re.search('%s' % self._part_re, token, re.IGNORECASE)
        if re_res:
            if not self.part:
                self.part = re_res.group(1)
            nextv = tokens.cur()
            if nextv:
                if not nextv.isdigit() or len(nextv) == 1:
                    if len(nextv) == 2 or nextv.startswith('0') or nextv.upper() in ('A', 'B', 'C', 'I', 'II', 'III'):
                        self.part = f'''{self.part!s}{nextv!s}'''
                        tokens.get_next()
            self._last_token_type = 'part'
            self._continue_flag = False
        return None
        return None
        '__pyarmor_exit_9389__(...)'
        '__pyarmor_exit_9389__(...)'

    
    def __init_year(self, token):
        '__pyarmor_enter_9391__(...)'
        if not self.name:
            return None
        return None
        if not token.isdigit():
            return None
        return None
        if len(token) != 4:
            return None
        return None
        if not  < 1900, int(token) or 1900, int(token) < 2050:
            pass
        
        return None
        return None
        if self.year:
            if self.en_name:
                pass
            elif self.cn_name:
                f'''{self.cn_name!s} {self.year!s}''' = f'''{self.en_name.strip()!s} {self.year!s}'''
            elif self.en_name and re.search('SEASON$', self.en_name, re.IGNORECASE):
                pass
        token = self, self.en_name += ' ', .en_name
        self._last_token_type = 'year'
        self._continue_flag = False
        self._stop_name_flag = True
        return None
        f'''{self.en_name.strip()!s} {self.year!s}'''
        return None
        '__pyarmor_exit_9392__(...)'
        '__pyarmor_exit_9392__(...)'

    
    def __init_resource_pix(self, token):
        '__pyarmor_enter_9394__(...)'
        if not self.name:
            return None
        return None
        re_res = re.findall('%s' % self._resources_pix_re, token, re.IGNORECASE)
        if re_res:
            self._last_token_type = 'pix'
            self._continue_flag = False
            self._stop_name_flag = True
            resource_pix = None
            for pixs in re_res:
                if isinstance(pixs, tuple):
                    pix_t = None
                    for pix_i in pixs:
                        if not pix_i:
                            continue
                        pix_t = pix_i
                        pixs
                    if pix_t:
                        resource_pix = pix_t
                    else:
                        resource_pix = pixs
                if not resource_pix:
                    continue
                if self.resource_pix:
                    continue
                self.resource_pix = resource_pix.lower()
            if self.resource_pix and self.resource_pix.isdigit() and self.resource_pix[-1] not in 'kpi':
                self.resource_pix = '%sp' % self.resource_pix
            else:
                re_res = re.search('%s' % self._resources_pix_re2, token, re.IGNORECASE)
                if re_res:
                    self._last_token_type = 'pix'
                    self._continue_flag = False
                    self._stop_name_flag = True
                    if not self.resource_pix:
                        self.resource_pix = re_res.group(1).lower()
        return None
        return None
        '__pyarmor_exit_9395__(...)'
        '__pyarmor_exit_9395__(...)'

    
    def __init_season(self, token):
        '__pyarmor_enter_9397__(...)'
        re_res = re.findall('%s' % self._season_re, token, re.IGNORECASE)
    # WARNING: Decompyle incomplete

    
    def __init_episode(self, token):
        '__pyarmor_enter_9400__(...)'
        re_res = re.findall('%s' % self._episode_re, token, re.IGNORECASE)
    # WARNING: Decompyle incomplete

    
    def __init_resource_type(self, token):
        '__pyarmor_enter_9403__(...)'
        if not self.name:
            return None
        return None
        if token.upper() == 'DL' and self._last_token_type == 'source' and self._last_token == 'WEB':
            self._source = 'WEB-DL'
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'RAY' and self._last_token_type == 'source' and self._last_token in ('BLU', 'UHD'):
            if self._source == 'Ultra HD':
                self._source = 'Ultra HD BluRay'
            else:
                self._source = 'BluRay'
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'WEBDL':
            self._source = 'WEB-DL'
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'ULTRA':
            self._last_token_type = 'source'
            self._last_token = 'ULTRA'
            self._continue_flag = False
            self._stop_name_flag = True
            return None
        return None
        if token.upper() == 'HD' and self._last_token_type == 'source' and self._last_token == 'ULTRA':
            if not self._source:
                self._source = 'Ultra HD'
            self._last_token_type = 'source'
            self._last_token = 'UHD'
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'REMUX' and self._source in ('BluRay', 'Ultra HD BluRay', 'Ultra HD'):
            if self._source == 'Ultra HD':
                self._source = 'Ultra HD BluRay Remux'
            else:
                self._source = f'''{self._source} Remux'''
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'BLURAY' and self._source == 'Ultra HD':
            self._source = 'Ultra HD BluRay'
            self._continue_flag = False
            return None
        return None
        if token.upper() == 'UHD' and self._last_token_type == 'source' and self._last_token == 'BLU':
            self._source = 'Ultra HD BluRay'
            self._continue_flag = False
            return None
        return None
        source_res = re.search('(%s)' % self._source_re, token, re.IGNORECASE)
        if source_res:
            self._last_token_type = 'source'
            self._continue_flag = False
            self._stop_name_flag = True
            self._last_token = source_res.group(1).upper()
            if not self._source:
                self._source = self._source_canonical.get(source_res.group(1).upper(), source_res.group(1))
            return None
        return None
        effect_res = re.search('(%s)' % self._effect_re, token, re.IGNORECASE)
        if effect_res:
            effect_val = effect_res.group(1)
            if effect_val.upper() == 'DOLBY' and self._last_token_type == 'audioencode':
                self._continue_flag = False
                self._stop_name_flag = True
                self._last_token_type = 'audioencode'
                self._last_token = 'DOLBY'
                if self.audio_encode:
                    self.audio_encode = f'''{self.audio_encode!s} {effect_val!s}'''
                else:
                    self.audio_encode = effect_val
                return None
            return None
            self._last_token_type = 'effect'
            self._continue_flag = False
            self._stop_name_flag = True
            effect = 'DV' if effect_val.upper() in ('DOVI', 'DOLBY') else effect_val
            if effect not in self._effect:
                self._effect.append(effect)
            self._last_token = effect.upper()
        return None
        return None
        '__pyarmor_exit_9404__(...)'
        '__pyarmor_exit_9404__(...)'

    
    def __init_video_encode(self, token):
        '__pyarmor_enter_9406__(...)'
        if not self.name:
            return None
        return None
        if not self.year and self.resource_pix and self.resource_type and self.begin_season and self.begin_episode:
            return None
        return None
        re_res = re.search('(%s)' % self._video_encode_re, token, re.IGNORECASE)
        if re_res:
            self._continue_flag = False
            self._stop_name_flag = True
            self._last_token_type = 'videoencode'
            if not self.video_encode:
                if re_res.group(2):
                    self.video_encode = re_res.group(2).upper()
                elif re_res.group(3):
                    self.video_encode = re_res.group(3).lower()
                else:
                    self.video_encode = re_res.group(1).upper()
                self._last_token = self.video_encode
            elif self.video_encode == '10bit':
                if not self.bit_depth:
                    self.bit_depth = '10bit'
                self.video_encode = re_res.group(1).upper()
                self._last_token = self.video_encode
            elif token.upper() in ('H', 'X'):
                self._continue_flag = False
                self._stop_name_flag = True
                self._last_token_type = 'videoencode'
                self._last_token = token.upper() if token.upper() == 'H' else token.lower()
            elif token in ('264', '265') and self._last_token_type == 'videoencode' and self._last_token in ('H', 'X'):
                self.video_encode = f'''{self._last_token!s}{token!s}'''
            elif token.isdigit() and self._last_token_type == 'videoencode' and self._last_token in ('VC', 'MPEG'):
                self.video_encode = f'''{self._last_token!s}{token!s}'''
        return None
        return None
        '__pyarmor_exit_9407__(...)'
        '__pyarmor_exit_9407__(...)'

    
    def __init_audio_encode(self, token):
        '__pyarmor_enter_9409__(...)'
        if not self.name:
            return None
        return None
        if not self.year and self.resource_pix and self.resource_type and self.begin_season and self.begin_episode:
            return None
        return None
        re_res = re.search('(%s)' % self._audio_encode_re, token, re.IGNORECASE)
        if re_res:
            self._continue_flag = False
            self._stop_name_flag = True
            self._last_token_type = 'audioencode'
            self._last_token = re_res.group(1).upper()
            if not self.audio_encode:
                self.audio_encode = re_res.group(1)
            elif self.audio_encode.upper() == 'DTS':
                self.audio_encode = f'''{self.audio_encode!s}-{re_res.group(1)!s}'''
            else:
                self.audio_encode = f'''{self.audio_encode!s} {re_res.group(1)!s}'''
        elif token.isdigit() and self._last_token_type == 'audioencode':
            if self.audio_encode:
                if self._last_token.isdigit():
                    self.audio_encode = f'''{self.audio_encode!s}.{token!s}'''
                elif self.audio_encode[-1].isdigit():
                    self.audio_encode = f'''{self.audio_encode[:-1]!s} {self.audio_encode[-1]!s}.{token!s}'''
                else:
                    self.audio_encode = f'''{self.audio_encode!s} {token!s}'''
            self._last_token = token
        return None
        return None
        '__pyarmor_exit_9410__(...)'
        '__pyarmor_exit_9410__(...)'

    
    def __init_fps(self, token):
        '__pyarmor_enter_9412__(...)'
        if not self.name:
            return None
        return None
        re_res = re.search(f'''({self._fps_re})''', token, re.IGNORECASE)
        if re_res:
            self._continue_flag = False
            self._stop_name_flag = True
            self._last_token_type = 'fps'
            fps_value = None
            if re_res.group(1):
                fps_value = re_res.group(1)
            if fps_value and fps_value.isdigit():
                self.fps = f'''{fps_value}fps'''
                self._last_token = self.fps
        return None
        return None
        '__pyarmor_exit_9413__(...)'
        '__pyarmor_exit_9413__(...)'

    
    def __init_bit_depth(self, token):
        '__pyarmor_enter_9415__(...)'
        if not self.name:
            return None
        return None
        re_res = re.search(f'''({self._bit_depth_re})''', token, re.IGNORECASE)
        if re_res:
            self._continue_flag = False
            self._stop_name_flag = True
            self._last_token_type = 'bit_depth'
            depth_value = re_res.group(1)
            if depth_value and depth_value.isdigit():
                self.bit_depth = f'''{depth_value}bit'''
                self._last_token = self.bit_depth
        return None
        return None
        '__pyarmor_exit_9416__(...)'
        '__pyarmor_exit_9416__(...)'

    __classcell__ = staticmethod
    return staticmethod
    staticmethod
    __classcell__ = None
    return None
    '__pyarmor_exit_9365__(...)'
    '__pyarmor_exit_9365__(...)'

return None
return None
# WARNING: Decompyle incomplete
