# File: main.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: main.py.1shot.das

'''NanShare 启动脚本'''
'__pyarmor_enter_1858__(...)'
AUTH_SERVER_URL = 'http://111.170.131.114:47187'
import os
import sys
import time
import logging
import warnings
import threading
from datetime import datetime
warnings.filterwarnings('ignore', category = DeprecationWarning, module = 'pkg_resources')
warnings.filterwarnings('ignore', message = '.*pkg_resources.*')
warnings.filterwarnings('ignore', module = 'zhconv')
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PROJECT_ROOT)
from core.logger import logger
from core.caddy_manager import caddy_manager
from core.config_manager import config_manager
from core.auth_manager import auth_manager

class NanShareService:
    '''NanShare 服务管理'''
    '__pyarmor_enter_1861__(...)'
    
    def __init__(self):
        '__pyarmor_enter_1864__(...)'
        self.project_root = PROJECT_ROOT
        os.chdir(self.project_root)
        self._create_dirs()
        return None
        return None
        '__pyarmor_exit_1865__(...)'
        '__pyarmor_exit_1865__(...)'

    
    def _create_dirs(self):
        '''创建必要的目录'''
        '__pyarmor_enter_1867__(...)'
        dirs = [
            'logs',
            'caddy',
            'config']
        for d in dirs:
            path = os.path.join(self.project_root, d)
            if os.path.exists(path):
                continue
            os.makedirs(path)
        return None
        return None
        '__pyarmor_exit_1868__(...)'
        '__pyarmor_exit_1868__(...)'

    
    def _start_telegram_bot(self):
        '''启动 Telegram Bot'''
        '__pyarmor_enter_1870__(...)'
        start_telegram_bot_thread = start_telegram_bot_thread
        import core.telegram_bot
        result = start_telegram_bot_thread()
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _start_scheduler(self):
        '''启动定时任务调度器'''
        '__pyarmor_enter_1873__(...)'
        task_scheduler = task_scheduler
        import core.task_queue
        setup_scheduled_tasks = setup_scheduled_tasks
        import core.scheduled_tasks
        setup_scheduled_tasks(AUTH_SERVER_URL)
        task_scheduler.start()
        return None
        return None
        '__pyarmor_exit_1874__(...)'
        '__pyarmor_exit_1874__(...)'

    
    def start(self):
        '''启动服务'''
        '__pyarmor_enter_1876__(...)'
        logger.info('==================================================')
        logger.info('NanShare 服务启动中...')
        logger.info('==================================================')
        logger.info('正在验证授权...')
        local_key = None
        key_file = os.path.join(self.project_root, 'key.txt')
    # WARNING: Decompyle incomplete

    
    def stop(self):
        '''停止服务'''
        '__pyarmor_enter_1879__(...)'
        logger.info('停止服务...')
        task_scheduler = task_scheduler
        import core.task_queue
        task_scheduler.stop()
        task_queue_manager = task_queue_manager
        import core.task_queue
        task_queue_manager.stop()
        tg_forward_engine = tg_forward_engine
        import core.tg_forward
        tg_forward_engine.stop_all()
        file_transfer_service = file_transfer_service
        import core.file_transfer_service
        file_transfer_service.stop()
        caddy_manager.stop()
        logger.info('服务已停止')
        return None
        return None
        continue
        continue
        continue
        continue
        '__pyarmor_exit_1880__(...)'
        '__pyarmor_exit_1880__(...)'

    return None
    return None
    '__pyarmor_exit_1862__(...)'
    '__pyarmor_exit_1862__(...)'


def main():
    '__pyarmor_enter_1882__(...)'
    service = NanShareService()
    service.start()
    service.stop()
    return None
    return None
# WARNING: Decompyle incomplete

if __name__ == '__main__':
    main()
return None
return None
'__pyarmor_exit_1859__(...)'
'__pyarmor_exit_1859__(...)'
