# File: api_tg_forward_logs.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_tg_forward_logs.py.1shot.das

'''TG 转发日志 API'''
'__pyarmor_enter_8740__(...)'
from math import ceil
from flask import jsonify, request
from  import api_bp
from logger import logger
from nanshare_db import nanshare_db
get_tg_forward_logs = (lambda : '__pyarmor_enter_8743__(...)'if not nanshare_db:
(jsonify({
'success': False,
'message': '数据库未初始化' }), 500)None(None)Nonepage = request.args.get('page', 1, type = int)page_size = request.args.get('page_size', 30, type = int)if not request.args.get('forward_config_id', '').strip():
request.args.get('forward_config_id', '').strip()forward_config_id = Noneif not request.args.get('tg_config_id', '').strip():
request.args.get('tg_config_id', '').strip()tg_config_id = Noneif not request.args.get('source_id', '').strip():
request.args.get('source_id', '').strip()source_id = Noneif not request.args.get('target_id', '').strip():
request.args.get('target_id', '').strip()target_id = Noneif not request.args.get('status', '').strip():
request.args.get('status', '').strip()status = Noneif not request.args.get('keyword', '').strip():
request.args.get('keyword', '').strip()keyword = None(logs, total) = nanshare_db.get_tg_forward_logs(page = page, page_size = page_size, forward_config_id = forward_config_id, tg_config_id = tg_config_id, source_id = source_id, target_id = target_id, status = status, keyword = keyword)total_pages = ceil(total / page_size) if page_size > 0 else 1jsonify({
'success': True,
'data': {
'list': logs,
'total': total,
'page': max(page, 1),
'page_size': page_size,
'total_pages': total_pages } })None(None)None# WARNING: Decompyle incomplete
)()
get_tg_forward_log = (lambda log_id: '__pyarmor_enter_8746__(...)'if not nanshare_db:
(jsonify({
'success': False,
'message': '数据库未初始化' }), 500)None(None)Nonelog = nanshare_db.get_tg_forward_log(log_id)if not log:
(jsonify({
'success': False,
'message': '记录不存在' }), 404)None(None)Nonejsonify({
'success': True,
'data': log })None(None)None# WARNING: Decompyle incomplete
)()
batch_delete_tg_forward_logs = (lambda : '__pyarmor_enter_8749__(...)'if not nanshare_db:
(jsonify({
'success': False,
'message': '数据库未初始化' }), 500)None(None)Noneif not request.get_json(silent = True):
request.get_json(silent = True)payload = { }log_ids = payload.get('log_ids', [])if not log_ids:
(jsonify({
'success': False,
'message': '缺少要删除的日志 ID' }), 400)None(None)Nonedeleted = nanshare_db.delete_tg_forward_logs(log_ids)jsonify({
'success': True,
'message': f'''已删除 {deleted} 条记录''',
'data': {
'deleted_count': deleted } })None(None)None# WARNING: Decompyle incomplete
)()
clear_tg_forward_logs = (lambda : '__pyarmor_enter_8752__(...)'if not nanshare_db:
(jsonify({
'success': False,
'message': '数据库未初始化' }), 500)None(None)Nonedeleted = nanshare_db.delete_all_tg_forward_logs()jsonify({
'success': True,
'message': f'''已清空 {deleted} 条记录''',
'data': {
'deleted_count': deleted } })None(None)None# WARNING: Decompyle incomplete
)()
get_tg_forward_log_filter_options = (lambda : '__pyarmor_enter_8755__(...)'if not nanshare_db:
(jsonify({
'success': False,
'message': '数据库未初始化' }), 500)None(None)Noneoptions = nanshare_db.get_tg_forward_log_filter_options()jsonify({
'success': True,
'data': options })None(None)None# WARNING: Decompyle incomplete
)()
return None
api_bp.route('/tg_forward/logs/filter_options', methods = [
    'GET'])
return None
'__pyarmor_exit_8741__(...)'
'__pyarmor_exit_8741__(...)'
return api_bp.route('/tg_forward/logs', methods = [
    'DELETE'])
