# File: api_strm_checker.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_strm_checker.py.1shot.das

'''无效 115 分享 STRM 检测 API'''
'__pyarmor_enter_8506__(...)'
import asyncio
import threading
from flask import request, jsonify
from  import api_bp
from logger import logger
_scan_task_status = {
    'running': False,
    'progress': '',
    'result_id': None,
    'error': None }
start_strm_scan = (lambda : '__pyarmor_enter_8509__(...)'if _scan_task_status['running']:
(jsonify({
'success': False,
'message': '已有扫描任务正在执行' }), 400)None(None)Nonedata = request.get_json()directory = data.get('directory', '')if not directory:
(jsonify({
'success': False,
'message': '请指定扫描目录' }), 400)None(None)Noneimport osif not os.path.isdir(directory):
(jsonify({
'success': False,
'message': f'''目录不存在: {directory}''' }), 400)None(None)None_scan_task_status['running'] = True_scan_task_status['progress'] = '正在扫描...'_scan_task_status['result_id'] = None_scan_task_status['error'] = None
def run_scan():
'__pyarmor_enter_8512__(...)'import multiprocessingsubprocess_scan_worker = subprocess_scan_workersend_result_to_telegram = send_result_to_telegram_scan_results_cache = _scan_results_cacheimport strm_checkerresult_queue = multiprocessing.Queue()proc = multiprocessing.Process(target = subprocess_scan_worker, args = (directory, result_queue), daemon = True)proc.start()result = result_queue.get(timeout = 7200)proc.join(timeout = 30)if proc.is_alive():
proc.kill()if 'error' in result and 'id' not in result:
_scan_task_status['error'] = result['error']logger.error(f'''STRM 扫描失败: {result['error']}''')else:
_scan_results_cache[result['id']] = result_scan_task_status['result_id'] = result['id']if result.get('invalid_shares'):
send_result_to_telegram(result)_scan_task_status['running'] = False_scan_task_status['progress'] = ''NoneNone# WARNING: Decompyle incomplete
thread = threading.Thread(target = run_scan, daemon = True, name = 'StrmChecker')thread.start()jsonify({
'success': True,
'message': '扫描任务已启动' })None(None)None'__pyarmor_exit_8510__(...)''__pyarmor_exit_8510__(...)')()
get_scan_status = (lambda : '__pyarmor_enter_8515__(...)'jsonify({
'success': True,
'data': {
'running': _scan_task_status['running'],
'progress': _scan_task_status['progress'],
'result_id': _scan_task_status['result_id'],
'error': _scan_task_status['error'] } })None(None)None'__pyarmor_exit_8516__(...)''__pyarmor_exit_8516__(...)')()
get_scan_results = (lambda : '__pyarmor_enter_8518__(...)'get_scan_results_cache = get_scan_results_cacheimport strm_checkercache = get_scan_results_cache()results = []for rid, data in cache.items():
data['directory']({
'id': data['total_strm_files'],
'directory': data['total_shares'],
'total_strm_files': len(data.get('invalid_shares', [])),
'total_shares': None,
'invalid_count': sum,
'invalid_file_count': (lambda .0: pass# WARNING: Decompyle incomplete
)(data.get('invalid_shares', [])()),
            'valid_shares_count': data['valid_shares_count'],
            'scan_time': data['scan_time'],
            'timestamp': data['timestamp'],
            'api_error': data.get('api_error') })
    results.sort(key = (lambda x: x['timestamp']), reverse = True)
    return jsonify({
        'success': True,
        'data': results })
    cache.items()(None)
    return None
    '__pyarmor_exit_8519__(...)'
    '__pyarmor_exit_8519__(...)'
)()
get_scan_result_detail = (lambda result_id: '__pyarmor_enter_8521__(...)'get_scan_result = get_scan_resultimport strm_checkerresult = get_scan_result(result_id)if not result:
(jsonify({
'success': False,
'message': '扫描结果不存在或已过期' }), 404)None(None)Nonejsonify({
'success': True,
'data': result })None(None)None'__pyarmor_exit_8522__(...)''__pyarmor_exit_8522__(...)')()
delete_scan_result_api = (lambda result_id: '__pyarmor_enter_8524__(...)'delete_scan_result = delete_scan_resultimport strm_checkerif delete_scan_result(result_id):
jsonify({
'success': True,
'message': '已删除' })None(None)None(jsonify({
'success': False,
'message': '扫描结果不存在' }), 404)None(None)None'__pyarmor_exit_8525__(...)''__pyarmor_exit_8525__(...)')()
view_scan_result_full = (lambda result_id: '__pyarmor_enter_8527__(...)'Response = Responseimport flaskget_scan_result = get_scan_resultimport strm_checkerimport jsonresult = get_scan_result(result_id)if not result:
Response('扫描结果不存在或已过期', status = 404, content_type = 'text/plain; charset=utf-8')None(None)Nonejson_content = json.dumps(result, ensure_ascii = False, indent = 2)Response(json_content, content_type = 'application/json; charset=utf-8')None(None)None'__pyarmor_exit_8528__(...)''__pyarmor_exit_8528__(...)')()
delete_invalid_files = (lambda result_id: '__pyarmor_enter_8530__(...)'delete_invalid_strm_files = delete_invalid_strm_filesimport strm_checkerresult = delete_invalid_strm_files(result_id)if result['success']:
jsonify({
'success': True,
'message': f'''删除完成: 成功 {result['deleted']} 个, 失败 {result['failed']} 个''',
'data': result })None(None)None(jsonify({
'success': False,
'message': result.get('message', '操作失败') }), 400)None(None)None'__pyarmor_exit_8531__(...)''__pyarmor_exit_8531__(...)')()
return None
api_bp.route('/strm_checker/delete_files/<result_id>', methods = [
    'POST'])
return None
'__pyarmor_exit_8507__(...)'
'__pyarmor_exit_8507__(...)'
return api_bp.route('/strm_checker/results/<result_id>', methods = [
    'DELETE'])
