# File: api_share_115.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_share_115.py.1shot.das

'''
115 分享 API 模块

提供通过 HTTP API 直接获取 115 分享直链的功能
用于 Emby 扫库等场景

请求格式:
GET /api/?share_code=xxx&receive_code=xxx&id=xxx
只要 URL 中包含 share_code、receive_code、id 三个参数即可

返回: 302 重定向到直链
'''
'__pyarmor_enter_8275__(...)'
import time
import threading
import httpx
from orjson import dumps, loads
from p115rsacipher import encrypt, decrypt
from flask import Blueprint, request, redirect, Response
from  import api_bp
from config_manager import config_manager
from logger import logger_302api as logger
from redirect import RedirectHandler

class ShareApiCache:
    '''分享 API 缓存管理器（线程安全）'''
    '__pyarmor_enter_8278__(...)'
    
    def __init__(self):
        '__pyarmor_enter_8281__(...)'
        self._cache = { }
        self._lock = threading.RLock()
        return None
        return None
        '__pyarmor_exit_8282__(...)'
        '__pyarmor_exit_8282__(...)'

    
    def _generate_key(self, share_code, receive_code, file_id):
        '''生成缓存键'''
        '__pyarmor_enter_8284__(...)'
        return f'''{share_code}|{receive_code}|{file_id}'''
        None(None)
        return None
        '__pyarmor_exit_8285__(...)'
        '__pyarmor_exit_8285__(...)'

    
    def get(self, share_code, receive_code, file_id):
        '''获取缓存的直链（非阻塞）'''
        '__pyarmor_enter_8287__(...)'
        key = self._generate_key(share_code, receive_code, file_id)
    # WARNING: Decompyle incomplete

    
    def set(self, share_code, receive_code, file_id, url, ttl):
        '''设置缓存（非阻塞）'''
        '__pyarmor_enter_8290__(...)'
        key = self._generate_key(share_code, receive_code, file_id)
        now = time.time()
    # WARNING: Decompyle incomplete

    
    def clear_expired(self):
        '''清理过期缓存（非阻塞）'''
        '__pyarmor_enter_8293__(...)'
        now = time.time()
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_8279__(...)'
    '__pyarmor_exit_8279__(...)'

_share_api_cache = ShareApiCache()

def parse_cookies(cookie_str):
    '''解析cookie'''
    '__pyarmor_enter_8296__(...)'
    cookies = { }
    for item in cookie_str.split(';'):
        if not '=' in item:
            continue
        (key, value) = item.strip().split('=', 1)
        cookies[key] = value
    return cookies
    None(None)
    return None
    '__pyarmor_exit_8297__(...)'
    '__pyarmor_exit_8297__(...)'


def get_download_url(share_code, receive_code, file_id, config_name):
    '''获取下载直链'''
    '__pyarmor_enter_8299__(...)'
    config = config_manager.get_115_config_by_name(config_name)
    if not config:
        raise Exception(f'''未找到 115 配置: {config_name}''')
    cookie = config.get('cookie', '')
    cookies = parse_cookies(cookie)
    payload = {
        'share_code': share_code,
        'receive_code': receive_code,
        'file_id': int(file_id) }
    encrypted_data = encrypt(dumps(payload)).decode('utf-8')
    resp = httpx.post('http://proapi.115.com/app/share/downurl', data = {
        'data': encrypted_data }, cookies = cookies, timeout = 10)
    if resp.status_code != 200:
        raise Exception(f'''请求失败: HTTP {resp.status_code}''')
    json_data = loads(resp.content)
    if not json_data.get('state'):
        error_msg = json_data.get('msg', json_data.get('error', '未知错误'))
        raise Exception(f'''获取失败: {error_msg}''')
    decrypted_data = loads(decrypt(json_data['data']))
    if not decrypted_data or decrypted_data.get('url'):
        raise Exception('响应中没有下载链接')
    return decrypted_data['url']['url']
    None(None)
    return None
    '__pyarmor_exit_8300__(...)'
    '__pyarmor_exit_8300__(...)'


def get_share_api_config():
    '''获取分享 API 配置'''
    '__pyarmor_enter_8302__(...)'
    return config_manager.get_share_api_config()
    None(None)
    return None
    '__pyarmor_exit_8303__(...)'
    '__pyarmor_exit_8303__(...)'

share_115_api = (lambda : '__pyarmor_enter_8305__(...)'share_code = request.args.get('share_code', '')receive_code = request.args.get('receive_code', '')file_id = request.args.get('id', '')if not share_code and receive_code or file_id:
Response('参数不完整，需要 share_code, receive_code, id', status = 400)None(None)Noneconfig = get_share_api_config()if not config.get('enabled', False):
logger.warning(f'''115 分享 API 请求被拒绝: 功能未启用 | share_code={share_code} | id={file_id}''')Response('115 分享 API 未启用，请在设置中启用', status = 403)None(None)Noneconfig_name = config.get('use_115_config', '')if not config_name:
Response('未配置 115 账号', status = 500)None(None)Nonereceive_code = receive_code[:4]known_params = {
'id',
'share_code',
'receive_code'}name = (lambda .0: pass# WARNING: Decompyle incomplete
)(request.args(), '')
    name_part = f''' | name={name}''' if name else ''
    cache_ttl = config.get('cache_ttl', 10)
    cached_url = _share_api_cache.get(share_code, receive_code, file_id)
    if cached_url:
        logger.info(f'''115 分享 API 请求 | share_code={share_code} | receive_code={receive_code} | id={file_id}{name_part}''')
        logger.info(f'''命中缓存 | 直链: {cached_url}''')
        return RedirectHandler.create_redirect_response(cached_url)
    None(None)
    return None
    logger.info(f'''115 分享 API 请求 | share_code={share_code} | receive_code={receive_code} | id={file_id}{name_part}''')
    start_time = time.time()
    direct_url = get_download_url(share_code, receive_code, file_id, config_name)
    elapsed = time.time() - start_time
    _share_api_cache.set(share_code, receive_code, file_id, direct_url, cache_ttl)
    logger.info(f'''请求成功 | 耗时 {elapsed:.2f}s | 直链: {direct_url}''')
    return RedirectHandler.create_redirect_response(direct_url)
    None(None)
    return None
# WARNING: Decompyle incomplete
)()

def handle_115_share_api(share_code, receive_code, file_id):
    '''处理 115 分享 API 请求（供其他模块调用）'''
    '__pyarmor_enter_8308__(...)'
    share_config = get_share_api_config()
    if not share_config.get('enabled', False):
        logger.warning(f'''115 分享 API 请求被拒绝: 功能未启用 | share_code={share_code} | id={file_id}''')
        return Response('115 分享 API 未启用，请在设置中启用', status = 403)
    None(None)
    return None
    config_name = share_config.get('use_115_config', '')
    if not config_name:
        return Response('未配置 115 账号', status = 500)
    None(None)
    return None
    receive_code = receive_code[:4]
    known_params = {
        'id',
        'share_code',
        'receive_code'}
    name = (lambda .0: pass# WARNING: Decompyle incomplete
)(request.args(), '')
    name_part = f''' | name={name}''' if name else ''
    cache_ttl = share_config.get('cache_ttl', 10)
    cached_url = _share_api_cache.get(share_code, receive_code, file_id)
    if cached_url:
        logger.info(f'''115 分享 API 请求 | share_code={share_code} | receive_code={receive_code} | id={file_id}{name_part}''')
        logger.info(f'''命中缓存 | 直链: {cached_url}''')
        return RedirectHandler.create_redirect_response(cached_url)
    None(None)
    return None
    logger.info(f'''115 分享 API 请求 | share_code={share_code} | receive_code={receive_code} | id={file_id}{name_part}''')
    start_time = time.time()
    direct_url = get_download_url(share_code, receive_code, file_id, config_name)
    elapsed = time.time() - start_time
    _share_api_cache.set(share_code, receive_code, file_id, direct_url, cache_ttl)
    logger.info(f'''请求成功 | 耗时 {elapsed:.2f}s | 直链: {direct_url}''')
    return RedirectHandler.create_redirect_response(direct_url)
    None(None)
    return None
# WARNING: Decompyle incomplete

return None
api_bp.route('/share_115', methods = [
    'GET'])
return None
'__pyarmor_exit_8276__(...)'
'__pyarmor_exit_8276__(...)'
