# File: api_tg_forward.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_tg_forward.py.1shot.das

'''TG 消息转发 API'''
'__pyarmor_enter_8311__(...)'
import uuid
from flask import request, jsonify
from  import api_bp
from config_manager import config_manager
from logger import logger
BLOCKED_CHANNEL_IDS = [
    '-1003092300229',
    '-1003714442743']
get_tg_forward_configs = (lambda : '__pyarmor_enter_8314__(...)'configs = config_manager.get_tg_forward_configs()jsonify({
'success': True,
'data': configs })None(None)None'__pyarmor_exit_8315__(...)''__pyarmor_exit_8315__(...)')()
add_tg_forward_config = (lambda : '__pyarmor_enter_8317__(...)'data = request.get_json()if not data:
(jsonify({
'success': False,
'message': '无效的请求数据' }), 400)None(None)Noneif not data.get('name'):
(jsonify({
'success': False,
'message': '请填写配置名称' }), 400)None(None)Nonesource_id = str(data.get('source_channel', '')).strip()target_id = str(data.get('target_channel', '')).strip()if source_id in BLOCKED_CHANNEL_IDS or target_id in BLOCKED_CHANNEL_IDS:
(jsonify({
'success': False,
'message': '此频道不可添加' }), 403)None(None)Nonedata['id'] = str(uuid.uuid4())[:8]if config_manager.add_tg_forward_config(data):
jsonify({
'success': True,
'data': data,
'message': '配置已添加' })None(None)None(jsonify({
'success': False,
'message': '添加失败' }), 500)None(None)None'__pyarmor_exit_8318__(...)''__pyarmor_exit_8318__(...)')()
update_tg_forward_config = (lambda config_id: '__pyarmor_enter_8320__(...)'data = request.get_json()if not data:
(jsonify({
'success': False,
'message': '无效的请求数据' }), 400)None(None)Nonesource_id = str(data.get('source_channel', '')).strip()target_id = str(data.get('target_channel', '')).strip()if source_id in BLOCKED_CHANNEL_IDS or target_id in BLOCKED_CHANNEL_IDS:
(jsonify({
'success': False,
'message': '此频道不可添加' }), 403)None(None)Nonedata['id'] = config_idif config_manager.update_tg_forward_config(config_id, data):
jsonify({
'success': True,
'message': '配置已更新' })None(None)None(jsonify({
'success': False,
'message': '更新失败' }), 500)None(None)None'__pyarmor_exit_8321__(...)''__pyarmor_exit_8321__(...)')()
delete_tg_forward_config = (lambda config_id: '__pyarmor_enter_8323__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardtg_forward_engine.stop(config_id)if config_manager.delete_tg_forward_config(config_id):
jsonify({
'success': True,
'message': '配置已删除' })None(None)None(jsonify({
'success': False,
'message': '删除失败' }), 500)None(None)None# WARNING: Decompyle incomplete
)()
start_tg_forward = (lambda config_id: '__pyarmor_enter_8326__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardresult = tg_forward_engine.start(config_id)jsonify(result)None(None)None# WARNING: Decompyle incomplete
)()
stop_tg_forward = (lambda config_id: '__pyarmor_enter_8329__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardresult = tg_forward_engine.stop(config_id)jsonify(result)None(None)None# WARNING: Decompyle incomplete
)()
get_tg_forward_status = (lambda : '__pyarmor_enter_8332__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardstatus = tg_forward_engine.get_status()jsonify({
'success': True,
'data': status })None(None)None# WARNING: Decompyle incomplete
)()
get_tg_forward_status_single = (lambda config_id: '__pyarmor_enter_8335__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardstatus = tg_forward_engine.get_status(config_id)jsonify({
'success': True,
'data': status })None(None)None# WARNING: Decompyle incomplete
)()
get_used_tg_configs = (lambda : '__pyarmor_enter_8338__(...)'tg_forward_engine = tg_forward_engineimport tg_forwardused = tg_forward_engine.get_used_tg_config_ids()jsonify({
'success': True,
'data': used })None(None)None# WARNING: Decompyle incomplete
)()
return None
api_bp.route('/tg_forward/used_tg_configs', methods = [
    'GET'])
return None
'__pyarmor_exit_8312__(...)'
'__pyarmor_exit_8312__(...)'
return api_bp.route('/tg_forward/status', methods = [
    'GET'])
