# File: api_empty_folder.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_empty_folder.py.1shot.das

'''空文件夹清理 API'''
'__pyarmor_enter_7897__(...)'
import os
from flask import request, jsonify
from  import api_bp
from empty_folder_scanner import scan_state, start_scan, delete_folders
start_empty_folder_scan = (lambda : '__pyarmor_enter_7900__(...)'if scan_state['running']:
(jsonify({
'success': False,
'message': '已有扫描任务正在执行' }), 400)None(None)Nonedata = request.get_json()directory = data.get('directory', '')if not directory:
(jsonify({
'success': False,
'message': '请指定扫描目录' }), 400)None(None)Noneif not os.path.isdir(directory):
(jsonify({
'success': False,
'message': f'''目录不存在: {directory}''' }), 400)None(None)Noneif start_scan(directory):
jsonify({
'success': True,
'message': '扫描任务已启动' })None(None)None(jsonify({
'success': False,
'message': '已有扫描任务正在执行' }), 400)None(None)None'__pyarmor_exit_7901__(...)''__pyarmor_exit_7901__(...)')()
get_empty_folder_scan_status = (lambda : '__pyarmor_enter_7903__(...)'jsonify({
'success': True,
'data': {
'running': scan_state['running'],
'progress': scan_state['progress'],
'error': scan_state['error'],
'total_scanned': scan_state['total_scanned'],
'result_count': len(scan_state['results']) } })None(None)None'__pyarmor_exit_7904__(...)''__pyarmor_exit_7904__(...)')()
get_empty_folder_results = (lambda : '__pyarmor_enter_7906__(...)'jsonify({
'success': True,
'data': scan_state['results'] })None(None)None'__pyarmor_exit_7907__(...)''__pyarmor_exit_7907__(...)')()
delete_empty_folders_api = (lambda : '__pyarmor_enter_7909__(...)'if scan_state['running']:
(jsonify({
'success': False,
'message': '扫描进行中，请稍后再试' }), 400)None(None)Nonedata = request.get_json()paths = data.get('paths', [])if not paths:
(jsonify({
'success': False,
'message': '未选择要删除的文件夹' }), 400)None(None)Noneresult = delete_folders(paths)# WARNING: Decompyle incomplete
)()
return None
api_bp.route('/empty_folder/delete', methods = [
    'POST'])
return None
'__pyarmor_exit_7898__(...)'
'__pyarmor_exit_7898__(...)'
return api_bp.route('/empty_folder/status', methods = [
    'GET'])
