# File: api_strm_123.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_strm_123.py.1shot.das

'''123 STRM API 路由'''
'__pyarmor_enter_8227__(...)'
from flask import request, jsonify, Response
from  import api_bp
from strm_123 import Strm123Manager
from config_manager import ConfigManager
from logger import logger_strm, logger_302api
from redirect import RedirectHandler
strm_123_manager = Strm123Manager()
config_manager = ConfigManager()
redirect_api = (lambda : '__pyarmor_enter_8230__(...)'has_redirect123 = 'redirect123' in request.argsfile_size_123 = request.args.get('size', '')md5_123 = request.args.get('md5', '')s3_key_flag_123 = request.args.get('s3_key_flag', '')if has_redirect123 and file_size_123 and md5_123 and s3_key_flag_123:
api_123_config = config_manager.get_api_123_config()if not api_123_config.get('enabled', False):
logger_302api.warning(f'''⚠️ 123 API 请求被拒绝: 功能未启用 | size={file_size_123} | md5={md5_123}''')Response('123 API 未启用，请在设置中启用', status = 403)None(None)None_handle_123_api(api_123_config)None(None)Noneshare_code = request.args.get('share_code', '')receive_code = request.args.get('receive_code', '')file_id = request.args.get('id', '')if share_code and receive_code and file_id:
handle_115_share_api = handle_115_share_apiimport api_share_115handle_115_share_api(share_code, receive_code, file_id)None(None)NoneNotFound = NotFoundimport werkzeug.exceptionsraise NotFound()'__pyarmor_exit_8231__(...)''__pyarmor_exit_8231__(...)')()

def _handle_123_api(api_123_config):
    '''处理 123 API 请求'''
    '__pyarmor_enter_8233__(...)'
    file_name = request.args.get('name', '')
    file_size = request.args.get('size', '')
    md5 = request.args.get('md5', '')
    s3_key_flag = request.args.get('s3_key_flag', '')
    if not file_size and md5 or s3_key_flag:
        return Response('参数不完整，需要 size, md5, s3_key_flag', status = 400)
    None(None)
    return None
    file_size = int(file_size)
    config_name = api_123_config.get('use_123_config', '')
    if not config_name:
        return Response('未配置 123 账号', status = 500)
    None(None)
    return None
    config_123 = config_manager.get_123_config_by_name(config_name)
    if not config_123:
        return Response(f'''未找到 123 配置: {config_name}''', status = 500)
    None(None)
    return None
    token = config_123.get('token')
    if not token:
        return Response(f'''123 配置 {config_name} 没有 token''', status = 500)
    None(None)
    return None
    cache_ttl = api_123_config.get('cache_ttl', 10)
    cache_key = f'''123_api_{md5}_{file_size}_{s3_key_flag}'''
    cache_mgr = cache_manager
    import cache_manager
    cached_url = cache_mgr.get_simple(cache_key)
    if cached_url:
        if file_name:
            logger_302api.info(f'''📥 123 API 请求 | size={file_size} | md5={md5} | s3_key_flag={s3_key_flag} | name={file_name}''')
        else:
            logger_302api.info(f'''📥 123 API 请求 | size={file_size} | md5={md5} | s3_key_flag={s3_key_flag}''')
        logger_302api.info(f'''✅ 命中缓存 | 直链: {cached_url}''')
        return RedirectHandler.create_redirect_response(cached_url)
    None(None)
    return None
    if file_name:
        logger_302api.info(f'''📥 123 API 请求 | size={file_size} | md5={md5} | s3_key_flag={s3_key_flag} | name={file_name}''')
    else:
        logger_302api.info(f'''📥 123 API 请求 | size={file_size} | md5={md5} | s3_key_flag={s3_key_flag}''')
    import time
    start_time = time.time()
    P123Client = P123Client
    import p123client
    client = P123Client(token = token)
    if not file_name:
        file_name
    payload = {
        'Etag': md5,
        'FileName': 'unknown.file',
        'S3KeyFlag': s3_key_flag,
        'Size': file_size }
    download_url = client.download_url(payload)
    if not download_url:
        elapsed = time.time() - start_time
        logger_302api.error(f'''❌ 请求失败 | 耗时 {elapsed:.2f}s | 错误: 获取下载链接失败''')
        return Response('获取下载链接失败', status = 500)
    None(None)
    return None
    elapsed = time.time() - start_time
    logger_302api.info(f'''✅ 请求成功 | 耗时 {elapsed:.2f}s | 直链: {download_url}''')
    cache_mgr.set_simple(cache_key, download_url, ttl = cache_ttl)
    return RedirectHandler.create_redirect_response(download_url)
    None(None)
    return None
# WARNING: Decompyle incomplete

get_api_123_config = (lambda : '__pyarmor_enter_8236__(...)'config = config_manager.get_api_123_config()jsonify({
'success': True,
'data': config })None(None)None# WARNING: Decompyle incomplete
)()
update_api_123_config = (lambda : '__pyarmor_enter_8239__(...)'config = request.get_json()success = config_manager.update_api_123_config(config)if success:
jsonify({
'success': True,
'message': '配置更新成功' })None(None)None(jsonify({
'success': False,
'message': '配置更新失败' }), 500)None(None)None# WARNING: Decompyle incomplete
)()
get_strm_123_config = (lambda : '__pyarmor_enter_8242__(...)'config = strm_123_manager.get_config()jsonify({
'success': True,
'data': config })None(None)None# WARNING: Decompyle incomplete
)()
update_strm_123_config = (lambda : 