# File: api_ed2k_strm.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_ed2k_strm.py.1shot.das

'''
ed2k STRM API 路由

提供:
1. ed2k STRM 配置管理 (GET/PUT /api/ed2k_strm/config)
2. ed2k 离线+生成 STRM (POST /api/ed2k_strm/generate)
3. ed2k 直链重定向 (GET /api/ed2k_strm?hash=xxx&size=xxx&name=xxx)
'''
'__pyarmor_enter_7654__(...)'
from flask import request, jsonify, Response
from  import api_bp
from ed2k_strm import ed2k_strm_manager, parse_ed2k
from config_manager import config_manager
from redirect import RedirectHandler
from logger import logger_302api as logger
get_ed2k_strm_config = (lambda : '__pyarmor_enter_7657__(...)'config = ed2k_strm_manager.get_config()jsonify({
'success': True,
'data': config })None(None)None'__pyarmor_exit_7658__(...)''__pyarmor_exit_7658__(...)')()
update_ed2k_strm_config = (lambda : '__pyarmor_enter_7660__(...)'data = request.get_json()if not data:
(jsonify({
'success': False,
'message': '无效的请求数据' }), 400)None(None)Noneif ed2k_strm_manager.save_config(data):
jsonify({
'success': True,
'message': 'ed2k STRM 配置保存成功' })None(None)None(jsonify({
'success': False,
'message': '配置保存失败' }), 500)None(None)None'__pyarmor_exit_7661__(...)''__pyarmor_exit_7661__(...)')()
get_api_ed2k_config = (lambda : '__pyarmor_enter_7663__(...)'config = config_manager.get_api_ed2k_config()jsonify({
'success': True,
'data': config })None(None)None# WARNING: Decompyle incomplete
)()
update_api_ed2k_config = (lambda : '__pyarmor_enter_7666__(...)'config = request.get_json()success = config_manager.update_api_ed2k_config(config)if success:
jsonify({
'success': True,
'message': '配置更新成功' })None(None)None(jsonify({
'success': False,
'message': '配置更新失败' }), 500)None(None)None# WARNING: Decompyle incomplete
)()
ed2k_strm_redirect = (lambda : '__pyarmor_enter_7669__(...)'file_hash = request.args.get('hash', '')file_size = request.args.get('size', '')file_name = request.args.get('name', '')if not file_hash and file_size or file_name:
Response('参数不完整，需要 hash, size, name', status = 400)None(None)Noneapi_ed2k_config = config_manager.get_api_ed2k_config()if not api_ed2k_config.get('enabled', False):
logger.warning(f'''⚠️ ed2k API 请求被拒绝: 功能未启用 | hash={file_hash} | name={file_name}''')Response('ed2k API 未启用，请在设置中启用', status = 403)None(None)Nonecache_ttl = api_ed2k_config.get('cache_ttl', 10)cache_key = f'''ed2k_api_{file_hash}_{file_size}'''cache_mgr = cache_managerimport cache_managercached_url = cache_mgr.get_simple(cache_key)if cached_url:
logger.info(f'''📥 ed2k API 请求 | hash={file_hash} | name={file_name}''')logger.info(f'''✅ 命中缓存 | 直链: {cached_url}''')RedirectHandler.create_redirect_response(cached_url)None(None)Noneimport timestart_time = time.time()logger.info(f'''📥 ed2k API 请求 | hash={file_hash} | name={file_name}''')result = ed2k_strm_manager.get_download_url(filehash = file_hash, filesize = file_size, filename = file_name)if result.get('success') and result.get('download_url'):
download_url = result['download_url']elapsed = time.time() - start_timelogger.info(f'''✅ 请求成功 | 耗时 {elapsed:.2f}s | 直链: {download_url}''')cache_mgr.set_simple(cache_key, download_url, ttl = cache_ttl)RedirectHandler.create_redirect_response(download_url)None(None)Noneerror = result.get('error', '获取直链失败')elapsed = time.time() - start_timelogger.error(f'''❌ 请求失败 | 耗时 {elapsed:.2f}s | 错误: {error}''')Response(f'''获取直链失败: {error}''', status = 500)None(None)None'__pyarmor_exit_7670__(...)''__pyarmor_exit_7670__(...)')()
return None
api_bp.route('/ed2k_strm', methods = [
    'GET',
    'HEAD'])
return None
'__pyarmor_exit_7655__(...)'
'__pyarmor_exit_7655__(...)'
return api_bp.route('/api_ed2k/config', methods = [
    'GET'])
