# File: api_bulk_transfer.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_bulk_transfer.py.1shot.das

'''115大包筛选入库 API'''
'__pyarmor_enter_8758__(...)'
from flask import request, jsonify
from  import api_bp
from config_manager import config_manager
from logger import Logger
logger = Logger('log.log')
get_bulk_transfer_config = (lambda : '__pyarmor_enter_8761__(...)'config = config_manager.get_bulk_transfer_config()jsonify({
'success': True,
'data': config })None(None)None# WARNING: Decompyle incomplete
)()
update_bulk_transfer_config = (lambda : '__pyarmor_enter_8764__(...)'if not request.get_json(silent = True):
request.get_json(silent = True)data = { }if config_manager.update_bulk_transfer_config(data):
jsonify({
'success': True,
'message': '配置已保存' })None(None)Nonejsonify({
'success': False,
'message': '保存失败' })None(None)None# WARNING: Decompyle incomplete
)()
start_scan = (lambda : '__pyarmor_enter_8767__(...)'if not request.get_json(silent = True):
request.get_json(silent = True)data = { }share_urls = data.get('share_urls', [])if not share_urls:
jsonify({
'success': False,
'message': '请输入至少一个分享链接' })None(None)Nonestart_scan_and_recognize = start_scan_and_recognizeimport bulk_transfer(ok, msg) = start_scan_and_recognize(share_urls)jsonify({
'success': ok,
'message': msg })None(None)None# WARNING: Decompyle incomplete
)()
get_bulk_transfer_status = (lambda : '__pyarmor_enter_8770__(...)'log_since = request.args.get('log_since', 0, type = int)get_task_status = get_task_statusimport bulk_transferstatus = get_task_status(log_since = log_since)jsonify({
'success': True,
'data': status })None(None)None# WARNING: Decompyle incomplete
)()
get_bulk_transfer_result = (lambda : '__pyarmor_enter_8773__(...)'get_task_result = get_task_resultimport bulk_transferresult = get_task_result()jsonify({
'success': True,
'data': result })None(None)None# WARNING: Decompyle incomplete
)()
start_transfer = (lambda : '__pyarmor_enter_8776__(...)'if not request.get_json(silent = True):
request.get_json(silent = True)data = { }selected_items = data.get('selected_items')do_transfer = start_transferimport bulk_transfer(ok, msg) = do_transfer(selected_items)jsonify({
'success': ok,
'message': msg })None(None)None# WARNING: Decompyle incomplete
)()
get_bulk_transfer_transfer_result = (lambda : '__pyarmor_enter_8779__(...)'get_result = get_transfer_resultimport bulk_transferresult = get_result()jsonify({
'success': True,
'data': result })None(None)None# WARNING: Decompyle incomplete
)()
clear_bulk_transfer_task = (lambda : '__pyarmor_enter_8782__(...)'do_clear = clear_taskimport bulk_transferdo_clear()jsonify({
'success': True,
'message': '已清空' })None(None)None# WARNING: Decompyle incomplete
)()
manual_recognize = (lambda : '__pyarmor_enter_8785__(...)'import logging_logger = logging.getLogger(__name__)if not request.get_json(silent = True):
request.get_json(silent = True)data = { }fid = data.get('fid', '')tmdb_id = data.get('tmdb_id', '')media_type = data.get('media_type', 'movie')title = data.get('title', '')year = data.get('year', '')poster_path = data.get('poster_path', '')season = data.get('season')episode = data.get('episode')_logger.info(f'''[手动识别] fid={fid}, tmdb_id={tmdb_id}, type={media_type}, title={title}, year={year}, S={season} E={episode}''')if not fid and tmdb_id or title:
jsonify({
'success': False,
'message': '缺少必要参数 (fid, tmdb_id, title)' })None(None)Nonemanual_recognize_item = manual_recognize_itemimport bulk_transfer(ok, msg) = manual_recognize_item(fid = str(fid), tmdb_id = str(tmdb_id), media_type = media_type, title = title, year = str(year), poster_path = poster_path, season = season, episode = episode)_logger.info(f'''[手动识别] 结果: ok={ok}, msg={msg}''')jsonify({
'success': ok,
'message': msg })None(None)None# WARNING: Decompyle incomplete
)()
re_recognize = (lambda : '__pyarmor_enter_8788__(...)'import logging_logger = logging.getLogger(__name__)if not request.get_json(silent = True):
request.get_json(silent = True)data = { }source_tmdb_id = data.get('source_tmdb_id', '')source_type = data.get('source_type', '')tmdb_id = data.get('tmdb_id', '')media_type = data.get('media_type', 'movie')title = data.get('title', '')year = data.get('year', '')poster_path = data.get('poster_path', '')season = data.get('season')episode = data.get('episode')if not source_tmdb_id and source_type and tmdb_id or title:
jsonify({
'success': False,
'message': '缺少必要参数' })None(None)Nonere_recognize_group = re_recognize_groupimport bulk_transfer(ok, msg) = re_recognize_group(source_tmdb_id = str(source_tmdb_id), source_type = source_type, tmdb_id = str(tmdb_id), media_type = media_type, title = title, year = str(year), poster_path = poster_path, season = season, episode = episode)jsonify({
'success': ok,
'message': msg })None(None)None# WARNING: Decompyle incomplete
)()
check_library = (lambda : '__pyarmor_enter_8791__(...)'do_check = start_library_checkimport bulk_transfer(ok, msg) = do_check()jsonify({
'success': ok,
'message': msg })None(None)None# WARNING: Decompyle incomplete
)()
return None
api_bp.route('/bulk_transfer/check_library', methods = [
    'POST'])
return None
'__pyarmor_exit_8759__(...)'
'__pyarmor_exit_8759__(...)'
return api_bp.route('/bulk_transfer/manual_recognize', methods = [
    'POST'])
