# File: api_file_transfer.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: api_file_transfer.py.1shot.das

'''文件整理 & 整理配置 & 二级分类 API'''
'__pyarmor_enter_8005__(...)'
from flask import request, jsonify
from  import api_bp
from logger import logger_organize as logger
from config_manager import config_manager
from category_manager import category_manager
from file_transfer_service import file_transfer_service
from transfer_naming import get_media_probe_field_catalog, get_rename_field_catalog, get_organize_notify_field_catalog, inspect_transfer_basic_config
get_file_transfer_configs = (lambda : '__pyarmor_enter_8008__(...)'configs = config_manager.get_file_transfer_configs()jsonify({
'success': True,
'data': configs,
'defaults': config_manager.get_default_file_transfer_config() })None(None)None# WARNING: Decompyle incomplete
)()
add_file_transfer_config = (lambda : '__pyarmor_enter_8011__(...)'data = request.get_json()if not data:
(jsonify({
'success': False,
'message': '无效的请求数据' }), 400)None(None)Noneresult = config_manager.add_file_transfer_config(data)if result:
jsonify({
'success': True,
'data': result,
'message': '配置已添加' })None(None)None(jsonify({
'success': False,
'message': '添加失败' }), 500)None(None)None'__pyarmor_exit_8012__(...)''__pyarmor_exit_8012__(...)')()
update_file_transfer_config = (lambda config_id: '__pyarmor_enter_8014__(...)'data = request.get_json()if not data:
(jsonify({
'success': False,
'message': '无效的请求数据' }), 400)None(None)Noneresult = config_manager.update_file_transfer_config(config_id, data)if result:
jsonify({
'success': True,
'data': result,
'message': '配置已更新' })None(None)None(jsonify({
'success': False,
'message': '更新失败' }), 500)None(None)None'__pyarmor_exit_8015__(...)''__pyarmor_exit_8015__(...)')()
delete_file_transfer_config = (lambda config_id: '__pyarmor_enter_8017__(...)'if config_manager.delete_file_transfer_config(config_id):
jsonify({
'success': True,
'message': '配置已删除' })None(None)None(jsonify({
'success': False,
'message': '删除失败' }), 500)None(None)None'__pyarmor_exit_8018__(...)''__pyarmor_exit_8018__(...)')()
get_file_transfer_status = (lambda : '__pyarmor_enter_8020__(...)'jsonify({
'success': True,
'data': file_transfer_service.get_status() })None(None)None# WARNING: Decompyle incomplete
)()
preview_file_transfer = (lambda : '__pyarmor_enter_8023__(...)'if not request.get_json():
request.get_json()data = { }if not data.get('path'):
data.get('path')path = str('').strip()config_id = data.get('config_id')if not data.get('options'):
data.get('options')manual_options = { }if not path:
(jsonify({
'success': False,
'message': '缺少源文件路径' }), 400)None(None)Noneresult = file_transfer_service.preview_transfer(path = path, config_id = config_id, manual_options = manual_options)jsonify({
'success': True,
'data': result })None(None)None# WARNING: Decompyle incomplete
)()
organize_file_transfer = (lambda : '__pyarmor_enter_8026__(...)'if not request.get_json():
request.get_json()data = { }if not data.get('path'):
data.get('path')path = str('').strip()config_id = data.get('config_id')if not data.get('options'):
data.get('options')manual_options = { }if not path:
(jsonify({
'success': False,
'message': '缺少源文件路径' }), 400)None(None)Noneresult = file_transfer_service.organize_file(path = path, config_id = config_id, manual_options = manual_options)if not result:
resultif not { }.get('status'):
{ }.get('status')status = str('').strip().lower()is_failed = status == 'failed'if not result.get('message'):
result.get('message')(jsonify({
'success': not is_failed,
'data': result,
'message': '文件整理已执行' if not is_failed else '文件整理失败' }), 400 if is_failed else 200)None(None)None# WARNING: Decompyle incomplete
)()
get_transfer_basic_config = (lambda : '__pyarmor_enter_8029__(...)'data = config_manager.get_transfer_basic_config()defaults = config_manager.get_default_transfer_basic_config()jsonify({
'success': True,
'data': data,
'defaults': defaults,
'field_catalog': get_rename_field_catalog(),
'media_probe_field_catalog': get_media_probe_field_catalog(),
'notify_field_catalog': get_organize_notify_field_catalog(),
'inspection': inspect_transfer_basic_config(data),
'default_inspection': inspect_transfer_basic_config(defaults) })None(None)None'__pyarmor_exit_8030__(...)''__pyarmor_exit_8030__(...)')()
inspect_transfer_basic_config_api = (lambda : '__pyarmor_enter_8032__(...)'if not request.get_json():
request.get_json()data = { }jsonify({
'success': True,
'data': data,
'field_catalog': get_rename_field_catalog(),
'media_probe_field_catalog': get_media_probe_field_catalog(),
'notify_field_catalog': get_organize_notify_field_catalog(),
'inspection': inspect_transfer_basic_config(data) })None(None)None'__pyarmor_exit_8033__(...)''__pyarmor_exit_8033__(...)')()
update_transfer_basic_config = (lambda : '__pyarmor_enter_8035__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
clear_tmdb_recognition_cache = (lambda : '__pyarmor_enter_8038__(...)'TmdbRecognitionCache = TmdbRecognitionCacheimport recognize_cachecount = TmdbRecognitionCache().clear()logger.info(f'''已清空 TMDB 识别缓存: count={count}''')jsonify({
'success': True,
'count': count,
'message': f'''已清空 {count} 条 TMDB 识别缓存''' })None(None)None'__pyarmor_exit_8039__(...)''__pyarmor_exit_8039__(...)')()
clear_openai_recognition_cache = (lambda : '__pyarmor_enter_8041__(...)'GptRecognitionCache = GptRecognitionCacheimport recognize_cachecount = GptRecognitionCache().clear()logger.info(f'''已清空 OpenAI 辅助识别缓存: count={count}''')jsonify({
'success': True,
'count': count,
'message': f'''已清空 {count} 条 OpenAI 辅助识别缓存''' })None(None)None'__pyarmor_exit_8042__(...)''__pyarmor_exit_8042__(...)')()
get_custom_identifiers = (lambda : '__pyarmor_enter_8044__(...)'words = config_manager.get_custom_identifiers()jsonify({
'success': True,
'data': words })None(None)None'__pyarmor_exit_8045__(...)''__pyarmor_exit_8045__(...)')()
set_custom_identifiers = (lambda : '__pyarmor_enter_8047__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
get_custom_captures = (lambda : '__pyarmor_enter_8050__(...)'words = config_manager.get_custom_captures()jsonify({
'success': True,
'data': words })None(None)None'__pyarmor_exit_8051__(...)''__pyarmor_exit_8051__(...)')()
set_custom_captures = (lambda : '__pyarmor_enter_8053__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
get_custom_release_groups = (lambda : '__pyarmor_enter_8056__(...)'groups = config_manager.get_custom_release_groups()jsonify({
'success': True,
'data': groups })None(None)None'__pyarmor_exit_8057__(...)''__pyarmor_exit_8057__(...)')()
set_custom_release_groups = (lambda : '__pyarmor_enter_8059__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
get_post_render_words = (lambda : '__pyarmor_enter_8062__(...)'words = config_manager.get_post_render_words()jsonify({
'success': True,
'data': words })None(None)None'__pyarmor_exit_8063__(...)''__pyarmor_exit_8063__(...)')()
set_post_render_words = (lambda : '__pyarmor_enter_8065__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
get_category_config = (lambda : '__pyarmor_enter_8068__(...)'data = category_manager.get_categorys()jsonify({
'success': True,
'data': data })None(None)None# WARNING: Decompyle incomplete
)()
update_category_config = (lambda : '__pyarmor_enter_8071__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
get_category_names = (lambda : '__pyarmor_enter_8074__(...)'names = category_manager.get_all_category_names()jsonify({
'success': True,
'data': names })None(None)None# WARNING: Decompyle incomplete
)()
get_category_raw = (lambda : '__pyarmor_enter_8077__(...)'content = category_manager.get_raw_content()jsonify({
'success': True,
'data': content })None(None)None'__pyarmor_exit_8078__(...)''__pyarmor_exit_8078__(...)')()
get_category_default_raw = (lambda : '__pyarmor_enter_8080__(...)'get_default_category_raw = get_default_category_rawimport config_managercontent = get_default_category_raw()jsonify({
'success': True,
'data': content })None(None)None'__pyarmor_exit_8081__(...)''__pyarmor_exit_8081__(...)')()
save_category_raw = (lambda : '__pyarmor_enter_8083__(...)'data = request.get_json()# WARNING: Decompyle incomplete
)()
return None
api_bp.route('/transfer_config/category/raw', methods = [
    'POST'])
return None
'__pyarmor_exit_8006__(...)'
'__pyarmor_exit_8006__(...)'
return api_bp.route('/transfer_config/category/raw', methods = [
    'GET'])
