# File: async_scanner.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: async_scanner.py.1shot.das

'''异步递归扫描器模块 - 纯异步高并发扫描分享链接，无需cookie'''
'__pyarmor_enter_1885__(...)'
import asyncio
import aiohttp
import random
import time
from typing import Dict, List
from logger import Logger
logger_strm = Logger('strm.log')

def _random_ip():
    '''生成随机公网 IP'''
    '__pyarmor_enter_1888__(...)'
    ip = f'''{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(1, 254)}'''
    first = int(ip.split('.')[0])
    if first in (10, 127, 0) and ip.startswith('192.168.') or ip.startswith('172.16.'):
        continue
    return ip
    None(None)
    return None
    '__pyarmor_exit_1889__(...)'
    '__pyarmor_exit_1889__(...)'


def _random_ua():
    '''生成随机 iOS UA'''
    '__pyarmor_enter_1891__(...)'
    return f'''Mozilla/5.0 (iPhone; CPU iPhone OS 17_{random.randint(0, 5)}_{random.randint(0, 3)} like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 115Browser/{random.randint(20, 30)}.{random.randint(0, 9)}.0'''
    None(None)
    return None
    '__pyarmor_exit_1892__(...)'
    '__pyarmor_exit_1892__(...)'


class AsyncRecursiveScanner:
    '''纯异步递归扫描器 - 持续工作队列，无延迟，aiohttp，无需cookie'''
    '__pyarmor_enter_1894__(...)'
    CONCURRENCY = 100
    API_LIMIT = 7000
    API_ENDPOINT = 'https://webapi.115.com/share/snap'
    
    def __init__(self, share_code, receive_code, video_exts, metadata_exts, quiet, progress_callback):
        '__pyarmor_enter_1897__(...)'
        self.share_code = share_code
        self.receive_code = receive_code
        if not video_exts:
            video_exts
        self.video_exts = set()
        if not metadata_exts:
            metadata_exts
        self.metadata_exts = set()
        self.quiet = quiet
        self.progress_callback = progress_callback
        self.total_files = 0
        self.total_dirs = 0
        self.all_files = []
        self.lock = asyncio.Lock()
        self.api_error = None
        self.queue = asyncio.LifoQueue()
        self.pending_count = 0
        self.done_event = asyncio.Event()
        self._last_log_time = 0
        return None
        return None
        '__pyarmor_exit_1898__(...)'
        '__pyarmor_exit_1898__(...)'

    
    def _get_headers(self):
        '''每次请求随机 IP 和 UA'''
        '__pyarmor_enter_1900__(...)'
        ip = _random_ip()
        return {
            'User-Agent': _random_ua(),
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Referer': 'https://115.com/',
            'Origin': 'https://115.com',
            'X-Forwarded-For': ip,
            'X-Real-IP': ip,
            'Client-IP': ip }
        None(None)
        return None
        '__pyarmor_exit_1901__(...)'
        '__pyarmor_exit_1901__(...)'

    
    async def _api_request(self, session, cid, offset):
        pass
    # WARNING: Decompyle incomplete

    
    def _classify_file(self, filename):
        '__pyarmor_enter_1906__(...)'
        ext = '.' + filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
        if ext in self.video_exts:
            return 'video'
        return 'video'
        if ext in self.metadata_exts:
            return 'metadata'
        return 'metadata'
        return 'other'
        return 'other'
        '__pyarmor_exit_1907__(...)'
        '__pyarmor_exit_1907__(...)'

    
    async def _process_folder(self, session, cid, path, name):
        '''处理单个文件夹'''
        pass
    # WARNING: Decompyle incomplete

    
    async def _worker(self, session):
        '''持续工作的 worker，从队列取任务'''
        pass
    # WARNING: Decompyle incomplete

    
    async def scan(self):
        pass
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_1895__(...)'
    '__pyarmor_exit_1895__(...)'

return None
return None
'__pyarmor_exit_1886__(...)'
'__pyarmor_exit_1886__(...)'
