# File: bulk_transfer.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: bulk_transfer.py.1shot.das

'''115大包筛选入库 - 核心逻辑模块

扫描分享链接 → 识别文件 → 分类展示 → 转存/分享STRM
'''
'__pyarmor_enter_7159__(...)'
import os
import copy
import concurrent.futures as concurrent
import random
import re
import requests
import string
import threading
import time
from typing import Any, Dict, List, Optional, Tuple
from logger import Logger, use_log_file, use_log_sink
from config_manager import config_manager
from transfer_115 import Transfer115
from ua import UserAgentUtils
logger = Logger('log.log')
VIDEO_EXTS = {
    '.tp',
    '.ts',
    '.avi',
    '.f4v',
    '.flv',
    '.iso',
    '.m4v',
    '.mkv',
    '.mov',
    '.mp4',
    '.wmv',
    '.m2ts',
    '.rmvb'}
_task_lock = threading.Lock()
_suppress_logs = False
_task_state = {
    'running': False,
    'phase': '',
    'progress': '',
    'error': None,
    'result': None,
    'transfer_result': None,
    'logs': [],
    'steps': [],
    'summary': None }

def _get_state():
    '__pyarmor_enter_7162__(...)'
# WARNING: Decompyle incomplete


def _set_state(**kwargs):
    '__pyarmor_enter_7165__(...)'
# WARNING: Decompyle incomplete


def get_task_status(log_since):
    '''获取当前任务状态（含增量日志）'''
    '__pyarmor_enter_7168__(...)'
# WARNING: Decompyle incomplete


def get_task_result():
    '''获取扫描识别结果'''
    '__pyarmor_enter_7171__(...)'
# WARNING: Decompyle incomplete


def get_transfer_result():
    '''获取转存结果'''
    '__pyarmor_enter_7174__(...)'
# WARNING: Decompyle incomplete


def manual_recognize_item(fid, tmdb_id, media_type, title, year, poster_path, season, episode):
    '''手动识别：将未识别项通过 TMDB 信息归类到电影或剧集列表中'''
    '__pyarmor_enter_7177__(...)'
# WARNING: Decompyle incomplete


def re_recognize_group(source_tmdb_id, source_type, tmdb_id, media_type, title, year, poster_path, season, episode):
    '''重新识别：将已识别的电影/电视剧整组重新归类到新的目标'''
    '__pyarmor_enter_7180__(...)'
# WARNING: Decompyle incomplete


def clear_task():
    '''清空任务状态和结果'''
    '__pyarmor_enter_7183__(...)'
# WARNING: Decompyle incomplete


def _add_log(msg, level):
    '''添加日志到实时列表并写入系统日志'''
    '__pyarmor_enter_7186__(...)'
    _add_log_visible(msg = msg, level = level, visible = True)
    return None
    return None
    '__pyarmor_exit_7187__(...)'
    '__pyarmor_exit_7187__(...)'


def _add_log_visible(msg, level, visible):
    '''添加日志；受 _suppress_logs 全局开关控制：
    - _suppress_logs=True（识别日志关闭）: 前端面板和 log.log 均不写入，仅 error 强制写入 log.log
    - _suppress_logs=False（识别日志开启）: visible=True 写入前端面板和 log.log，visible=False 仅 error 写入 log.log
    '''
    '__pyarmor_enter_7189__(...)'
    import time as _t
    ts = _t.strftime('%H:%M:%S')
    if _suppress_logs:
        if level == 'error':
            logger.error(f'''[大包筛选] {msg}''')
        return None
    return None
# WARNING: Decompyle incomplete


def _normalize_logger_level(level):
    '''将 Logger 内部等级符号映射成前端实时日志使用的等级'''
    '__pyarmor_enter_7192__(...)'
    if '❌' in level:
        return 'error'
    return 'error'
    if '⚠' in level:
        return 'warning'
    return 'warning'
    return 'info'
    return 'info'
    '__pyarmor_exit_7193__(...)'
    '__pyarmor_exit_7193__(...)'


def _forward_related_logger(log_name, level, message, timestamp):
    '''把当前任务线程内其他模块输出的相关日志同步到前端实时日志。

    说明：
    - 通过 _add_log/_add_log_visible 输出的日志已经手动写入过前端列表，这里跳过，避免重复。
    - 主要用于补齐扫描器等底层模块直接写 logger 时，前端日志面板看不到的问题。
    - _suppress_logs=True 时不转发，避免日志面板显示底层模块日志。
    '''
    '__pyarmor_enter_7195__(...)'
    if _suppress_logs:
        return None
    return None
    if message or message.startswith('[大包筛选]'):
        return None
    return None
    if log_name != 'log.log':
        return None
    return None
# WARNING: Decompyle incomplete


def _init_steps(step_names):
    '''初始化步骤列表'''
    '__pyarmor_enter_7198__(...)'
# WARNING: Decompyle incomplete


def _update_step(index, **kwargs):
    '''更新指定步骤的字段'''
    '__pyarmor_enter_7201__(...)'
# WARNING: Decompyle incomplete


def _ensure_step(name):
    '''确保步骤存在并返回步骤索引'''
    '__pyarmor_enter_7204__(...)'
# WARNING: Decompyle incomplete


def _build_empty_library_result(result):
    '''构建默认的 Emby 入库检测结果'''
    '__pyarmor_enter_7207__(...)'
    if not result:
        result
    result = { }
    if not result.get('movies', []):
        result.get('movies', [])
    movies = []
    if not result.get('tvshows', []):
        result.get('tvshows', [])
    tvshows = []
    total_items = len(movies) + len(tvshows)
    return {
        'checked': False,
        'movie_in_library': [],
        'tv_in_library': { },
        'movie_total': len(movies),
        'tv_total': len(tvshows),
        'total_items': total_items,
        'completed_items': 0,
        'movie_in_library_count': 0,
        'movie_not_in_library_count': len(movies),
        'tv_complete_count': 0,
        'tv_missing_count': len(tvshows) }
    None(None)
    return None
    '__pyarmor_exit_7208__(...)'
    '__pyarmor_exit_7208__(...)'


def _build_summary(result):
    '''根据当前识别/检测结果构建页面汇总信息'''
    '__pyarmor_enter_7210__(...)'
    if not result:
        result
    result = { }
    if not result.get('stats'):
        result.get('stats')
    stats = { }
    if not result.get('movies', []):
        result.get('movies', [])
    if not result.get('tvshows', []):
        result.get('tvshows', [])
    summary = {
        'total_files': stats.get('total_files', 0),
        'recognized': stats.get('recognized', 0),
        'unrecognized': stats.get('unrecognized', 0),
        'movies': stats.get('movies', len([])),
        'tvshows': stats.get('tvshows', len([])),
        'library_checked': False,
        'library_total_items': 0,
        'library_completed_items': 0,
        'movie_in_library': 0,
        'movie_not_in_library': 0,
        'tv_complete_in_library': 0,
        'tv_missing_or_not_in_library': 0 }
    if not result.get('library'):
        result.get('library')
    library = { }
    if library.get('checked'):
        summary.update({
            'library_checked': True,
            'library_total_items': library.get('total_items', 0),
            'library_completed_items': library.get('completed_items', 0),
            'movie_in_library': library.get('movie_in_library_count', 0),
            'movie_not_in_library': library.get('movie_not_in_library_count', 0),
            'tv_complete_in_library': library.get('tv_complete_count', 0),
            'tv_missing_or_not_in_library': library.get('tv_missing_count', 0) })
    return summary
    None(None)
    return None
    '__pyarmor_exit_7211__(...)'
    '__pyarmor_exit_7211__(...)'


def _resolve_emby_connection(emby_config_id):
    '''解析 Emby 连接信息，支持 Emby 助手和秒传播放配置'''
    '__pyarmor_enter_7213__(...)'
    if not emby_config_id:
        raise ValueError('未配置 Emby 账号')
    emby_cfg = config_manager.get_emby_config(emby_config_id)
    if not emby_cfg:
        emby_cfg = config_manager.get_fast_transfer_config(emby_config_id)
    if not emby_cfg:
        raise ValueError('Emby 配置不存在')
    if not emby_cfg.get('server'):
        emby_cfg.get('server')
    server = ''.rstrip('/')
    if not emby_cfg.get('api_key'):
        emby_cfg.get('api_key')
    api_key = ''
    if not server or api_key:
        raise ValueError('Emby 服务器或 API Key 未配置')
    return (server, api_key)
    None(None)
    return None
    '__pyarmor_exit_7214__(...)'
    '__pyarmor_exit_7214__(...)'


def _extract_requested_episodes(show):
    '''提取当前剧集需要检测的季/集范围'''
    '__pyarmor_enter_7216__(...)'
    requested = { }
    if not show.get('seasons_list', []):
        show.get('seasons_list', [])
    for season in []:
        if not season.get('season'):
            season.get('season')
        season_num = int(0)
        if season_num <= 0:
            continue
        episodes = []
        if not season.get('episodes', []):
            season.get('episodes', [])
        for episode in []:
            if not episode.get('episode'):
                episode.get('episode')
            ep_num = int(0)
            if not ep_num > 0:
                continue
            episodes.append(ep_num)
        requested[season_num] = sorted(set(episodes))
    return requested
    None(None)
    return None
# WARNING: Decompyle incomplete


def _check_movie_in_library(server, api_key, movie):
    '''仅按电影 TMDB ID 精确匹配 Emby，不做标题或年份回退'''
    '__pyarmor_enter_7219__(...)'
    if not movie.get('tmdb_id', ''):
        movie.get('tmdb_id', '')
    tmdb_id = str('')
    if not movie.get('title', ''):
        movie.get('title', '')
        if not tmdb_id:
            tmdb_id
    title = '未知电影'
    if not tmdb_id:
        return {
            'kind': 'movie',
            'tmdb_id': '',
            'title': title,
            'in_library': False }
    None(None)
    return None
    resp = requests.get(f'''{server}/emby/Items''', params = {
        'api_key': api_key,
        'AnyProviderIdEquals': f'''Tmdb.{tmdb_id}''',
        'IncludeItemTypes': 'Movie',
        'Recursive': 'true',
        'Fields': 'ProviderIds',
        'Limit': 1 }, timeout = 10)
    resp.raise_for_status()
    items = resp.json().get('Items', [])
    return {
        'kind': 'movie',
        'tmdb_id': tmdb_id,
        'title': title,
        'in_library': bool(items) }
    None(None)
    return None
    '__pyarmor_exit_7220__(...)'
    '__pyarmor_exit_7220__(...)'


def _check_tv_in_library(server, api_key, show):
    '''仅按剧集 TMDB ID 精确匹配 Emby，不做标题或年份回退'''
    '__pyarmor_enter_7222__(...)'
    if not show.get('tmdb_id', ''):
        show.get('tmdb_id', '')
    tmdb_id = str('')
    if not show.get('title', ''):
        show.get('title', '')
        if not tmdb_id:
            tmdb_id
    title = '未知剧集'
    if not tmdb_id:
        return {
            'kind': 'tv',
            'tmdb_id': '',
            'title': title,
            'season_episodes': { },
            'complete': False }
    None(None)
    return None
    resp = requests.get(f'''{server}/emby/Items''', params = {
        'api_key': api_key,
        'AnyProviderIdEquals': f'''Tmdb.{tmdb_id}''',
        'IncludeItemTypes': 'Series',
        'Recursive': 'true',
        'Fields': 'ProviderIds',
        'Limit': 1 }, timeout = 10)
    resp.raise_for_status()
    items = resp.json().get('Items', [])
    if not items:
        return {
            'kind': 'tv',
            'tmdb_id': tmdb_id,
            'title': title,
            'season_episodes': { },
            'complete': False }
    None(None)
    return None
    series_id = items[0].get('Id', '')
    if not series_id:
        return {
            'kind': 'tv',
            'tmdb_id': tmdb_id,
            'title': title,
            'season_episodes': { },
            'complete': False }
    None(None)
    return None
    ep_resp = requests.get(f'''{server}/emby/Shows/{series_id}/Episodes''', params = {
        'api_key': api_key,
        'Fields': 'ParentIndexNumber' }, timeout = 15)
    ep_resp.raise_for_status()
    ep_items = ep_resp.json().get('Items', [])
    season_episodes = { }
# WARNING: Decompyle incomplete


def _run_library_check(result, emby_config_id, step_index):
    '''执行 Emby 入库检测；只按识别结果中的媒体类型和 TMDB ID 匹配'''
    '__pyarmor_enter_7225__(...)'
    (server, api_key) = _resolve_emby_connection(emby_config_id)
    if not result.get('movies', []):
        result.get('movies', [])
    movies = []
    if not result.get('tvshows', []):
        result.get('tvshows', [])
    tvshows = []
    total_items = len(movies) + len(tvshows)
    library_data = _build_empty_library_result(result)
# WARNING: Decompyle incomplete


def _api_delay():
    '''执行 API 调用随机延迟'''
    '__pyarmor_enter_7228__(...)'
    config = config_manager.get_bulk_transfer_config()
    if config.get('api_delay_enabled', True):
        delay_min = float(config.get('api_delay_min', 0.5))
        delay_max = float(config.get('api_delay_max', 1.2))
        if delay_max < delay_min:
            delay_max = delay_min + 0.1
        time.sleep(random.uniform(delay_min, delay_max))
    return None
    return None
    '__pyarmor_exit_7229__(...)'
    '__pyarmor_exit_7229__(...)'


def _build_media_folder_name(name, year, tmdb_id, media_type):
    '''构建媒体文件夹名称: 名字 (年份) {tmdbid-ID}'''
    '__pyarmor_enter_7231__(...)'
    if not name or tmdb_id:
        return ''
    return ''
    name = re.sub('[\\\\/:*?"<>|]', '', name).strip()
    parts = [
        name]
    if year:
        parts.append(f'''({year})''')
    parts.append(f'''{{tmdbid-{tmdb_id}}}''')
    return ' '.join(parts)
    None(None)
    return None
    '__pyarmor_exit_7232__(...)'
    '__pyarmor_exit_7232__(...)'


def _build_full_target_path(transfer_folder_name, media_folder, season_folder):
    '''构建从网盘根目录开始的完整目标路径'''
    '__pyarmor_enter_7234__(...)'
    if not transfer_folder_name:
        transfer_folder_name
    parts = [
        '根目录']
    if media_folder:
        parts.append(media_folder)
    if season_folder:
        parts.append(season_folder)
    return '/' + '/'.join(parts)
    None(None)
    return None
    '__pyarmor_exit_7235__(...)'
    '__pyarmor_exit_7235__(...)'


def _scan_share_link(cookie, share_url, parse_mode):
    '''扫描单个分享链接，返回文件列表
    parse_mode: 0=最快, 1=大包模式, 3=葵花宝典
    '''
    '__pyarmor_enter_7237__(...)'
    (share_code, receive_code) = Transfer115.parse_share_link(share_url)
    if not share_code or receive_code:
        _add_log(f'''无法解析分享链接: {share_url}''', 'error')
        return []
    None(None)
    return None
    raw_files = []
    scan_stats = {
        'files': 0,
        'dirs': 0 }
    
    def _scan_progress(files_count, dirs_count):
        '__pyarmor_enter_7240__(...)'
        scan_stats['files'] = files_count
        scan_stats['dirs'] = dirs_count
        _add_log(f'''扫描中... 文件: {files_count}, 文件夹: {dirs_count}''')
        _update_step(0, message = f'''扫描中: {files_count} 个文件, {dirs_count} 个文件夹''')
        return None
        return None
        '__pyarmor_exit_7241__(...)'
        '__pyarmor_exit_7241__(...)'

# WARNING: Decompyle incomplete


def _extract_media_fields(result):
    '''从 recognize_media 返回结果中提取关键字段
    recognize_media 返回: {meta_info: {...}, media_info: {tmdb_id, type, title, year, poster_path, season, ...}, ...}
    '''
    '__pyarmor_enter_7243__(...)'
    if not result:
        return None
    return None
    if not result.get('media_info'):
        result.get('media_info')
    mi = { }
    if not result.get('meta_info'):
        result.get('meta_info')
    meta = { }
    tmdb_id = mi.get('tmdb_id')
    if not tmdb_id:
        return None
    return None
    media_type = mi.get('type', 'movie')
    if media_type in ('电视剧', 'tv'):
        media_type = 'tv'
    else:
        media_type = 'movie'
    if not mi.get('title', ''):
        mi.get('title', '')
    if not mi.get('season'):
        mi.get('season')
    return {
        'tmdb_id': str(tmdb_id),
        'type': media_type,
        'title': meta.get('name', ''),
        'year': mi.get('year', ''),
        'poster_path': mi.get('poster_path', ''),
        'season': meta.get('begin_season'),
        'episode': meta.get('begin_episode') }
    None(None)
    return None
    '__pyarmor_exit_7244__(...)'
    '__pyarmor_exit_7244__(...)'


def _recognize_single_file(filename, show_detail_logs):
    '''识别单个文件名，返回提取后的媒体字段或 None'''
    '__pyarmor_enter_7246__(...)'
    recognize_media = recognize_media
    import media_info_builder
    config = config_manager.get_transfer_basic_config()
    result = recognize_media(title = filename, config = config)
    extracted = _extract_media_fields(result)
    if extracted:
        return extracted
    None(None)
    return None
    config = config_manager.get_transfer_basic_config()
    result = recognize_media(title = filename, force_gpt = True, config = config)
    extracted = _extract_media_fields(result)
    if extracted:
        return extracted
    None(None)
    return None
    return None
    return None
# WARNING: Decompyle incomplete


def start_scan_and_recognize(share_urls):
    '''启动扫描+识别后台任务'''
    '__pyarmor_enter_7249__(...)'
    state = _get_state()
    if state['running']:
        return (False, '已有任务在运行中')
    return (False, '已有任务在运行中')
# WARNING: Decompyle incomplete


def _scan_and_recognize_worker(share_urls):
    '''扫描+识别工作线程'''
    '__pyarmor_enter_7252__(...)'
# WARNING: Decompyle incomplete


def start_library_check():
    '''基于当前识别结果重新启动 Emby 入库检测任务'''
    '__pyarmor_enter_7258__(...)'
    state = _get_state()
    if state['running']:
        return (False, '已有任务在运行中')
    return (False, '已有任务在运行中')
    result = get_task_result()
    if not result:
        return (False, '没有识别结果，请先扫描')
    return (False, '没有识别结果，请先扫描')
    config = config_manager.get_bulk_transfer_config()
    emby_config_id = config.get('emby_config_id', '')
    if not emby_config_id:
        return (False, '未配置 Emby 账号')
    return (False, '未配置 Emby 账号')
    result['library'] = _build_empty_library_result(result)
    summary = _build_summary(result)
    step_index = _ensure_step('Emby 入库检测')
    _update_step(step_index, status = 'pending', current = 0, total = result['library'].get('total_items', 0), message = '等待开始...')
    _set_state(running = True, phase = 'library', progress = '准备检测 Emby 入库状态...', error = None, result = result, summary = summary)
    thread = threading.Thread(target = _library_check_worker, args = (result, emby_config_id), daemon = True)
    thread.start()
    return (True, 'Emby 入库检测已启动')
    return (True, 'Emby 入库检测已启动')
    '__pyarmor_exit_7259__(...)'
    '__pyarmor_exit_7259__(...)'


def _library_check_worker(result, emby_config_id):
    '''Emby 入库检测后台线程'''
    '__pyarmor_enter_7261__(...)'
    step_index = _ensure_step('Emby 入库检测')
# WARNING: Decompyle incomplete


def start_transfer(selected_items):
    '''启动转存任务'''
    '__pyarmor_enter_7264__(...)'
    state = _get_state()
    if state['running']:
        return (False, '已有任务在运行中')
    return (False, '已有任务在运行中')
    if not state.get('result'):
        return (False, '没有识别结果，请先扫描')
    return (False, '没有识别结果，请先扫描')
    _set_state(running = True, phase = 'transfer', progress = '准备转存...', error = None, transfer_result = None)
    thread = threading.Thread(target = _transfer_worker, args = (selected_items,), daemon = True)
    thread.start()
    return (True, '转存任务已启动')
    return (True, '转存任务已启动')
    '__pyarmor_exit_7265__(...)'
    '__pyarmor_exit_7265__(...)'


def _transfer_worker(selected_items):
    '''转存工作线程'''
    global _suppress_logs, _suppress_logs, _suppress_logs, _suppress_logs
    '__pyarmor_enter_7267__(...)'
    config = config_manager.get_bulk_transfer_config()
    _suppress_logs = not config.get('show_recognize_logs', False)
    mode = config.get('mode', 'transfer')
    multi_version = config.get('multi_version', False)
    config_name = config.get('use_115_config', '')
    config_115 = config_manager.get_115_config_by_name(config_name)
    if not config_115 or config_115.get('cookie'):
        _set_state(running = False, phase = '', error = '115 配置不可用')
        _suppress_logs = False
        return None
    return None
    cookie = config_115['cookie']
    if not config.get('transfer_folder'):
        config.get('transfer_folder')
    transfer_folder = { }
    target_cid = str(transfer_folder.get('cid', '0'))
    result = get_task_result()
    if not result:
        _set_state(running = False, phase = '', error = '没有识别结果')
        _suppress_logs = False
        return None
    return None
    movies = result.get('movies', [])
    tvshows = result.get('tvshows', [])
    selected_movie_ids = None
    selected_tv_ids = None
    if selected_items:
        selected_movie_ids = set(selected_items.get('movie_ids', []))
        selected_tv_ids = set(selected_items.get('tv_ids', []))
    total_success = 0
    total_fail = 0
    transfer_details = []
    if mode == 'transfer':
        (total_success, total_fail, transfer_details) = _do_transfer_mode(cookie, target_cid, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids)
    elif mode == 'share_strm':
        reshare_enabled = config.get('reshare_enabled', False)
        (total_success, total_fail, transfer_details) = _do_share_strm_mode(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, reshare_enabled)
    transfer_result = {
        'success': total_success,
        'fail': total_fail,
        'details': transfer_details,
        'mode': mode }
    _set_state(running = False, phase = 'done', progress = f'''完成: 成功 {total_success}, 失败 {total_fail}''', transfer_result = transfer_result)
    logger.info(f'''转存完成: 成功 {total_success}, 失败 {total_fail}''')
    _suppress_logs = False
    return None
    return None
# WARNING: Decompyle incomplete


def _do_transfer_mode(cookie, target_cid, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids):
    '''普通转存模式'''
    '__pyarmor_enter_7270__(...)'
    transferer = Transfer115(cookie, target_cid)
    total_success = 0
    total_fail = 0
    details = []
# WARNING: Decompyle incomplete


def _do_share_strm_mode(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, reshare_enabled):
    '''分享 STRM 模式（含转存再分享子开关）'''
    '__pyarmor_enter_7273__(...)'
    strm_folder_path = config.get('strm_folder_path', '')
    if not strm_folder_path:
        logger.error('未配置 STRM 生成目录')
        return (0, 0, [])
    None(None)
    return None
    if reshare_enabled:
        return _do_reshare_strm(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, strm_folder_path)
    None(None)
    return None
    return _do_direct_share_strm(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, strm_folder_path)
    None(None)
    return None
    '__pyarmor_exit_7274__(...)'
    '__pyarmor_exit_7274__(...)'


def _do_direct_share_strm(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, strm_folder_path):
    '''普通分享 STRM：直接用原始分享链接生成 STRM 文件'''
    '__pyarmor_enter_7276__(...)'
    strm_config = config_manager.get_share_strm_config()
    total_success = 0
    total_fail = 0
    details = []
# WARNING: Decompyle incomplete


def _do_reshare_strm(cookie, config, movies, tvshows, multi_version, selected_movie_ids, selected_tv_ids, strm_folder_path):
    '''转存再分享模式：在根目录创建 NanShare 临时文件夹 → 嵌套结构单文件转存 → 创建新分享 → 生成 STRM → 清理'''
    '__pyarmor_enter_7279__(...)'
    strm_config = config_manager.get_share_strm_config()
    transferer = Transfer115(cookie, '0')
    tmp_folder_name = f'''Nanshare-{''.join(random.choices(string.ascii_lowercase + string.digits, k = 4))}'''
    result = transferer.create_folder('0', tmp_folder_name)
    if not result.get('success'):
        logger.error(f'''创建临时文件夹失败: {result.get('message')}''')
        return (0, 0, [])
    None(None)
    return None
    tmp_cid = result['cid']
    logger.info(f'''创建临时文件夹: {tmp_folder_name} (CID: {tmp_cid})''')
    total_success = 0
    total_fail = 0
    details = []
    all_items = []
# WARNING: Decompyle incomplete


def _build_strm_content(strm_config, share_code, receive_code, fid, filename):
    '''构建 STRM 文件内容（与 StrmGenerator.get_strm_url 保持一致）'''
    '__pyarmor_enter_7282__(...)'
    request_url = strm_config.get('request_url', '')
    base_url = request_url.rstrip('/')
    url = f'''{base_url}/api/?share_code={share_code}&id={fid}&receive_code={receive_code}'''
    if not strm_config.get('strm_exclude_filename', True):
        url += f'''&{filename}'''
    return url
    None(None)
    return None
    '__pyarmor_exit_7283__(...)'
    '__pyarmor_exit_7283__(...)'

return None
return None
'__pyarmor_exit_7160__(...)'
'__pyarmor_exit_7160__(...)'
