# File: cloud189.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: cloud189.py.1shot.das

'''天翼云盘模块 - 账号密码登录、路径解析、获取 302 直链'''
'__pyarmor_enter_6820__(...)'
import json
import time
import httpx
from typing import Optional, Dict, Any, List
from config_manager import config_manager
from logger import logger_302 as logger

class Cloud189Client:
    '''天翼云盘客户端（账号密码登录，cookie 认证，302 直链）'''
    '__pyarmor_enter_6823__(...)'
    
    def __init__(self, username, password, cookies, config_name):
        '__pyarmor_enter_6826__(...)'
        self._username = username
        self._password = password
        if not cookies:
            cookies
        self._cookies = dict({ })
        self._config_name = config_name
        return None
        return None
        '__pyarmor_exit_6827__(...)'
        '__pyarmor_exit_6827__(...)'

    cookies = (lambda self: '__pyarmor_enter_6829__(...)'dict(self._cookies)None(None)None'__pyarmor_exit_6830__(...)''__pyarmor_exit_6830__(...)')()
    is_logged_in = (lambda self: '__pyarmor_enter_6832__(...)'bool(self._cookies)None(None)None'__pyarmor_exit_6833__(...)''__pyarmor_exit_6833__(...)')()
    
    def login(self):
        '''账号密码登录，返回 cookies 字典

        流程: login_unify_wap → login_submit → 跟随重定向收集 cookies
        需要关闭设备锁: https://e.dlife.cn/user/index.do
        '''
        '__pyarmor_enter_6835__(...)'
        P189Client = P189Client
        import p189client
        rsa_encrypt = rsa_encrypt
        import p189client.client
        quote = quote
        import urllib.parse
        data = P189Client.login_unify_wap()
        session = httpx.Client(follow_redirects = False, timeout = 30)
        if not data.get('captchaToken'):
            data.get('captchaToken')
        r = session.post('https://open.e.189.cn/api/logbox/oauth2/loginSubmit.do', data = {
            'appKey': 'cloud',
            'accountType': '01',
            'pageKey': 'normal',
            'userName': '{NRP}' + rsa_encrypt(self._username.encode('utf-8')).hex().upper(),
            'password': '{NRP}' + rsa_encrypt(self._password.encode('utf-8')).hex().upper(),
            'paramId': data['paramId'],
            'returnUrl': quote(data['returnUrl'], safe = ''),
            'captchaToken': '' }, headers = {
            'lt': data['lt'],
            'reqid': data['reqId'],
            'referer': data['url'],
            'Content-Type': 'application/x-www-form-urlencoded' })
        resp = r.json() if isinstance(r.text, str) else { }
        if resp.get('result') != 0:
            raise Exception(resp.get('msg', '登录失败'))
        cookies = { }
        url = resp['toUrl']
        for _ in range(10):
            r = session.get(url, cookies = cookies)
            for name, value in r.cookies.items():
                cookies[name] = value
            if r.status_code not in (301, 302, 303, 307, 308):
                pass
            else:
                url = r.headers.get('location', '')
                if url:
                    continue
        session.close()
        if not cookies:
            raise Exception('登录后未获取到有效 cookies')
        self._cookies = cookies
        return cookies
        None(None)
        return None
        session.close()
        '__pyarmor_exit_6836__(...)'
        '__pyarmor_exit_6836__(...)'

    
    def verify(self):
        '''验证 cookies 是否有效，返回用户信息'''
        '__pyarmor_enter_6838__(...)'
        P189Client = P189Client
        import p189client
        client = P189Client(cookies = self._cookies)
        info = client.user_info_portal()
        if not info.get('nickName'):
            info.get('nickName')
            if not info.get('userName'):
                info.get('userName')
        nickname = ''
        return {
            'nickname': nickname,
            'valid': True }
        None(None)
        return None
        '__pyarmor_exit_6839__(...)'
        '__pyarmor_exit_6839__(...)'

    
    def resolve_path(self, file_path):
        """按路径逐级查找文件，返回 {'fileId': ..., 'fileName': ..., 'fileSize': ...}"""
        '__pyarmor_enter_6841__(...)'
        P189Client = P189Client
        import p189client
        client = P189Client(cookies = self._cookies)
    # WARNING: Decompyle incomplete

    
    def get_download_url(self, file_id):
        '''获取文件的 302 直链

        使用 fs_info_portal 获取 downloadUrl，该 URL 可直接 302 重定向。
        '''
        '__pyarmor_enter_6844__(...)'
        P189Client = P189Client
        import p189client
        client = P189Client(cookies = self._cookies)
        info = client.fs_info_portal({
            'fileId': file_id })
        dl_url = info.get('downloadUrl', '')
        if not dl_url:
            raise Exception('未获取到下载链接')
        if dl_url.startswith('//'):
            dl_url = 'https:' + dl_url
        return dl_url
        None(None)
        return None
        '__pyarmor_exit_6845__(...)'
        '__pyarmor_exit_6845__(...)'

    return None
    property
    return None
    '__pyarmor_exit_6824__(...)'
    '__pyarmor_exit_6824__(...)'


def cloud189_verify_account(username, password):
    '''验证天翼云盘账号密码，返回 cookies 和用户信息'''
    '__pyarmor_enter_6847__(...)'
    client = Cloud189Client(username = username, password = password)
    cookies = client.login()
    user_info = client.verify()
    return {
        'cookies': cookies,
        'nickname': user_info.get('nickname', '') }
    None(None)
    return None
    '__pyarmor_exit_6848__(...)'
    '__pyarmor_exit_6848__(...)'


def cloud189_verify_cookies(cookies):
    '''验证已有 cookies 是否有效'''
    '__pyarmor_enter_6850__(...)'
    client = Cloud189Client(cookies = cookies)
    user_info = client.verify()
    return {
        'nickname': user_info.get('nickname', ''),
        'valid': True }
    None(None)
    return None
    '__pyarmor_exit_6851__(...)'
    '__pyarmor_exit_6851__(...)'


def get_direct_link_from_path_cloud189(file_path, config_name):
    '''通过路径获取天翼云盘文件的 302 直链

    Args:
        file_path: 网盘内路径，如 /以法之名/1-22 4k/xxx.mp4
        config_name: 天翼配置名称

    Returns:
        302 直链 URL 或 None
    '''
    '__pyarmor_enter_6853__(...)'
    config = config_manager.get_cloud189_config_by_name(config_name)
    if not config:
        logger.error(f'''未找到天翼配置: {config_name}''')
        return None
    return None
    if not config.get('cookies'):
        config.get('cookies')
    cookies = { }
    username = config.get('username', '')
    password = config.get('password', '')
    if not cookies:
        if not username or password:
            logger.error(f'''天翼配置 {config_name} 缺少 cookies 或账号密码''')
            return None
        return None
    start_time = time.time()
    client = Cloud189Client(username = username, password = password, cookies = cookies, config_name = config_name)
    if not cookies:
        logger.info(f'''天翼配置 {config_name} 无 cookies，尝试登录...''')
        new_cookies = client.login()
        _save_cookies_to_config(config_name, new_cookies)
    else:
        client.verify()
    file_info = client.resolve_path(file_path)
    file_id = file_info['fileId']
    url = client.get_download_url(file_id)
    elapsed = time.time() - start_time
    logger.success(f'''天翼云盘获取直链成功，耗时: {elapsed:.3f}s''')
    return url
    None(None)
    return None
# WARNING: Decompyle incomplete


def _save_cookies_to_config(config_name, cookies):
    '''将新 cookies 保存到配置'''
    '__pyarmor_enter_6856__(...)'
    config = config_manager.get_cloud189_config_by_name(config_name)
    if config:
        config['cookies'] = cookies
        config_manager.update_cloud189_config(config['id'], config)
        logger.info(f'''天翼配置 {config_name} cookies 已更新''')
    return None
    return None
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_6821__(...)'
'__pyarmor_exit_6821__(...)'
