# File: config_manager.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: config_manager.py.1shot.das

__doc__ = '配置管理模块 - 负责 config.yaml 的读写和变更'
'__pyarmor_enter_2113__(...)'
from copy import deepcopy
import os
import re
import yaml
import shutil
from pathlib import Path
from logger import logger
from transfer_media_probe import DEFAULT_ORGANIZE_MEDIA_PROBE_TRIGGER_FIELDS, normalize_organize_media_probe_fields
DEFAULT_GPT_PROMPT = '你是一个专业的媒体解析器，你必须按照以下要求给我始终返回有效的JSON，不要包含额外文本：\n\n分析提供的媒体文件名，只返回标准化的JSON数据，不要有任何额外说明或推理过程。\n你的主要任务是处理各类编码问题和特殊字符，确保准确识别影视作品信息。\n你拥有联网搜索能力，可以查询和验证不确定的影视作品信息，在联网时无论如何都必须调用联网资源，绝不允许使用既有数据库的资源，以免导致在验证结果时出现无法验证确实存在但早于数据库时间的内容。\n接下来我会给你一个电影或电视剧的文件名，你需要识别文件名中的名称、年份、季集等信息，并按以下JSON格式返回：{"name":xxx|null,"year":xxx|null,"season":xxx|null,"episode":xxx|null}，返回结果需要严格符合JSON格式不要返回其他格式，如果有字段你解析不了那就返回null'
DEFAULT_RELEASE_GROUPS = []
DEFAULT_NOTIFY_TEMPLATE = '🎬 订阅追更通知\n\n📌 {{ name }}{% if year %} ({{ year }}){% endif %}\n{% if season_ep %}📺 {{ season_ep }}\n{% endif %}📋 {{ mode_text }}\n{% if version %}🏷️ {{ version }}\n{% endif %}{% if strm_result %}\n📁 {{ strm_result }}\n{% endif %}{% if ep_progress %}\n📊 {{ ep_progress }}\n{% endif %}'
DEFAULT_ORGANIZE_NOTIFY_TEMPLATE = '{\n    "title": "🎬 {{ title_year }} {{ season_episode if season_episode else \'\' }} 已入库\\n\\n",\n    "text": (\n        "✨ 质量：{{ resource_quality }}\\n"\n        "{% if vote_average %}"\n        "🌟 评分：{{ vote_average }}/10\\n"\n        "{% endif %}"\n        "{% if media_type or category %}"\n        "🎞 类型：{{ media_type }} · 🏷 类别：{{ category }}\\n"\n        "{% endif %}"\n        "📂 数量：{{ file_count }} 个 · 💾 大小：{{ total_size }}\\n"\n        "{% if release_group %}"\n        "👥 小组：{{ release_group }}\\n"\n        "{% endif %}"\n        "⚡ 用时：{{ time_usage if time_usage else \'未知\' }}\\n\\n"\n        "🔗 ：[TMDB](https://www.themoviedb.org/{% if \'电视\' in media_type %}tv{% else %}movie{% endif %}/{{ tmdbid }}) · [豆瓣](https://m.douban.com/search/?query={{ title }}) · [IMDB](https://www.imdb.com/title/{{ imdbid }}) · [TVDB](https://thetvdb.com/?id={{ tvdbid }}&tab=series)\\n"\n        "{% if overview %}\\n"\n        "📝 简介：\\n{{ overview | truncate(50, True, \'...\') }}"\n        "{% endif %}"\n    )\n}'
DEFAULT_MOVIE_RENAME_FORMAT = '{{title}} ({{year}}) {tmdbid-{{tmdbid}}}/{{en_title}}.{{year}}.{{part}}.{{webSource}}.{{resourceType}}.{{videoFormat}}.{{videoCodec}}.{{audioCodec}}.{{effect}}.{{bitDepth}}.{{fps}}-{{customCapture}}-{{releaseGroup}}{{fileExt}}'
DEFAULT_TV_RENAME_FORMAT = '{{title}} ({{year}}) {tmdbid-{{tmdbid}}}/Season {{season|int}}/{{en_title}}.{{year}}.{{season_episode}}.{{part}}.{{webSource}}.{{resourceType}}.{{videoFormat}}.{{videoCodec}}.{{audioCodec}}.{{effect}}.{{bitDepth}}.{{fps}}-{{customCapture}}-{{releaseGroup}}{{fileExt}}'
DEFAULT_CATEGORY_CONFIG_RAW = "movie:\n  动画电影:\n    genre_ids: '16'\n  国产电影:\n    production_countries: 'CN'\n  港台电影:\n    production_countries: 'TW,HK'\n  韩国电影:\n    production_countries: 'KP,KR'\n  日本电影:\n    production_countries: 'JP'\n  欧美电影:\n    production_countries: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'\n  其他电影:\ntv:\n  国漫:\n    genre_ids: '16'\n    origin_country: 'CN,TW,HK'\n  日漫:\n    genre_ids: '16'\n    origin_country: 'JP'\n  欧美动漫:\n    genre_ids: '16'\n    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'\n  儿童动漫:\n    genre_ids: '10762'\n  纪录片:\n    genre_ids: '99'\n  综艺:\n    genre_ids: '10764,10767'\n  国产剧:\n    origin_country: 'CN'\n  港台剧:\n    origin_country: 'TW,HK'\n  欧美剧:\n    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'\n  日剧:\n    origin_country: 'JP'\n  韩剧:\n    origin_country: 'KP,KR'\n  其他剧:\n"
if not yaml.safe_load(DEFAULT_CATEGORY_CONFIG_RAW):
    yaml.safe_load(DEFAULT_CATEGORY_CONFIG_RAW)
DEFAULT_CATEGORY_CONFIG = {
    'movie': { },
    'tv': { } }

def get_default_category_config():
    '__pyarmor_enter_2116__(...)'
    return deepcopy(DEFAULT_CATEGORY_CONFIG)
    None(None)
    return None
    '__pyarmor_exit_2117__(...)'
    '__pyarmor_exit_2117__(...)'


def get_default_category_raw():
    '__pyarmor_enter_2119__(...)'
    return DEFAULT_CATEGORY_CONFIG_RAW if DEFAULT_CATEGORY_CONFIG_RAW.endswith('\n') else DEFAULT_CATEGORY_CONFIG_RAW + '\n'
    None(None)
    return None
    '__pyarmor_exit_2120__(...)'
    '__pyarmor_exit_2120__(...)'


def get_default_transfer_basic_config():
    '__pyarmor_enter_2122__(...)'
    return {
        'movie_rename_format': DEFAULT_MOVIE_RENAME_FORMAT,
        'tv_rename_format': DEFAULT_TV_RENAME_FORMAT,
        'organize_notify_enabled': False,
        'organize_notify_template': DEFAULT_ORGANIZE_NOTIFY_TEMPLATE,
        'media_info_extract_trigger_fields': list(DEFAULT_ORGANIZE_MEDIA_PROBE_TRIGGER_FIELDS),
        'tmdb_cache_enabled': True,
        'meta_cache_expire_hours': 24,
        'gpt_cache_enabled': True,
        'gpt_cache_expire_hours': 24 }
    None(None)
    return None
    '__pyarmor_exit_2123__(...)'
    '__pyarmor_exit_2123__(...)'


def normalize_transfer_basic_config(config):
    '__pyarmor_enter_2125__(...)'
    defaults = get_default_transfer_basic_config()
    if not config:
        config
    incoming = { }
    if 'media_info_extract_trigger_fields' in incoming:
        media_info_extract_trigger_fields = normalize_organize_media_probe_fields(incoming.get('media_info_extract_trigger_fields'))
    else:
        media_info_extract_trigger_fields = list(defaults['media_info_extract_trigger_fields'])
    if not incoming.get('movie_rename_format'):
        incoming.get('movie_rename_format')
    if not incoming.get('tv_rename_format'):
        incoming.get('tv_rename_format')
    if not incoming.get('organize_notify_template'):
        incoming.get('organize_notify_template')
    return {
        'movie_rename_format': str(defaults['movie_rename_format']),
        'tv_rename_format': str(defaults['tv_rename_format']),
        'organize_notify_enabled': _to_bool(incoming.get('organize_notify_enabled'), defaults['organize_notify_enabled']),
        'organize_notify_template': str(defaults['organize_notify_template']),
        'media_info_extract_trigger_fields': media_info_extract_trigger_fields,
        'tmdb_cache_enabled': _to_bool(incoming.get('tmdb_cache_enabled'), defaults['tmdb_cache_enabled']),
        'meta_cache_expire_hours': _to_positive_int(incoming.get('meta_cache_expire_hours'), defaults['meta_cache_expire_hours']),
        'gpt_cache_enabled': _to_bool(incoming.get('gpt_cache_enabled'), defaults['gpt_cache_enabled']),
        'gpt_cache_expire_hours': _to_positive_int(incoming.get('gpt_cache_expire_hours'), defaults['gpt_cache_expire_hours']) }
    None(None)
    return None
    '__pyarmor_exit_2126__(...)'
    '__pyarmor_exit_2126__(...)'


def _to_bool(value, default):
    '__pyarmor_enter_2128__(...)'
# WARNING: Decompyle incomplete


def _to_positive_int(value, default):
    '__pyarmor_enter_2131__(...)'
    number = int(value)
    return number if number > 0 else default
    None(None)
    return None
# WARNING: Decompyle incomplete


def _normalize_choice(value, allowed_values, default):
    '__pyarmor_enter_2134__(...)'
    if not value:
        value
    text = str('').strip().lower()
    return text if text in allowed_values else default
    None(None)
    return None
    '__pyarmor_exit_2135__(...)'
    '__pyarmor_exit_2135__(...)'


def get_default_file_transfer_config():
    '__pyarmor_enter_2137__(...)'
# WARNING: Decompyle incomplete


def normalize_file_transfer_config(config, legacy_metadata_config):
    '__pyarmor_enter_2140__(...)'
    defaults = get_default_file_transfer_config()
    if not config:
        config
    incoming = dict({ })
    if not legacy_metadata_config:
        legacy_metadata_config
    legacy_metadata_config = dict({ })
    if not incoming.get('monitor_mode'):
        incoming.get('monitor_mode')
    raw_monitor_mode = str('').strip().lower()
    if raw_monitor_mode in ('event', 'fast'):
        raw_monitor_mode = 'performance'
    monitor_mode = _normalize_choice(raw_monitor_mode, {
        'compatibility',
        'performance'}, defaults['monitor_mode'])
    transfer_type = _normalize_choice(incoming.get('transfer_type'), {
        'copy',
        'move',
        '115_copy',
        '115_move',
        'cd2_copy',
        'cd2_move'}, defaults['transfer_type'])
    if transfer_type in ('115_move', '115_copy', 'cd2_move', 'cd2_copy'):
        monitor_mode = 'compatibility'
    if not incoming.get('overwrite_mode'):
        incoming.get('overwrite_mode')
    raw_overwrite_mode = str('').strip().lower()
    overwrite_mode = raw_overwrite_mode
    if overwrite_mode == 'never':
        overwrite_mode = defaults['overwrite_mode']
    overwrite_mode = _normalize_choice(overwrite_mode, {
        'size',
        'always',
        'resolution'}, defaults['overwrite_mode'])
    overwrite_enabled = incoming.get('overwrite_enabled')
# WARNING: Decompyle incomplete

# WARNING: Decompyle incomplete
