# File: device_manager.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: device_manager.py.1shot.das

'''设备管理器 - 生成并管理设备指纹'''
'__pyarmor_enter_2872__(...)'
import os
import json
import hashlib
import base64
from pathlib import Path
from typing import Tuple, Optional, Dict
from core.logger import logger

class DeviceManager:
    '''设备管理器 - 负责基于硬件信息生成稳定的设备码'''
    '__pyarmor_enter_2875__(...)'
    
    def __init__(self):
        '''初始化设备管理器'''
        '__pyarmor_enter_2878__(...)'
        self._device_info = None
        return None
        return None
        '__pyarmor_exit_2879__(...)'
        '__pyarmor_exit_2879__(...)'

    _DMI_PATHS = [
        ('/sys/class/dmi/id/product_uuid', 'system_uuid'),
        ('/sys/class/dmi/id/product_serial', 'system_serial'),
        ('/sys/class/dmi/id/board_serial', 'board_serial'),
        ('/sys/class/dmi/id/chassis_serial', 'chassis_serial'),
        ('/sys/class/dmi/id/board_name', 'board_name'),
        ('/sys/class/dmi/id/product_name', 'product_name'),
        ('/sys/class/dmi/id/bios_vendor', 'bios_vendor')]
    _DMI_INVALID = {
        '',
        'none',
        'not specified',
        'default string',
        'not applicable',
        'system product name',
        'system serial number',
        'to be filled by o.e.m.'}
    
    def _collect_hardware_info(self):
        '''收集多维度宿主机硬件信息（Docker 环境下也不会变化）'''
        '__pyarmor_enter_2881__(...)'
        import platform
        info = { }
    # WARNING: Decompyle incomplete

    
    def _generate_device_id(self):
        '''基于多维度硬件信息生成稳定的设备ID'''
        '__pyarmor_enter_2884__(...)'
        hardware_info = self._collect_hardware_info()
        fingerprint_parts = [
            hardware_info.get('system_uuid', ''),
            hardware_info.get('system_serial', ''),
            hardware_info.get('board_serial', ''),
            hardware_info.get('chassis_serial', ''),
            hardware_info.get('board_name', ''),
            hardware_info.get('product_name', ''),
            hardware_info.get('bios_vendor', ''),
            hardware_info.get('os', ''),
            hardware_info.get('os_release', ''),
            hardware_info.get('machine', ''),
            hardware_info.get('cpu', '')]
        fingerprint_str = (lambda .0: pass# WARNING: Decompyle incomplete
)(fingerprint_parts())
        device_hash = hashlib.sha256(fingerprint_str.encode()).hexdigest()
        return f'''{device_hash[:8]}-{device_hash[8:12]}-{device_hash[12:16]}-{device_hash[16:20]}-{device_hash[20:32]}'''
        None('|'.join)
        return None
        '__pyarmor_exit_2885__(...)'
        '__pyarmor_exit_2885__(...)'

    
    def _generate_device_secret(self, license_key):
        '''基于多维度硬件信息 + license_key 生成设备密钥'''
        '__pyarmor_enter_2887__(...)'
        hardware_info = self._collect_hardware_info()
        secret_parts = [
            hardware_info.get('system_uuid', ''),
            hardware_info.get('system_serial', ''),
            hardware_info.get('board_serial', ''),
            hardware_info.get('chassis_serial', ''),
            hardware_info.get('board_name', ''),
            hardware_info.get('product_name', ''),
            hardware_info.get('bios_vendor', ''),
            hardware_info.get('os', ''),
            hardware_info.get('os_release', ''),
            hardware_info.get('machine', ''),
            hardware_info.get('cpu', ''),
            license_key]
        secret_str = (lambda .0: pass# WARNING: Decompyle incomplete
)(secret_parts())
        return hashlib.sha256(secret_str.encode()).hexdigest()
        None('::'.join)
        return None
        '__pyarmor_exit_2888__(...)'
        '__pyarmor_exit_2888__(...)'

    
    def _hash_secret(self, secret):
        '''对密钥进行哈希（服务端存储用）'''
        '__pyarmor_enter_2890__(...)'
        return hashlib.sha256(secret.encode()).hexdigest()
        None(None)
        return None
        '__pyarmor_exit_2891__(...)'
        '__pyarmor_exit_2891__(...)'

    
    def _collect_environment_info(self):
        '''收集环境信息（用于异常检测，非验证用）'''
        '__pyarmor_enter_2893__(...)'
        import socket
        info = {
            'hostname': socket.gethostname() }
        return info
        None(None)
        return None
        '__pyarmor_exit_2894__(...)'
        '__pyarmor_exit_2894__(...)'

    
    def get_or_create_device_info(self, license_key):
        '''
        获取设备信息（基于硬件信息 + license_key 生成，同一设备同一 key 每次结果相同）
        
        Returns:
            (device_id, device_secret)
        '''
        '__pyarmor_enter_2896__(...)'
        if self._device_info and self._device_info.get('license_key') == license_key:
            return (self._device_info['device_id'], self._device_info['device_secret'])
        None(None)
        return None
        device_id = self._generate_device_id()
        device_secret = self._generate_device_secret(license_key)
        self._device_info = {
            'device_id': device_id,
            'device_secret': device_secret,
            'license_key': license_key }
        return (device_id, device_secret)
        None(None)
        return None
        '__pyarmor_exit_2897__(...)'
        '__pyarmor_exit_2897__(...)'

    
    def _get_timestamp(self):
        '''获取当前时间戳'''
        '__pyarmor_enter_2899__(...)'
        datetime = datetime
        import datetime
        return datetime.now().isoformat()
        None(None)
        return None
        '__pyarmor_exit_2900__(...)'
        '__pyarmor_exit_2900__(...)'

    
    def get_verification_payload(self, license_key):
        '''
        获取验证请求的 payload
        
        Args:
            license_key: 用户的 license_key（参与 device_secret 计算）
        
        Returns:
            包含设备验证信息的字典
        '''
        '__pyarmor_enter_2902__(...)'
        (device_id, device_secret) = self.get_or_create_device_info(license_key)
        return {
            'device_id': device_id,
            'device_secret': device_secret }
        None(None)
        return None
        '__pyarmor_exit_2903__(...)'
        '__pyarmor_exit_2903__(...)'

    
    def get_device_id(self):
        '''获取设备ID'''
        '__pyarmor_enter_2905__(...)'
        if self._device_info:
            return self._device_info.get('device_id')
        None(None)
        return None
        return None
        return None
        '__pyarmor_exit_2906__(...)'
        '__pyarmor_exit_2906__(...)'

    return None
    return None
    '__pyarmor_exit_2876__(...)'
    '__pyarmor_exit_2876__(...)'

device_manager = DeviceManager()
return None
return None
'__pyarmor_exit_2873__(...)'
'__pyarmor_exit_2873__(...)'
