# File: douban_discover.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: douban_discover.py.1shot.das

'''豆瓣探索模块'''
'__pyarmor_enter_2908__(...)'
import base64
import hashlib
import hmac
import re
import time
from datetime import datetime
from random import choice
from typing import Optional, List, Dict, Any
from urllib import parse
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
from logger import logger_subscribe as logger
from config_manager import config_manager

class DoubanApi:
    __module__ = __name__
    __qualname__ = 'DoubanApi'
    __doc__ = '豆瓣 Frodo API 客户端'
    '__pyarmor_enter_2911__(...)'
# WARNING: Decompyle incomplete


class DoubanDiscover:
    '''豆瓣探索 - 高层业务接口，标准化输出格式'''
    '__pyarmor_enter_2989__(...)'
    IMG_PROXY_PATH = '/api/douban/img?imgurl='
    
    def __init__(self):
        '__pyarmor_enter_2992__(...)'
        self._api = DoubanApi()
        return None
        return None
        '__pyarmor_exit_2993__(...)'
        '__pyarmor_exit_2993__(...)'

    
    def _normalize_item(self, item):
        '''将豆瓣 subject_collection_item 标准化为前端期望的格式'''
        '__pyarmor_enter_2995__(...)'
        if not item:
            return { }
        None(None)
        return None
        douban_id = str(item.get('id', ''))
        title = item.get('title', '')
        year = item.get('year', '')
        if not year:
            subtitle = item.get('card_subtitle', '')
            if subtitle:
                m = re.match('(\\d{4})', subtitle.strip())
                if m:
                    year = m.group(1)
        poster = ''
        pic = item.get('pic', { })
        if isinstance(pic, dict):
            if not pic.get('large', ''):
                pic.get('large', '')
                if not pic.get('normal', ''):
                    pic.get('normal', '')
            poster = pic.get('url', '')
        elif isinstance(pic, str):
            poster = pic
        if not poster:
            if not item.get('cover_url', ''):
                item.get('cover_url', '')
            cover = item.get('cover', '')
            if isinstance(cover, dict):
                poster = cover.get('url', '')
            elif isinstance(cover, str):
                poster = cover
        if poster:
            poster = f'''{self.IMG_PROXY_PATH}{parse.quote(poster, safe = '')}'''
        vote = 0
        rating = item.get('rating', { })
        if isinstance(rating, dict):
            if not rating.get('value', 0):
                rating.get('value', 0)
            vote = float(0)
        elif isinstance(rating, (int, float)):
            vote = float(rating)
        media_type = 'movie'
        if not item.get('type', ''):
            item.get('type', '')
        subtype = item.get('subtype', '')
        if subtype in ('tv', 'TVSeries', 'show'):
            media_type = 'tv'
        elif item.get('is_tv'):
            media_type = 'tv'
        elif item.get('episodes_count') and int(item.get('episodes_count', 0)) > 0:
            media_type = 'tv'
        if not item.get('intro', ''):
            item.get('intro', '')
            if not item.get('card_subtitle', ''):
                item.get('card_subtitle', '')
        overview = ''
        if not item.get('original_title', ''):
            item.get('original_title', '')
        return {
            'douban_id': douban_id,
            'tmdb_id': 0,
            'title': title,
            'original_title': title,
            'year': year,
            'type': media_type,
            'poster_path': poster,
            'backdrop_path': '',
            'overview': overview,
            'vote_average': vote,
            'popularity': 0,
            'genre_ids': [],
            'source': 'douban' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _normalize_collection(self, data):
        '''标准化 subject_collection 类型的返回值'''
        '__pyarmor_enter_2998__(...)'
        items = data.get('subject_collection_items', [])
        if not items:
            return []
        None(None)
        return None
        results = []
        for item in items:
            normalized = self._normalize_item(item)
            if not normalized:
                continue
            if not normalized.get('title'):
                continue
            if normalized.get('poster_path') or 'movie_large.jpg' in normalized.get('poster_path', ''):
                continue
            results.append(normalized)
        return results
        None(None)
        return None
        '__pyarmor_exit_2999__(...)'
        '__pyarmor_exit_2999__(...)'

    
    def _normalize_recommend(self, data):
        '''标准化 recommend 类型的返回值'''
        '__pyarmor_enter_3001__(...)'
        items = data.get('items', [])
        if not items:
            return []
        None(None)
        return None
        results = []
        for item in items:
            normalized = self._normalize_item(item)
            if not normalized:
                continue
            if not normalized.get('title'):
                continue
            if normalized.get('poster_path') or 'movie_large.jpg' in normalized.get('poster_path', ''):
                continue
            results.append(normalized)
        return results
        None(None)
        return None
        '__pyarmor_exit_3002__(...)'
        '__pyarmor_exit_3002__(...)'

    
    def movie_showing(self, page, count):
        '__pyarmor_enter_3004__(...)'
        data = self._api.movie_showing(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3005__(...)'
        '__pyarmor_exit_3005__(...)'

    
    def movie_hot(self, page, count):
        '__pyarmor_enter_3007__(...)'
        data = self._api.movie_hot_gaia(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3008__(...)'
        '__pyarmor_exit_3008__(...)'

    
    def tv_hot(self, page, count):
        '__pyarmor_enter_3010__(...)'
        data = self._api.tv_hot(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3011__(...)'
        '__pyarmor_exit_3011__(...)'

    
    def tv_animation(self, page, count):
        '__pyarmor_enter_3013__(...)'
        data = self._api.tv_animation(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3014__(...)'
        '__pyarmor_exit_3014__(...)'

    
    def movie_top250(self, page, count):
        '__pyarmor_enter_3016__(...)'
        data = self._api.movie_top250(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3017__(...)'
        '__pyarmor_exit_3017__(...)'

    
    def tv_weekly_chinese(self, page, count):
        '__pyarmor_enter_3019__(...)'
        data = self._api.tv_chinese_best_weekly(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3020__(...)'
        '__pyarmor_exit_3020__(...)'

    
    def tv_weekly_global(self, page, count):
        '__pyarmor_enter_3022__(...)'
        data = self._api.tv_global_best_weekly(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3023__(...)'
        '__pyarmor_exit_3023__(...)'

    
    def movie_soon(self, page, count):
        '__pyarmor_enter_3025__(...)'
        data = self._api.movie_soon(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3026__(...)'
        '__pyarmor_exit_3026__(...)'

    
    def movie_scifi(self, page, count):
        '__pyarmor_enter_3028__(...)'
        data = self._api.movie_scifi(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3029__(...)'
        '__pyarmor_exit_3029__(...)'

    
    def movie_comedy(self, page, count):
        '__pyarmor_enter_3031__(...)'
        data = self._api.movie_comedy(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3032__(...)'
        '__pyarmor_exit_3032__(...)'

    
    def movie_action(self, page, count):
        '__pyarmor_enter_3034__(...)'
        data = self._api.movie_action(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3035__(...)'
        '__pyarmor_exit_3035__(...)'

    
    def movie_love(self, page, count):
        '__pyarmor_enter_3037__(...)'
        data = self._api.movie_love(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3038__(...)'
        '__pyarmor_exit_3038__(...)'

    
    def tv_domestic(self, page, count):
        '__pyarmor_enter_3040__(...)'
        data = self._api.tv_domestic(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3041__(...)'
        '__pyarmor_exit_3041__(...)'

    
    def tv_american(self, page, count):
        '__pyarmor_enter_3043__(...)'
        data = self._api.tv_american(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3044__(...)'
        '__pyarmor_exit_3044__(...)'

    
    def tv_japanese(self, page, count):
        '__pyarmor_enter_3046__(...)'
        data = self._api.tv_japanese(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3047__(...)'
        '__pyarmor_exit_3047__(...)'

    
    def tv_korean(self, page, count):
        '__pyarmor_enter_3049__(...)'
        data = self._api.tv_korean(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3050__(...)'
        '__pyarmor_exit_3050__(...)'

    
    def tv_variety_show(self, page, count):
        '__pyarmor_enter_3052__(...)'
        data = self._api.tv_variety_show(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3053__(...)'
        '__pyarmor_exit_3053__(...)'

    
    def show_hot(self, page, count):
        '__pyarmor_enter_3055__(...)'
        data = self._api.show_hot(start = (page - 1) * count, count = count)
        return self._normalize_collection(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3056__(...)'
        '__pyarmor_exit_3056__(...)'

    
    def movies(self, sort, tags, page, count):
        '__pyarmor_enter_3058__(...)'
        data = self._api.movie_recommend(tags = tags, sort = sort, start = (page - 1) * count, count = count)
        return self._normalize_recommend(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3059__(...)'
        '__pyarmor_exit_3059__(...)'

    
    def tvs(self, sort, tags, page, count):
        '__pyarmor_enter_3061__(...)'
        data = self._api.tv_recommend(tags = tags, sort = sort, start = (page - 1) * count, count = count)
        return self._normalize_recommend(data) if data else []
        None(None)
        return None
        '__pyarmor_exit_3062__(...)'
        '__pyarmor_exit_3062__(...)'

    
    def search(self, keyword, page, count):
        '''豆瓣搜索'''
        '__pyarmor_enter_3064__(...)'
        data = self._api.search(keyword = keyword, start = (page - 1) * count, count = count)
        if not data:
            return []
        None(None)
        return None
        items = data.get('items', [])
        results = []
        for item in items:
            target = item.get('target', { })
            if not target:
                continue
            target_type = item.get('target_type', '')
            if target_type not in ('movie', 'tv', 'show'):
                continue
            normalized = self._normalize_item(target)
            if not normalized:
                continue
            if not normalized.get('title'):
                continue
            results.append(normalized)
        return results
        None(None)
        return None
        '__pyarmor_exit_3065__(...)'
        '__pyarmor_exit_3065__(...)'

    return None
    return None
    '__pyarmor_exit_2990__(...)'
    '__pyarmor_exit_2990__(...)'

_douban_discover = None

def get_douban_discover():
    '__pyarmor_enter_3067__(...)'
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_2909__(...)'
'__pyarmor_exit_2909__(...)'
