# File: ed2k_hash_service.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: ed2k_hash_service.py.1shot.das

'''ED2K Hash 生成服务 - 队列管理、线程池、进度追踪'''
'__pyarmor_enter_6859__(...)'
import os
import time
import uuid
import urllib.parse as urllib
import threading
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from collections import OrderedDict
from ed2k import MD4Hash, MD4_BLOCK_SIZE, MD4_EMPTY_HASH
from logger import logger
from config_manager import config_manager

def ed2k_hash_with_progress(filepath, progress_callback):
    '''计算文件的 ED2K hash，支持进度回调
    
    Args:
        filepath: 文件路径
        progress_callback: 回调函数 callback(bytes_processed, total_bytes)
    
    Returns:
        (file_size, hash_hex_upper) 或在取消时返回 None
    '''
    '__pyarmor_enter_6862__(...)'
    file_size = os.path.getsize(filepath)
    block_hashes = bytearray()
    bytes_processed = 0
# WARNING: Decompyle incomplete


class Ed2kHashService:
    '''ED2K Hash 生成服务（单例）'''
    '__pyarmor_enter_6865__(...)'
    _instance = None
    _lock = threading.Lock()
    
    def __new__(cls):
        '__pyarmor_enter_6868__(...)'
    # WARNING: Decompyle incomplete

    
    def __init__(self):
        '__pyarmor_enter_6871__(...)'
        if hasattr(self, '_initialized'):
            return None
        return None
        self._initialized = True
        self._queue = OrderedDict()
        self._executor = None
        self._max_workers = 3
        self._running = True
        self._queue_lock = threading.Lock()
        self._delete_source = False
        self._delete_queue = []
        self._delete_lock = threading.Lock()
        self._delete_thread = None
        self._load_config()
        return None
        return None
        '__pyarmor_exit_6872__(...)'
        '__pyarmor_exit_6872__(...)'

    
    def _load_config(self):
        '''从配置加载线程数和删除源文件开关'''
        '__pyarmor_enter_6874__(...)'
        cfg = config_manager.get_ed2k_hash_config()
        self._max_workers = max(1, min(cfg.get('threads', 1), 16))
        self._delete_source = bool(cfg.get('delete_source', False))
        self._rebuild_executor()
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _rebuild_executor(self):
        '''重建线程池'''
        '__pyarmor_enter_6877__(...)'
        if self._executor:
            self._executor.shutdown(wait = False)
        self._executor = ThreadPoolExecutor(max_workers = self._max_workers)
        return None
        return None
        '__pyarmor_exit_6878__(...)'
        '__pyarmor_exit_6878__(...)'

    
    def update_threads(self, threads):
        '''实时更新线程数'''
        '__pyarmor_enter_6880__(...)'
        threads = max(1, min(int(threads), 16))
        if threads != self._max_workers:
            self._max_workers = threads
            self._rebuild_executor()
            logger.info(f'''[ED2K Hash] 线程数已更新为 {threads}''')
        return None
        return None
        '__pyarmor_exit_6881__(...)'
        '__pyarmor_exit_6881__(...)'

    
    def update_delete_source(self, enabled):
        '''实时更新删除源文件开关'''
        '__pyarmor_enter_6883__(...)'
        self._delete_source = bool(enabled)
        logger.info(f'''[ED2K Hash] 删除源文件: {'开启' if self._delete_source else '关闭'}''')
        return None
        return None
        '__pyarmor_exit_6884__(...)'
        '__pyarmor_exit_6884__(...)'

    
    def submit(self, path):
        '''提交路径（文件或文件夹）到队列
        
        文件夹异步扫描，立即返回响应。
        
        Returns:
            batch_id: 批次ID
        '''
        '__pyarmor_enter_6886__(...)'
        batch_id = str(uuid.uuid4())[:8]
        path_obj = Path(path)
        if not path_obj.exists():
            return (None, f'''路径不存在: {path}''')
        None(None)
        return None
        if path_obj.is_file():
            (added, skipped) = self._submit_files([
                str(path_obj)], batch_id)
            if not skipped and added:
                return (batch_id, '该文件已在队列中，已跳过')
            None(None)
            return None
        logger.info(f'''[ED2K Hash] 提交批次 {batch_id}，1 个文件''')
        return (batch_id, '已提交 1 个文件')
        None(None)
        return None
        if path_obj.is_dir():
            threading.Thread(target = self._scan_dir_and_submit, args = (str(path_obj), batch_id), daemon = True).start()
            logger.info(f'''[ED2K Hash] 提交批次 {batch_id}，正在扫描文件夹: {path}''')
            return (batch_id, '文件夹已提交，正在后台扫描...')
        None(None)
        return None
        return (None, '不支持的路径类型')
        return (None, '不支持的路径类型')
        '__pyarmor_exit_6887__(...)'
        '__pyarmor_exit_6887__(...)'

    
    def _scan_dir_and_submit(self, dir_path, batch_id):
        '''后台扫描文件夹并逐个提交任务'''
        '__pyarmor_enter_6889__(...)'
        total_added = 0
        total_skipped = 0
    # WARNING: Decompyle incomplete

    
    def _submit_files(self, files, batch_id):
        '''将文件列表加入队列并提交到线程池，跳过已存在的任务
        
        Returns:
            (added, skipped): 新增数量和跳过数量
        '''
        '__pyarmor_enter_6892__(...)'
        tasks = []
        skipped = 0
    # WARNING: Decompyle incomplete

    
    def _process_task(self, task_id):
        '''处理单个任务'''
        '__pyarmor_enter_6895__(...)'
    # WARNING: Decompyle incomplete

    
    def _enqueue_delete(self, filepath):
        '''将文件路径加入删除队列，确保单线程顺序删除（防止网盘风控）'''
        '__pyarmor_enter_6901__(...)'
    # WARNING: Decompyle incomplete

    
    def _delete_worker(self):
        '''后台单线程逐个删除源文件'''
        '__pyarmor_enter_6904__(...)'
        filepath = None
    # WARNING: Decompyle incomplete

    
    def get_queue(self, page, page_size, status_filter):
        '''获取队列信息（分页）'''
        '__pyarmor_enter_6907__(...)'
    # WARNING: Decompyle incomplete

    
    def cancel_task(self, task_id):
        '''取消单个任务'''
        '__pyarmor_enter_6910__(...)'
    # WARNING: Decompyle incomplete

    
    def cancel_batch(self, batch_id):
        '''取消整个批次'''
        '__pyarmor_enter_6913__(...)'
        count = 0
    # WARNING: Decompyle incomplete

    
    def clear_completed(self):
        '''清除已完成/失败/取消的任务'''
        '__pyarmor_enter_6916__(...)'
    # WARNING: Decompyle incomplete

    
    def remove_tasks(self, task_ids):
        '''删除指定任务（运行中的先取消）'''
        '__pyarmor_enter_6919__(...)'
        removed = 0
    # WARNING: Decompyle incomplete

    
    def remove_all_tasks(self):
        '''删除全部任务（运行中的先取消）'''
        '__pyarmor_enter_6922__(...)'
    # WARNING: Decompyle incomplete

    
    def get_batch_results(self, batch_id):
        '''获取批次的所有结果'''
        '__pyarmor_enter_6925__(...)'
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_6866__(...)'
    '__pyarmor_exit_6866__(...)'

ed2k_hash_service = Ed2kHashService()
return None
return None
'__pyarmor_exit_6860__(...)'
'__pyarmor_exit_6860__(...)'
