# File: empty_folder_scanner.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: empty_folder_scanner.py.1shot.das

'''空文件夹扫描器 - 递归扫描目录，找出不含 .strm 文件的文件夹'''
'__pyarmor_enter_3619__(...)'
import os
import shutil
import threading
from pathlib import Path
from typing import List, Dict
from logger import logger
scan_state = {
    'running': False,
    'progress': '',
    'error': None,
    'results': [],
    'total_scanned': 0 }

def _scan_empty_folders(directory):
    '''递归扫描目录，找出所有不含 .strm 文件的子文件夹。
    
    算法：
    1. 递归遍历所有子目录
    2. 对每个子目录，递归检查是否含 .strm 文件
    3. 只保留"最上层"的空目录（如果父目录已标记为空，则不再标记子目录）
    '''
    '__pyarmor_enter_3622__(...)'
    scan_state['running'] = True
    scan_state['progress'] = '正在扫描目录结构...'
    scan_state['error'] = None
    scan_state['results'] = []
    scan_state['total_scanned'] = 0
    root = Path(directory)
    if not root.exists() or root.is_dir():
        scan_state['error'] = '目录不存在'
        scan_state['running'] = False
        return None
    return None
    all_subdirs = []
    for p in root.rglob('*'):
        if not p.is_dir():
            continue
        all_subdirs.append(p)
    total = len(all_subdirs)
    scan_state['progress'] = f'''共发现 {total} 个子目录，开始检测 .strm 状态...'''
    logger.info(f'''空文件夹扫描: {directory}，共 {total} 个子目录''')
    has_strm_cache = { }
    
    def has_strm(dir_path):
        '''递归检查目录是否含 .strm 文件（带缓存）'''
        '__pyarmor_enter_3625__(...)'
        key = str(dir_path)
        if key in has_strm_cache:
            return has_strm_cache[key]
        None(None)
        return None
        for _ in dir_path.rglob('*.strm'):
            has_strm_cache[key] = True
            dir_path.rglob('*.strm')
            return True
            return True
        has_strm_cache[key] = False
        return False
        return False
    # WARNING: Decompyle incomplete

    empty_dirs = []
    for idx, subdir in enumerate(all_subdirs):
        if (idx + 1) % 50 == 0 or idx + 1 == total:
            scan_state['progress'] = f'''检测进度: {idx + 1}/{total}'''
            scan_state['total_scanned'] = idx + 1
        if has_strm(subdir):
            continue
        empty_dirs.append(subdir)
    empty_set = (lambda .0: pass# WARNING: Decompyle incomplete
)(empty_dirs())
    top_level_empty = []
    for d in empty_dirs:
        parent = d.parent
        is_child_of_empty = False
        if parent != root and parent != parent.parent:
            pass
        if is_child_of_empty:
            continue
        top_level_empty.append(d)
    results = []
# WARNING: Decompyle incomplete


def start_scan(directory):
    '''启动后台扫描线程，返回是否成功启动'''
    '__pyarmor_enter_3628__(...)'
    if scan_state['running']:
        return False
    return False
    thread = threading.Thread(target = _scan_empty_folders, args = (directory,), daemon = True)
    thread.start()
    return True
    return True
    '__pyarmor_exit_3629__(...)'
    '__pyarmor_exit_3629__(...)'


def delete_folders(paths):
    '''删除指定的文件夹列表'''
    '__pyarmor_enter_3631__(...)'
    deleted = 0
    failed = 0
    errors = []
    for p in paths:
        target = Path(p)
    continue
    deleted_set = set(paths)
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_3620__(...)'
'__pyarmor_exit_3620__(...)'
