# File: export_shares.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: export_shares.py.1shot.das

'''115 分享导出模块'''
'__pyarmor_enter_3724__(...)'
import time
import json
import requests
from typing import Tuple, List, Dict
from pathlib import Path
from logger import Logger
logger_strm = Logger('strm.log')

class ShareExporter:
    '''115 分享导出器'''
    '__pyarmor_enter_3727__(...)'
    
    def __init__(self, cookie):
        '__pyarmor_enter_3730__(...)'
        self.cookie = cookie
        self.cookies = self._parse_cookie(cookie)
        self.user_id = self._get_user_id_from_cookie()
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Referer': 'https://115.com/' }
        return None
        return None
        '__pyarmor_exit_3731__(...)'
        '__pyarmor_exit_3731__(...)'

    
    def _parse_cookie(self, cookie_str):
        '''解析 Cookie 字符串为字典'''
        '__pyarmor_enter_3733__(...)'
        cookies = { }
        for item in cookie_str.split(';'):
            if not '=' in item:
                continue
            (key, value) = item.strip().split('=', 1)
            cookies[key] = value
        return cookies
        None(None)
        return None
        '__pyarmor_exit_3734__(...)'
        '__pyarmor_exit_3734__(...)'

    
    def _get_user_id_from_cookie(self):
        '''从 Cookie 中提取 user_id'''
        '__pyarmor_enter_3736__(...)'
        uid = self.cookies.get('UID', '')
        if '_' in uid:
            return uid.split('_')[0]
        None(None)
        return None
        return uid
        None(None)
        return None
        '__pyarmor_exit_3737__(...)'
        '__pyarmor_exit_3737__(...)'

    
    def _format_size(self, size_bytes):
        '''格式化文件大小'''
        '__pyarmor_enter_3739__(...)'
        units = [
            'B',
            'KB',
            'MB',
            'GB',
            'TB',
            'PB']
        size = float(size_bytes)
        unit_index = 0
        if size >= 1024 and unit_index < len(units) - 1:
            size /= 1024
            unit_index += 1
            if size >= 1024 and unit_index < len(units) - 1:
                continue
        return f'''{size:.2f} {units[unit_index]}'''
        None(None)
        return None
        '__pyarmor_exit_3740__(...)'
        '__pyarmor_exit_3740__(...)'

    
    def _parse_share(self, share):
        '''解析分享数据'''
        '__pyarmor_enter_3742__(...)'
        create_time = share.get('create_time', 0)
        create_time_str = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(create_time)) if create_time else 'N/A'
        file_size = int(share.get('file_size', 0))
        file_size_str = self._format_size(file_size)
        share_duration = share.get('share_duration', '-1')
        share_url = share.get('share_url', '')
        receive_code = share.get('receive_code', '')
        if share_url and receive_code:
            full_url = f'''{share_url}?password={receive_code}'''
        elif not share_url:
            share_url
        full_url = 'N/A'
        share_title = share.get('share_title', '')
        return {
            '分享大小': file_size_str,
            '分享时间': create_time_str,
            '接收次数': share.get('receive_count', 0),
            '分享有效期': share_duration,
            full_url: '',
            '分享名字': share_title }
        None(None)
        return None
        '__pyarmor_exit_3743__(...)'
        '__pyarmor_exit_3743__(...)'

    
    def fetch_shares(self):
        '''获取所有分享列表'''
        '__pyarmor_enter_3745__(...)'
        logger_strm.info(f'''开始获取用户 {self.user_id} 的分享列表...''')
        shares = []
        offset = 0
        limit = 100
        url = f'''https://webapi.115.com/share/slist?user_id={self.user_id}&offset={offset}&limit={limit}'''
        resp = requests.get(url, cookies = self.cookies, headers = self.headers, timeout = 30)
        resp.raise_for_status()
        data = resp.json()
        if not data.get('state'):
            error_msg = data.get('error', '未知错误')
            logger_strm.error(f'''API 返回错误: {error_msg}''')
            raise Exception(f'''API 返回错误: {error_msg}''')
        items = data.get('list', [])
        if not items:
            pass
        else:
            shares.extend(items)
            logger_strm.info(f'''已获取 {len(shares)} 条分享...''')
            total_count = data.get('count', 0)
            if len(shares) >= total_count:
                pass
            else:
                offset += limit
        logger_strm.info(f'''共获取到 {len(shares)} 条分享''')
        return shares
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def export_to_json_lines(self, shares, include_raw):
        '''导出为 JSON Lines 格式
        
        返回: (parsed_json_str, raw_json_str)
        '''
        '__pyarmor_enter_3748__(...)'
        parsed_lines = []
        for share in shares:
            parsed = self._parse_share(share)
            parsed_lines.append(json.dumps(parsed, ensure_ascii = False))
        parsed_json_str = '\n'.join(parsed_lines)
        raw_json_str = ''
        if include_raw:
            raw_lines = []
            for share in shares:
                raw_lines.append(json.dumps(share, ensure_ascii = False))
            raw_json_str = '\n'.join(raw_lines)
        return (parsed_json_str, raw_json_str)
        None(None)
        return None
        '__pyarmor_exit_3749__(...)'
        '__pyarmor_exit_3749__(...)'

    
    def export_shares(self, include_raw):
        '''导出分享
        
        返回: (success, parsed_json, raw_json, message, count)
        '''
        '__pyarmor_enter_3751__(...)'
        shares = self.fetch_shares()
        if not shares:
            return (True, '', '', '未找到任何分享', 0)
        return (True, '', '', '未找到任何分享', 0)
        (parsed_json, raw_json) = self.export_to_json_lines(shares, include_raw)
        logger_strm.info(f'''导出完成，共 {len(shares)} 条分享''')
        return (True, parsed_json, raw_json, f'''成功导出 {len(shares)} 条分享''', len(shares))
        None(None)
        return None
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_3728__(...)'
    '__pyarmor_exit_3728__(...)'


def export_shares_from_config(config_name, include_raw):
    '''从配置名称导出分享
    
    返回: (success, parsed_json, raw_json, message, count)
    '''
    '__pyarmor_enter_3754__(...)'
    config_manager = config_manager
    import config_manager
    config_115 = config_manager.get_115_config_by_name(config_name)
    if not config_115:
        return (False, '', '', f'''未找到 115 配置: {config_name}''', 0)
    None(None)
    return None
    cookie = config_115.get('cookie', '')
    if not cookie:
        return (False, '', '', '115 配置中未设置 Cookie', 0)
    return (False, '', '', '115 配置中未设置 Cookie', 0)
    exporter = ShareExporter(cookie)
    return exporter.export_shares(include_raw)
    None(None)
    return None
    '__pyarmor_exit_3755__(...)'
    '__pyarmor_exit_3755__(...)'

return None
return None
'__pyarmor_exit_3725__(...)'
'__pyarmor_exit_3725__(...)'
