# File: hdhive_open_client.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: hdhive_open_client.py.1shot.das

'''HDHive Open API 客户端 - 通过 API Key 调用 Open API'''
'__pyarmor_enter_3922__(...)'
import time
import threading
from typing import Optional, Dict, Any, List
import requests as http_requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
from logger import hdhive_logger as logger, logger as sys_logger, logger_subscribe
BASE_URL = 'https://hdhive.com'
OPEN_API_BASE = f'''{BASE_URL}/api/open'''
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36'

class HDHiveOpenClient:
    '''HDHive Open API 客户端 - 使用 API Key 认证'''
    '__pyarmor_enter_3925__(...)'
    
    def __init__(self, api_key, proxy_url):
        '__pyarmor_enter_3928__(...)'
        self.api_key = api_key
        self.session = http_requests.Session()
        self.proxies = {
            'http': proxy_url,
            'https': proxy_url } if proxy_url else { }
        self.session.headers.update({
            'User-Agent': UA,
            'X-API-Key': api_key,
            'Accept': 'application/json' })
        return None
        return None
        '__pyarmor_exit_3929__(...)'
        '__pyarmor_exit_3929__(...)'

    
    def _get(self, path, params, timeout):
        '''Open API GET 请求'''
        '__pyarmor_enter_3931__(...)'
        resp = self.session.get(f'''{OPEN_API_BASE}{path}''', params = params, proxies = self.proxies, verify = False, timeout = timeout)
        return resp.json()
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _post(self, path, data, timeout):
        '''Open API POST 请求'''
        '__pyarmor_enter_3934__(...)'
        if not data:
            data
        resp = self.session.post(f'''{OPEN_API_BASE}{path}''', json = { }, proxies = self.proxies, verify = False, timeout = timeout)
        return resp.json()
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def ping(self):
        '''验证 API Key 有效性'''
        '__pyarmor_enter_3937__(...)'
        return self._get('/ping')
        None(None)
        return None
        '__pyarmor_exit_3938__(...)'
        '__pyarmor_exit_3938__(...)'

    
    def get_me(self):
        '''获取当前用户信息（Premium 专属）'''
        '__pyarmor_enter_3940__(...)'
        return self._get('/me')
        None(None)
        return None
        '__pyarmor_exit_3941__(...)'
        '__pyarmor_exit_3941__(...)'

    
    def get_quota(self):
        '''获取 API 配额信息'''
        '__pyarmor_enter_3943__(...)'
        return self._get('/quota')
        None(None)
        return None
        '__pyarmor_exit_3944__(...)'
        '__pyarmor_exit_3944__(...)'

    
    def get_weekly_free_quota(self):
        '''获取永久 VIP 每周免费解锁配额（Premium 专属）'''
        '__pyarmor_enter_3946__(...)'
        return self._get('/vip/weekly-free-quota')
        None(None)
        return None
        '__pyarmor_exit_3947__(...)'
        '__pyarmor_exit_3947__(...)'

    
    def get_resources(self, media_type, tmdb_id):
        """通过 TMDB ID 获取资源列表
        
        Args:
            media_type: 'movie' 或 'tv'
            tmdb_id: TMDB ID
            
        Returns:
            Open API 响应，data 为资源列表（已含 user 昵称）
        """
        '__pyarmor_enter_3949__(...)'
        if media_type not in ('movie', 'tv'):
            return {
                'success': False,
                'data': [],
                'message': f'''无效的 media_type: {media_type}''' }
        None(None)
        return None
        return self._get(f'''/resources/{media_type}/{tmdb_id}''')
        None(None)
        return None
        '__pyarmor_exit_3950__(...)'
        '__pyarmor_exit_3950__(...)'

    
    def unlock_resource(self, slug):
        '''解锁资源，获取下载链接
        
        Args:
            slug: 资源 slug（32位无横杠UUID）
            
        Returns:
            Open API 响应，data 含 url, access_code, full_url, already_owned
        '''
        '__pyarmor_enter_3952__(...)'
        return self._post('/resources/unlock', {
            'slug': slug })
        None(None)
        return None
        '__pyarmor_exit_3953__(...)'
        '__pyarmor_exit_3953__(...)'

    
    def checkin(self, is_gambler):
        '''每日签到（Premium 专属）
        
        Args:
            is_gambler: 是否赌狗模式
        '''
        '__pyarmor_enter_3955__(...)'
        return self._post('/checkin', {
            'is_gambler': is_gambler })
        None(None)
        return None
        '__pyarmor_exit_3956__(...)'
        '__pyarmor_exit_3956__(...)'

    
    def get_shares(self, page, page_size):
        '''获取我的分享列表'''
        '__pyarmor_enter_3958__(...)'
        return self._get('/shares', {
            'page': page,
            'page_size': page_size })
        None(None)
        return None
        '__pyarmor_exit_3959__(...)'
        '__pyarmor_exit_3959__(...)'

    
    def get_share_detail(self, slug):
        '''获取分享详情'''
        '__pyarmor_enter_3961__(...)'
        return self._get(f'''/shares/{slug}''')
        None(None)
        return None
        '__pyarmor_exit_3962__(...)'
        '__pyarmor_exit_3962__(...)'

    
    def check_resource(self, url):
        '''检查资源链接的网盘类型'''
        '__pyarmor_enter_3964__(...)'
        return self._post('/check/resource', {
            'url': url })
        None(None)
        return None
        '__pyarmor_exit_3965__(...)'
        '__pyarmor_exit_3965__(...)'

    return None
    return None
    '__pyarmor_exit_3926__(...)'
    '__pyarmor_exit_3926__(...)'

_open_client_cache = { }
_open_client_cache_lock = threading.Lock()
_OPEN_CLIENT_CACHE_TTL = 3600

def get_open_client(account_name, api_key, proxy_url):
    '''获取或创建缓存的 Open API 客户端实例'''
    '__pyarmor_enter_3967__(...)'
    if not api_key:
        return None
    return None
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_3923__(...)'
'__pyarmor_exit_3923__(...)'
