# File: media_info_builder.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: media_info_builder.py.1shot.das

'''媒体信息构建模块 - 基于名称解析结果构建标准化媒体信息字典'''
'__pyarmor_enter_4048__(...)'
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
from nameparser.parser import parse_title, recognize_path
from nameparser.utils import MediaType
from transfer_naming import render_rename_preview

def _tmdb_original_image(path):
    '__pyarmor_enter_4051__(...)'
    if not path:
        return ''
    return ''
    image_path = str(path).strip()
    if not image_path:
        return ''
    return ''
    if image_path.startswith('http://') or image_path.startswith('https://'):
        return re.sub('/t/p/[^/]+/', '/t/p/original/', image_path)
    None(None)
    return None
    if image_path.startswith('/'):
        return f'''https://image.tmdb.org/t/p/original{image_path}'''
    None(None)
    return None
    return image_path
    None(None)
    return None
    '__pyarmor_exit_4052__(...)'
    '__pyarmor_exit_4052__(...)'


def _media_type_value(media_type):
    '__pyarmor_enter_4054__(...)'
    if hasattr(media_type, 'value'):
        return media_type.value
    None(None)
    return None
    if media_type == 'movie':
        return MediaType.MOVIE.value
    None(None)
    return None
    if media_type == 'tv':
        return MediaType.TV.value
    None(None)
    return None
    if media_type in (MediaType.MOVIE.value, MediaType.TV.value, MediaType.UNKNOWN.value):
        return media_type
    None(None)
    return None
    return None
    return None
    '__pyarmor_exit_4055__(...)'
    '__pyarmor_exit_4055__(...)'


def build_media_info(meta):
    '__pyarmor_enter_4057__(...)'
    if not getattr(meta, '_tmdb_raw_info', None):
        getattr(meta, '_tmdb_raw_info', None)
    tmdb_raw = { }
    if not _media_type_value(tmdb_raw.get('media_type')):
        _media_type_value(tmdb_raw.get('media_type'))
    media_type = meta.type.value if meta.type else None
    if not tmdb_raw.get('title'):
        tmdb_raw.get('title')
        if not tmdb_raw.get('name'):
            tmdb_raw.get('name')
            if not meta.name:
                meta.name
    title = ''
    year = ''
    if tmdb_raw.get('release_date'):
        year = str(tmdb_raw.get('release_date'))[:4]
    elif tmdb_raw.get('first_air_date'):
        year = str(tmdb_raw.get('first_air_date'))[:4]
    elif getattr(meta, 'year', None):
        year = str(meta.year)
    if not tmdb_raw.get('id'):
        tmdb_raw.get('id')
    tmdb_id = meta.tmdbid
    if not tmdb_raw.get('external_ids'):
        tmdb_raw.get('external_ids')
    external_ids = { }
    if not tmdb_raw.get('imdb_id'):
        tmdb_raw.get('imdb_id')
        if not external_ids.get('imdb_id'):
            external_ids.get('imdb_id')
            if not meta.imdbid:
                meta.imdbid
    imdb_id = ''
    if not tmdb_raw.get('tvdb_id'):
        tmdb_raw.get('tvdb_id')
    tvdb_id = external_ids.get('tvdb_id')
    if not tmdb_raw.get('credits'):
        tmdb_raw.get('credits')
    credits = { }
    if not credits.get('cast'):
        credits.get('cast')
# WARNING: Decompyle incomplete


def build_applied_rules(meta):
    '__pyarmor_enter_4060__(...)'
    applied_rules = []
    if meta.apply_words:
        for word in meta.apply_words:
            applied_rules.append({
                'type': '识别词',
                'rule': word })
    if getattr(meta, 'resource_team', None):
        GroupMatcher = GroupMatcher
        import nameparser.matchers
        if GroupMatcher().is_list_matched(meta.resource_team):
            applied_rules.append({
                'type': '制作组',
                'rule': meta.resource_team })
    if getattr(meta, 'custom_capture', None):
        applied_rules.append({
            'type': '自定义捕获词',
            'rule': meta.custom_capture })
    return applied_rules
    None(None)
    return None
    '__pyarmor_exit_4061__(...)'
    '__pyarmor_exit_4061__(...)'


def build_torrent_info(meta):
    '__pyarmor_enter_4063__(...)'
    if not getattr(meta, 'resource_pix', None):
        getattr(meta, 'resource_pix', None)
    if not getattr(meta, 'resource_effect', None):
        getattr(meta, 'resource_effect', None)
    if not getattr(meta, 'resource_type', None):
        getattr(meta, 'resource_type', None)
    if not getattr(meta, 'resource_team', None):
        getattr(meta, 'resource_team', None)
    if not getattr(meta, 'video_encode', None):
        getattr(meta, 'video_encode', None)
    if not getattr(meta, 'audio_encode', None):
        getattr(meta, 'audio_encode', None)
    if not getattr(meta, 'fps', None):
        getattr(meta, 'fps', None)
    if not getattr(meta, 'bit_depth', None):
        getattr(meta, 'bit_depth', None)
    if not getattr(meta, 'web_source', None):
        getattr(meta, 'web_source', None)
    if not getattr(meta, 'custom_capture', None):
        getattr(meta, 'custom_capture', None)
    if not getattr(meta, 'part', None):
        getattr(meta, 'part', None)
    return {
        'resolution': '',
        'effect': '',
        'resource_type': '',
        'release_group': '',
        'video_codec': '',
        'audio_codec': '',
        'frame_rate': '',
        'bit_depth': '',
        'web_source': '',
        'custom_capture': '',
        'part': '' }
    None(None)
    return None
    '__pyarmor_exit_4064__(...)'
    '__pyarmor_exit_4064__(...)'


def build_recognize_result(meta, original_name, config, include_internal, custom_post_render_words):
    '__pyarmor_enter_4066__(...)'
    media_info = build_media_info(meta)
    if not getattr(meta, '_recognize_diagnostics', None):
        getattr(meta, '_recognize_diagnostics', None)
    diagnostics = { }
    warnings = []
    result = {
        'meta_info': meta.to_dict(),
        'torrent_info': build_torrent_info(meta),
        'media_info': media_info,
        'applied_rules': build_applied_rules(meta) }
    if diagnostics:
        result['diagnostics'] = diagnostics
    rename_preview = render_rename_preview(meta = meta, media_info = media_info, original_name = original_name, config = config, custom_post_render_words = custom_post_render_words)
    result['rename_preview'] = rename_preview
# WARNING: Decompyle incomplete


def recognize_media(title, path, subtitle, force_gpt, skip_tmdb, custom_identifiers, custom_release_groups, custom_captures, custom_post_render_words, config, include_internal):
    '__pyarmor_enter_4069__(...)'
    if path:
        path_text = str(path).strip()
        if not path_text:
            return None
        return None
        meta = recognize_path(path = path_text, subtitle = subtitle, force_gpt = force_gpt, skip_tmdb = skip_tmdb, custom_identifiers = custom_identifiers, custom_release_groups = custom_release_groups, custom_captures = custom_captures)
        if not meta:
            return None
        return None
        if not Path(path_text).name:
            Path(path_text).name
        original_name = path_text
    elif not title:
        title
    normalized_title = str('').strip()
    if not normalized_title:
        return None
    return None
    meta = parse_title(title = normalized_title, subtitle = subtitle, force_gpt = force_gpt, skip_tmdb = skip_tmdb, custom_identifiers = custom_identifiers, custom_release_groups = custom_release_groups, custom_captures = custom_captures)
    original_name = normalized_title
    return build_recognize_result(meta = meta, original_name = original_name, config = config, include_internal = include_internal, custom_post_render_words = custom_post_render_words)
    None(None)
    return None
    '__pyarmor_exit_4070__(...)'
    '__pyarmor_exit_4070__(...)'


def apply_recognize_result(target, recognize_result, overwrite):
    '__pyarmor_enter_4072__(...)'
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_4049__(...)'
'__pyarmor_exit_4049__(...)'
