# File: organize_cd2.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: organize_cd2.py.1shot.das

__doc__ = 'CloudDrive2 文件整理模块 - 基于 python-clouddrive2==2.0.8.1.2\n\nAPI:\n- MoveFile(theFilePaths[], destPath)  原生批量移动\n- CopyFile(theFilePaths[], destPath)  原生批量复制\n- RenameFile(theFilePath, newName)    重命名\n- RenameFiles(renameFiles[])           原生批量重命名\n- fs.makedirs / fs.remove / fs.listdir_attr  目录与文件操作\n- 所有写操作失败自动重试一次\n'
'__pyarmor_enter_6499__(...)'
from pathlib import Path
from time import sleep
from typing import Dict, Any, List, Optional
from logger import hdhive_logger as logger
from config_manager import config_manager
from clouddrive import CloudDriveClient, CloudDriveFileSystem

class OrganizeCD2:
    '''CloudDrive2 文件整理器'''
    '__pyarmor_enter_6502__(...)'
    
    def __init__(self, address, username, password):
        '__pyarmor_enter_6505__(...)'
    # WARNING: Decompyle incomplete

    
    def _get_client(self, force_new):
        '__pyarmor_enter_6508__(...)'
    # WARNING: Decompyle incomplete

    
    def _get_fs(self, force_new):
        '__pyarmor_enter_6511__(...)'
        self._get_client(force_new)
        return self._fs
        None(None)
        return None
        '__pyarmor_exit_6512__(...)'
        '__pyarmor_exit_6512__(...)'

    
    def close(self):
        '__pyarmor_enter_6514__(...)'
        self._client = None
        self._fs = None
        return None
        return None
        '__pyarmor_exit_6515__(...)'
        '__pyarmor_exit_6515__(...)'

    
    def test_connection(self):
        '__pyarmor_enter_6517__(...)'
        client = self._get_client()
        client.FindFileByPath({
            'path': '/' })
        return {
            'success': True,
            'message': '连接成功' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def list_dir(self, path):
        '__pyarmor_enter_6520__(...)'
        items = []
        fs = self._get_fs()
        for attr in fs.listdir_attr(path):
            if not attr.get('fullPathName', ''):
                attr.get('fullPathName', '')
            items.append({
                'name': attr.get('name', ''),
                'path': attr.get('path', ''),
                'is_dir': bool(attr.get('isDirectory', False)),
                'size': int(0) if not attr.get('isDirectory') else 0 })
        return items
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def ensure_dir(self, path):
        '__pyarmor_enter_6523__(...)'
        self._get_fs().makedirs(path, exist_ok = True)
        return {
            'success': True,
            'message': '目录就绪' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def move_files(self, source_paths, target_dir):
        '__pyarmor_enter_6526__(...)'
        for attempt in range(2):
            client = self._get_client(force_new = attempt > 0)
            result = client.MoveFile({
                'theFilePaths': source_paths,
                'destPath': target_dir })
            if not result.success:
                raise ValueError(f'''MoveFile 失败: {result.errorMessage}''')
            
            return range(2), {
                'success': True,
                'message': f'''批量移动成功: {len(source_paths)} 个文件''' }
            None(None)
            return None
        return {
            'success': False,
            'message': '批量移动失败(已重试)' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def copy_files(self, source_paths, target_dir):
        '__pyarmor_enter_6529__(...)'
        for attempt in range(2):
            client = self._get_client(force_new = attempt > 0)
            result = client.CopyFile({
                'theFilePaths': source_paths,
                'destPath': target_dir })
            if not result.success:
                raise ValueError(f'''CopyFile 失败: {result.errorMessage}''')
            
            return range(2), {
                'success': True,
                'message': f'''批量复制成功: {len(source_paths)} 个文件''' }
            None(None)
            return None
        return {
            'success': False,
            'message': '批量复制失败(已重试)' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def rename_file(self, file_path, new_name):
        '__pyarmor_enter_6532__(...)'
        for attempt in range(2):
            client = self._get_client(force_new = attempt > 0)
            result = client.RenameFile({
                'theFilePath': file_path,
                'newName': new_name })
            if not result.success:
                raise ValueError(f'''RenameFile 失败: {result.errorMessage}''')
            
            return range(2), {
                'success': True,
                'message': '重命名成功' }
            None(None)
            return None
        return {
            'success': False,
            'message': '重命名失败(已重试)' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def batch_rename(self, rename_map):
        '''批量重命名文件

        Args:
            rename_map: {cd2_file_path: new_name} 字典

        Returns:
            {success, message}
        '''
        '__pyarmor_enter_6535__(...)'
        if not rename_map:
            return {
                'success': True,
                'message': '无需重命名' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def delete_file(self, file_path):
        '__pyarmor_enter_6538__(...)'
        for attempt in range(2):
            self._get_fs(force_new = attempt > 0).remove(file_path)
            
            return range(2), {
                'success': True,
                'message': '删除成功' }
            None(None)
            return None
        return {
            'success': False,
            'message': '删除失败(已重试)' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def local_to_cd2_path(self, local_path, root_dir):
        '__pyarmor_enter_6541__(...)'
        relative = Path(local_path).resolve().relative_to(Path(root_dir).resolve())
        return '/' + str(relative)
        None(None)
        return None
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_6503__(...)'
    '__pyarmor_exit_6503__(...)'

_cd2_instance: Optional[OrganizeCD2] = None
_cd2_config_hash: Optional[str] = None

def get_organize_cd2(config):
    '__pyarmor_enter_6544__(...)'
    cd2_config = config_manager.get_cd2_config()
    if not cd2_config.get('address'):
        cd2_config.get('address')
    address = str('').strip()
    if not cd2_config.get('username'):
        cd2_config.get('username')
    username = str('').strip()
    if not cd2_config.get('password'):
        cd2_config.get('password')
    password = str('')
    if not address and username or password:
        return None
    return None
    config_hash = f'''{address}|{username}|{password}'''
# WARNING: Decompyle incomplete

return None
return None
# WARNING: Decompyle incomplete
