# File: organize_115.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: organize_115.py.1shot.das

'''115 文件整理模块 - 通过 115 API 进行批量移动/复制/重命名操作

- RateLimiter 限流器: 防止 API 频繁调用导致 115 风控
- IdPathCache 路径缓存: 减少重复目录查询 API 请求
- 交替 app/non-app API 调用: 降低风控风险
- 失败重试机制: 增强操作稳定性
'''
'__pyarmor_enter_6442__(...)'
from pathlib import Path, PurePosixPath
from time import sleep
from typing import Dict, Any, List, Optional
from p115client import P115Client, check_response
from p115client.tool.edit import update_name
from logger import hdhive_logger as logger
from organize_utils import RateLimiter, IdPathCache
from ua import ShareP115Client, UserAgentUtils
from config_manager import config_manager
_rate_limiter = RateLimiter(max_calls = 2, time_window = 1, name = '115-organize')

class Organize115:
    '''115 网盘文件整理器

    用于文件整理场景的 115 批量操作，包括移动、复制、重命名、删除、
    目录列表、路径解析和目录创建等功能。

    增强特性:
    - 交替使用 app=True / app=False 调用方式降低风控
    - 所有 API 调用经过 RateLimiter 限流
    - 目录路径与 CID 双向缓存
    - 操作失败时自动重试（最多1次）
    '''
    '__pyarmor_enter_6445__(...)'
    
    def __init__(self, cookie):
        '__pyarmor_enter_6448__(...)'
        self.cookie = cookie
        self.client = ShareP115Client(cookie, check_for_relogin = True)
        self._path_cache = IdPathCache(maxsize = 512, ttl = 1800)
        self._call_count = 0
        return None
        return None
        '__pyarmor_exit_6449__(...)'
        '__pyarmor_exit_6449__(...)'

    
    def _get_ua_kwargs(self, use_app):
        '''获取 UA 参数，交替使用 app/non-app 模式降低风控'''
        '__pyarmor_enter_6451__(...)'
    # WARNING: Decompyle incomplete

    
    def _rate_limited_call(self, func, *args, **kwargs):
        '''经过限流器的 API 调用'''
        '__pyarmor_enter_6454__(...)'
        _rate_limiter.acquire()
    # WARNING: Decompyle incomplete

    
    def list_dir_files(self, cid, limit):
        '''列出指定目录下的所有文件和文件夹

        返回列表中的每个项包含: n(名称), fid(文件ID), cid(目录ID), ico(类型), s(大小) 等
        目录项有 cid 字段, 文件项有 fid 字段

        Returns:
            成功时返回 list（可能为空），API 失败时返回 None
        '''
        '__pyarmor_enter_6457__(...)'
        all_items = []
        offset = 0
        ua_kwargs = self._get_ua_kwargs()
    # WARNING: Decompyle incomplete

    
    def find_item_in_dir(self, parent_cid, name):
        '''在指定目录中查找文件或文件夹

        返回找到的项的信息字典, 未找到返回 None
        '''
        '__pyarmor_enter_6460__(...)'
        items = self.list_dir_files(parent_cid)
    # WARNING: Decompyle incomplete

    
    def find_item_in_dir_cached(self, parent_cid, name):
        '''带缓存的目录查找: 先检查缓存中是否有对应路径的CID'''
        '__pyarmor_enter_6463__(...)'
        parent_path = self._path_cache.get_dir_by_id(int(parent_cid)) if parent_cid.isdigit() else None
    # WARNING: Decompyle incomplete

    
    def resolve_cloud_path(self, relative_path, root_cid):
        """解析相对云端路径到文件/文件夹信息

        Args:
            relative_path: 相对于 root_cid 的路径, 如 'Movies/Title (2024)/video.mkv'
            root_cid: 起始目录 CID

        Returns:
            找到的文件/文件夹信息, 未找到返回 None
        """
        '__pyarmor_enter_6466__(...)'
        parts = PurePosixPath(relative_path).parts
        if not parts:
            return {
                'cid': root_cid,
                'n': '',
                'is_dir': True }
        None(None)
        return None
        current_cid = root_cid
        current_item = None
        for i, part in enumerate(parts):
            found = self.find_item_in_dir(current_cid, part)
            if not found:
                enumerate(parts)
                return None
            enumerate(parts)
            return None
            current_item = found
            if not i < len(parts) - 1:
                continue
            item_cid = str(found.get('cid', ''))
            if not item_cid:
                return None
            return None
            current_cid = item_cid
        return current_item
        None(None)
        return None
        '__pyarmor_exit_6467__(...)'
        '__pyarmor_exit_6467__(...)'

    
    def ensure_cloud_dir(self, relative_path, root_cid):
        '''确保云端目录路径存在, 不存在则创建

        优先从缓存查找已知目录CID，减少 API 调用次数。

        Args:
            relative_path: 相对于 root_cid 的目录路径
            root_cid: 起始目录 CID

        Returns:
            {success, cid, message}
        '''
        '__pyarmor_enter_6469__(...)'
        parts = PurePosixPath(relative_path).parts
        if not parts:
            return {
                'success': True,
                'cid': root_cid,
                'message': '根目录' }
        None(None)
        return None
        current_cid = root_cid
        current_path_parts = []
        root_path = self._path_cache.get_dir_by_id(int(root_cid)) if root_cid.isdigit() else None
    # WARNING: Decompyle incomplete

    
    def _create_folder(self, parent_cid, folder_name):
        '''在网盘中创建文件夹，返回 {success, cid, message}

        带重试机制: 首次失败时切换 app 模式重试一次
        '''
        '__pyarmor_enter_6472__(...)'
    # WARNING: Decompyle incomplete

    
    def move_files(self, file_ids, target_cid):
        '''批量移动文件到目标目录

        带重试机制: 首次失败时切换 app 模式重试一次

        Args:
            file_ids: 文件ID列表
            target_cid: 目标目录 CID

        Returns:
            {success, message}
        '''
        '__pyarmor_enter_6475__(...)'
    # WARNING: Decompyle incomplete

    
    def copy_files(self, file_ids, target_cid):
        '''批量复制文件到目标目录

        带重试机制: 首次失败时切换 app 模式重试一次

        Args:
            file_ids: 文件ID列表
            target_cid: 目标目录 CID

        Returns:
            {success, message}
        '''
        '__pyarmor_enter_6478__(...)'
    # WARNING: Decompyle incomplete

    
    def rename_file(self, file_id, new_name):
        '''重命名单个文件

        带重试机制: 首次失败时切换 app 模式重试一次
        '''
        '__pyarmor_enter_6481__(...)'
    # WARNING: Decompyle incomplete

    
    def batch_rename(self, rename_map):
        '''批量重命名文件

        带重试机制: 首次失败时切换 app 模式重试一次

        Args:
            rename_map: {file_id: new_name} 字典

        Returns:
            {success, message}
        '''
        '__pyarmor_enter_6484__(...)'
        if not rename_map:
            return {
                'success': True,
                'message': '无需重命名' }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def delete_files(self, file_ids):
        '''批量删除文件

        带重试机制: 首次失败时切换 app 模式重试一次

        Args:
            file_ids: 文件ID列表

        Returns:
            {success, message}
        '''
        '__pyarmor_enter_6487__(...)'
    # WARNING: Decompyle incomplete

    
    def get_file_id_from_local_path(self, local_path, cloud_path_prefix, cloud_root_cid):
        '''从本地路径解析出 115 文件 ID

        Args:
            local_path: 本地文件路径 (115 挂载路径)
            cloud_path_prefix: 本地挂载根路径 (如 /mnt/115)
            cloud_root_cid: 对应的 115 云端根目录 CID

        Returns:
            文件 ID 或 None
        '''
        '__pyarmor_enter_6490__(...)'
        local = Path(local_path).resolve()
        prefix = Path(cloud_path_prefix).resolve()
        relative = local.relative_to(prefix)
        item = self.resolve_cloud_path(str(relative), cloud_root_cid)
        if not item:
            return None
        return None
        if not item.get('fid'):
            item.get('fid')
            if not item.get('cid'):
                item.get('cid')
        return str('')
        None(None)
        return None
    # WARNING: Decompyle incomplete

    get_cloud_relative_path = (lambda local_path, cloud_path_prefix: '__pyarmor_enter_6493__(...)'local = Path(local_path).resolve()prefix = Path(cloud_path_prefix).resolve()str(local.relative_to(prefix))None(None)None# WARNING: Decompyle incomplete
)()
    return None
    staticmethod
    return None
    '__pyarmor_exit_6446__(...)'
    '__pyarmor_exit_6446__(...)'

_115_instance: Optional[Organize115] = None
_115_config_hash: Optional[str] = None

def get_organize_115(config):
    '''获取用于文件整理的 115 操作器（带缓存）

    相同 cookie 配置下复用实例，避免重复创建客户端。
    实例内部的路径缓存和限流器也随之复用。

    Args:
        config: 文件整理配置, 需包含 use_115_config 字段

    Returns:
        Organize115 实例或 None
    '''
    '__pyarmor_enter_6496__(...)'
    if not config:
        config
    if not { }.get('use_115_config'):
        { }.get('use_115_config')
    config_name = str('').strip()
    if not config_name:
        logger.warning('文件整理 115 模式未配置 use_115_config')
        return None
    return None
    config_115 = config_manager.get_115_config_by_name(config_name)
    if not config_115:
        logger.warning(f'''文件整理 115 模式找不到 115 配置: {config_name}''')
        return None
    return None
    cookie = config_115.get('cookie', '')
    if not cookie:
        logger.warning(f'''文件整理 115 配置缺少 cookie: {config_name}''')
        return None
    return None
    config_hash = f'''{config_name}|{cookie[:32]}'''
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_6443__(...)'
'__pyarmor_exit_6443__(...)'
