# File: pickcode_302.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: pickcode_302.py.1shot.das

'''115 Pickcode 模式直链获取模块'''
'__pyarmor_enter_4339__(...)'
import re
from typing import Optional
from orjson import loads
from p115rsacipher import encrypt, decrypt
from config_manager import config_manager
from logger import logger_302 as logger

def parse_cookies(cookie_str):
    '''解析cookie'''
    '__pyarmor_enter_4342__(...)'
    cookies = { }
    for item in cookie_str.split(';'):
        if not '=' in item:
            continue
        (key, value) = item.strip().split('=', 1)
        cookies[key] = value
    return cookies
    None(None)
    return None
    '__pyarmor_exit_4343__(...)'
    '__pyarmor_exit_4343__(...)'


def extract_pickcode_from_url(url):
    '''从 URL 中提取 pickcode
    
    支持格式:
    - http://xxx/?pickcode=azlr1dfzv9oudhfzy/文件名.mp4
    - http://xxx/?pickcode=azlr1dfzv9oudhfzy&其他参数
    - pickcode=azlr1dfzv9oudhfzy
    - http://xxx/d/abchrb6gnrw0hhh80
    - http://xxx/d/abchrb6gnrw0hhh80?/文件名.mkv
    - http://xxx/d/abchrb6gnrw0hhh80.mkv?/文件名.mkv
    - http://xxx/play115/{pickcode}/{file_id}/{sha1}/{file_size}/{filename}
    '''
    '__pyarmor_enter_4345__(...)'
    match = re.search('pickcode=([a-zA-Z0-9]+)', url)
    if match:
        return match.group(1)
    None(None)
    return None
    match = re.search('/d/([a-zA-Z0-9]+)(?:\\.[a-zA-Z0-9]+)?(?:\\?|$)', url)
    if match:
        return match.group(1)
    None(None)
    return None
    match = re.search('/play115/([a-zA-Z0-9]+)/', url)
    if match:
        return match.group(1)
    None(None)
    return None
    return None
    return None
    '__pyarmor_exit_4346__(...)'
    '__pyarmor_exit_4346__(...)'


def get_download_url_by_pickcode(pickcode, config_name, user_agent, use_open):
    '''通过 pickcode 获取下载链接
    
    Args:
        pickcode: 115 文件的 pickcode
        config_name: 115 配置名称
        user_agent: 用户代理字符串
        use_open: 是否使用 Open API
    
    Returns:
        下载链接或 None
    '''
    '__pyarmor_enter_4348__(...)'
    import time
    import httpx
    start_time = time.time()
    config_115 = config_manager.get_115_config_by_name(config_name)
    if not config_115:
        logger.error(f'''未找到 115 配置: {config_name}''')
        return None
    return None
    if use_open:
        get_open_client_from_config = get_open_client_from_config
        import open_client
        open_client = get_open_client_from_config(config_115)
        if not open_client:
            logger.error(f'''[115 open] 115 配置 {config_name} 未绑定 Open Token''')
            return None
        return None
        file_url = open_client.get_download_url_str(pickcode, user_agent = user_agent)
        if not file_url:
            logger.error('[115 open] Pickcode 获取下载链接失败')
            return None
        return None
        end_time = time.time()
        logger.success(f'''[115 open] Pickcode 模式获取下载链接成功，耗时: {end_time - start_time:.3f}s''')
        return file_url
    None(None)
    return None
    cookie = config_115.get('cookie', '')
    if not cookie:
        logger.error(f'''[115 cookie] 115 配置 {config_name} 未设置 cookie''')
        return None
    return None
    cookies = parse_cookies(cookie)
    headers = {
        'User-Agent': user_agent } if user_agent else { }
    payload = f'''{{"pick_code":"{pickcode}"}}'''
    encrypted_data = encrypt(payload).decode('utf-8')
    resp = httpx.post('http://proapi.115.com/android/2.0/ufile/download', data = {
        'data': encrypted_data }, headers = headers, cookies = cookies, follow_redirects = True, timeout = 10)
    if resp.status_code != 200:
        logger.error(f'''[115 cookie] 请求失败: HTTP {resp.status_code}''')
        return None
    return None
    json_data = loads(resp.content)
    if not json_data.get('state'):
        error_msg = json_data.get('error', json_data.get('msg', '未知错误'))
        logger.error(f'''[115 cookie] 获取下载链接失败: {error_msg}''')
        return None
    return None
    decrypted_data = loads(decrypt(json_data['data']))
    url = decrypted_data.get('url')
    if not url:
        logger.error('[115 cookie] 响应中没有下载链接')
        return None
    return None
    end_time = time.time()
    logger.success(f'''[115 cookie] Pickcode 模式获取下载链接成功，耗时: {end_time - start_time:.3f}s''')
    return url
    None(None)
    return None
# WARNING: Decompyle incomplete


def get_direct_link_from_pickcode(source_file, config_name, user_agent, use_open):
    '''从包含 pickcode 的源文件路径获取直链
    
    Args:
        source_file: 包含 pickcode 参数的源文件路径
        config_name: 115 配置名称
        user_agent: 用户代理字符串
    
    Returns:
        下载链接或 None
    '''
    '__pyarmor_enter_4351__(...)'
    logger.info('Pickcode 模式')
    pickcode = extract_pickcode_from_url(source_file)
    if not pickcode:
        logger.error(f'''无法从源文件中提取 pickcode: {source_file}''')
        return None
    return None
    logger.debug(f'''提取到 pickcode: {pickcode}''')
    return get_download_url_by_pickcode(pickcode, config_name, user_agent, use_open = use_open)
    None(None)
    return None
    '__pyarmor_exit_4352__(...)'
    '__pyarmor_exit_4352__(...)'

return None
return None
'__pyarmor_exit_4340__(...)'
'__pyarmor_exit_4340__(...)'
