# File: precache.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: precache.py.1shot.das

'''预缓存模块 - 在用户进入详情页时提前获取下载链接'''
'__pyarmor_enter_4306__(...)'
import random
import re
import threading
import time
import requests as http_requests
from config_manager import config_manager
from cache_manager import cache_manager
from emby import EmbyManager
from logger import logger_302 as logger

class PrecacheManager:
    '''预缓存管理器'''
    '__pyarmor_enter_4309__(...)'
    _instance = None
    _lock = threading.Lock()
    _active_tasks = set()
    _active_tasks_lock = threading.Lock()
    _last_request_time = { }
    _debounce_lock = threading.Lock()
    _DEBOUNCE_INTERVAL = 1
    
    def __new__(cls):
        '__pyarmor_enter_4312__(...)'
    # WARNING: Decompyle incomplete

    
    def _format_episode_name(self, ep_item, series_name):
        '''格式化剧集显示名称: 剧名 S01E02 集名'''
        '__pyarmor_enter_4315__(...)'
        if not ep_item.get('SeriesName', ''):
            ep_item.get('SeriesName', '')
        s_name = series_name
        season_num = ep_item.get('ParentIndexNumber')
        ep_num = ep_item.get('IndexNumber')
        ep_name = ep_item.get('Name', '')
        parts = []
        if s_name:
            parts.append(s_name)
    # WARNING: Decompyle incomplete

    
    def _is_precache_enabled(self, config_id, media_type, emby_user_id):
        """检查预缓存是否启用
        
        Args:
            config_id: 配置 ID（emby_xxx 或 ft_xxx）
            media_type: 'Movie' 或 'Series'/'Episode'
            emby_user_id: Emby 用户 ID（用于用户级筛选）
            
        Returns:
            bool
        """
        '__pyarmor_enter_4318__(...)'
        if config_id:
            config_id
        is_ft = config_id.startswith('ft_')
        if is_ft:
            cfg = config_manager.get_fast_transfer_config(config_id)
        else:
            cfg = config_manager.get_emby_config(config_id)
        if not cfg:
            return False
        return False
        if not cfg.get('enabled', True):
            return False
        return False
        if not cfg.get('precache_enabled', False):
            return False
        return False
        if media_type in ('Movie',):
            type_enabled = cfg.get('precache_movie_enabled', False)
        elif media_type in ('Series', 'Episode', 'Season'):
            type_enabled = cfg.get('precache_series_enabled', False)
        else:
            return False
        return False
        if not type_enabled:
            return False
        return False
        precache_user_ids = cfg.get('precache_user_ids', [])
        if not precache_user_ids:
            return True
        return True
        if not emby_user_id:
            return True
        return True
        return emby_user_id in precache_user_ids
        None(None)
        return None
        '__pyarmor_exit_4319__(...)'
        '__pyarmor_exit_4319__(...)'

    
    def _is_precache_enabled_for_user(self, config_id, emby_user_id, media_type):
        """检查特定用户的预缓存是否启用（秒传播放模式）
        
        对于秒传播放：
        - 共享账号模式：遵循总开关的子开关
        - 非共享模式：检查每个用户的 precache_movie / precache_series 开关
        
        Args:
            config_id: 秒传配置 ID
            emby_user_id: Emby 用户 ID
            media_type: 'Movie' 或 'Series'/'Episode'
        """
        '__pyarmor_enter_4321__(...)'
        cfg = config_manager.get_fast_transfer_config(config_id)
        if not cfg:
            return False
        return False
        if not cfg.get('enabled', True):
            return False
        return False
        if not cfg.get('precache_enabled', False):
            return False
        return False
        if cfg.get('shared_account_enabled', False):
            if media_type in ('Movie',):
                return cfg.get('precache_movie_enabled', False)
            None(None)
            return None
        if media_type in ('Series', 'Episode', 'Season'):
            return cfg.get('precache_series_enabled', False)
        None(None)
        return None
        return False
        return False
        emby_user_configs = cfg.get('emby_user_configs', [])
        for user_cfg in emby_user_configs:
            cfg_user_ids = user_cfg.get('emby_user_ids', [])
            if cfg_user_ids and user_cfg.get('emby_user_id'):
                cfg_user_ids = [
                    user_cfg['emby_user_id']]
            if not emby_user_id in cfg_user_ids:
                continue
            if media_type in ('Movie',):
                if cfg.get('precache_movie_enabled', False):
                    cfg.get('precache_movie_enabled', False)
                
                return emby_user_configs, user_cfg.get('precache_movie', False)
            None(emby_user_configs)
            return None
            if media_type in ('Series', 'Episode', 'Season'):
                if cfg.get('precache_series_enabled', False):
                    cfg.get('precache_series_enabled', False)
                
                return None, user_cfg.get('precache_series', False)
            None(None)
            return None
            return False
            return False
        return False
        return False
        '__pyarmor_exit_4322__(...)'
        '__pyarmor_exit_4322__(...)'

    
    def handle_detail_request(self, config_id, item_id, emby_user_id, request_headers):
        '''处理详情页请求，触发预缓存
        
        从 Caddy 拦截的详情页请求进入此方法。
        
        Args:
            config_id: 配置 ID（emby_xxx 或 ft_xxx）
            item_id: Emby 项目 ID
            emby_user_id: 从 URL 中提取的 Emby 用户 ID
            request_headers: 请求头字典
        '''
        '__pyarmor_enter_4324__(...)'
        if not config_id or item_id:
            return None
        return None
        debounce_key = f'''{config_id}:{item_id}:{emby_user_id}'''
        now = time.time()
    # WARNING: Decompyle incomplete

    
    def _do_precache(self, config_id, item_id, emby_user_id, user_agent, host, emby_token, emby_device_id, task_key):
        '''执行预缓存逻辑（在后台线程中运行）'''
        '__pyarmor_enter_4327__(...)'
        if config_id:
            config_id
        is_ft = config_id.startswith('ft_')
        emby_manager = EmbyManager(config_id)
        server = emby_manager.server
        api_key = emby_manager.api_key
    # WARNING: Decompyle incomplete

    
    def _precache_item(self, config_id, item_id, item_name, media_sources, emby_manager, user_agent, host, emby_user_id, emby_user_name, is_ft, version_count):
        '''预缓存单个项目
        
        Args:
            version_count: 缓存版本数，0 表示全部缓存
        '''
        '__pyarmor_enter_4330__(...)'
        if not media_sources:
            return None
        return None
        total_versions = len(media_sources)
        sources_to_cache = list(media_sources)
        if version_count > 0 and len(sources_to_cache) > version_count:
            sources_to_cache = random.sample(sources_to_cache, version_count)
            logger.info(f'''[预缓存] {item_name} 共 {total_versions} 个版本，随机选取 {version_count} 个缓存''')
        elif total_versions > 1:
            logger.info(f'''[预缓存] {item_name} 共 {total_versions} 个版本，全部缓存''')
        import time as time_module
        start_time = time_module.time()
        cached_count = 0
        skipped_count = 0
        failed_count = 0
        for idx, media_source in enumerate(sources_to_cache):
            source_file = media_source.get('Path', '')
            media_source_id = media_source.get('Id', '')
            version_name = media_source.get('Name', '')
            if not source_file:
                continue
            display_name = item_name
            if total_versions > 1:
                version_label = version_name if version_name else f'''版本{idx + 1}'''
                display_name = f'''{item_name} [{version_label}]'''
            if emby_manager.should_local_proxy(source_file):
                skipped_count += 1
                continue
            is_share = emby_manager.is_share_link(source_file)
            is_pickcode = emby_manager.is_pickcode_link(source_file)
            is_123_strm = emby_manager.is_123_strm_link(source_file)
            is_ed2k = emby_manager.is_ed2k_link(source_file)
            is_path = emby_manager.is_local_path(source_file)
            if cached:
                skipped_count += 1
                continue
            if success:
                cached_count += 1
                continue
            failed_count += 1
        elapsed = time_module.time() - start_time
        if total_versions > 1:
            if failed_count > 0 and cached_count == 0:
                logger.warning(f'''[预缓存] 预缓存失败: {item_name}，共 {total_versions} 个版本，全部失败（跳过 {skipped_count} 个已缓存），耗时: {elapsed:.3f}s''')
            elif failed_count > 0:
                logger.warning(f'''[预缓存] 预缓存部分失败: {item_name}，共 {total_versions} 个版本，成功 {cached_count} 个，失败 {failed_count} 个（跳过 {skipped_count} 个已缓存），耗时: {elapsed:.3f}s''')
            else:
                logger.info(f'''[预缓存] 预缓存完成: {item_name}，共 {total_versions} 个版本，缓存 {cached_count} 个（跳过 {skipped_count} 个已缓存），耗时: {elapsed:.3f}s''')
        elif failed_count > 0:
            logger.warning(f'''[预缓存] 预缓存失败: {item_name}，耗时: {elapsed:.3f}s''')
        else:
            logger.info(f'''[预缓存] 预缓存完成: {item_name}，耗时: {elapsed:.3f}s''')
        return None
        return None
        '__pyarmor_exit_4331__(...)'
        '__pyarmor_exit_4331__(...)'

    
    def _precache_normal(self, config_id, source_file, is_share, is_pickcode, is_path, is_123_strm, is_ed2k, emby_manager, user_agent, host, emby_user_name, item_name):
        '''Emby 助手模式预缓存 - 按播放时的逻辑获取直链'''
        '__pyarmor_enter_4333__(...)'
        if not cache_manager.start_transfer(source_file, host, user_agent, is_fast_transfer = False):
            return False
        return False
        direct_link = None
        mode = None
        used_config_name = None
        if is_share and emby_manager.share_mode_enabled:
            config_name = emby_manager.config.get('share_mode_115_config', '')
            if config_name:
                logger.info(f'''[预缓存] 匹配分享模式，115 配置: {config_name}，项目: {item_name}''')
                get_direct_link_from_115 = get_direct_link_from_115
                extract_params_from_share_link = extract_params_from_share_link
                import share_302
                concurrent_play_manager = concurrent_play_manager
                import concurrent_play
                (is_concurrent, cached_copy_url) = concurrent_play_manager.check_concurrent_play(source_file, user_agent)
                if is_concurrent and concurrent_play_manager.is_enabled(config_name):
                    logger.info(f'''[预缓存] 检测到同播，执行同播复制，项目: {item_name}''')
                    if cached_copy_url:
                        direct_link = cached_copy_url
                        mode = 'share'
                        used_config_name = config_name
                    else:
                        (share_code, receive_code, file_id) = extract_params_from_share_link(source_file)
                        filename = source_file.split('/')[-1].split('?')[0]
                        copy_url = concurrent_play_manager.handle_concurrent_play_share(source_file, user_agent, share_code, receive_code, int(file_id), filename, config_name)
                        if copy_url:
                            direct_link = copy_url
                            mode = 'share'
                            used_config_name = config_name
                            logger.success(f'''[预缓存] 同播复制获取直链成功，项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] 同播复制失败，项目: {item_name}''')
                else:
                    direct_link = get_direct_link_from_115(source_file, config_name, user_agent = user_agent)
                    if direct_link:
                        mode = 'share'
                        used_config_name = config_name
                        if concurrent_play_manager.is_enabled(config_name):
                            concurrent_play_manager.register_play(source_file, user_agent, direct_link, config_name)
                        else:
                            logger.warning(f'''[预缓存] 分享模式获取直链失败，115 配置: {config_name}，项目: {item_name}''')
                    else:
                        logger.warning(f'''[预缓存] 分享模式未配置 115 账号，项目: {item_name}''')
            elif not is_share and emby_manager.share_mode_enabled:
                logger.info(f'''[预缓存] 检测到分享链接但分享模式未开启，项目: {item_name}''')
        if direct_link and is_path and emby_manager.path_mode_enabled:
            converted_path = emby_manager.convert_path(source_file)
            logger.info(f'''[预缓存] 匹配路径替换模式，路径转换: {source_file} -> {converted_path}，项目: {item_name}''')
            config_115 = None
            use_115_open = emby_manager.config.get('use_115_open', False)
            http_url = emby_manager.get_http_url_for_path(source_file) if emby_manager.http_fallback_enabled else None
            if http_url:
                RedirectHandler = RedirectHandler
                import redirect
                (fallback_link, error_msg) = RedirectHandler._try_http_fallback(http_url, user_agent)
                if fallback_link:
                    direct_link = fallback_link
                    mode = 'http_url'
                    logger.success(f'''[预缓存] 路径替换(HTTP URL)获取直链成功，项目: {item_name}''')
                else:
                    logger.warning(f'''[预缓存] 路径替换(HTTP URL)获取直链失败: {error_msg}，项目: {item_name}''')
            if not direct_link:
                config_115 = emby_manager.get_115_config_name_for_path(source_file)
                if config_115:
                    logger.info(f'''[预缓存] 路径替换尝试 115 配置: {config_115}，项目: {item_name}''')
                    get_direct_link_from_path = get_direct_link_from_path
                    import path_302
                    concurrent_play_manager = concurrent_play_manager
                    import concurrent_play
                    (is_concurrent, _) = concurrent_play_manager.check_concurrent_play(source_file, user_agent)
                    if is_concurrent and concurrent_play_manager.is_enabled(config_115):
                        logger.info(f'''[预缓存] 检测到同播（路径模式），执行同播复制，项目: {item_name}''')
                        copy_url = concurrent_play_manager.handle_concurrent_play_path(source_file, user_agent, converted_path, config_115, use_open = use_115_open)
                        if copy_url:
                            direct_link = copy_url
                            mode = 'path'
                            used_config_name = config_115
                            logger.success(f'''[预缓存] 115 同播复制获取直链成功，项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] 115 同播复制失败，项目: {item_name}''')
                    else:
                        direct_link = get_direct_link_from_path(converted_path, config_115, user_agent, use_open = use_115_open)
                        if direct_link:
                            mode = 'path'
                            used_config_name = config_115
                            if concurrent_play_manager.is_enabled(config_115):
                                concurrent_play_manager.register_play(source_file, user_agent, direct_link, config_115)
                            else:
                                logger.warning(f'''[预缓存] 路径替换 115 配置 {config_115} 未找到文件，项目: {item_name}''')
            config_123 = None
            if not direct_link and config_115:
                config_123 = emby_manager.get_123_config_name_for_path(source_file)
                if config_123:
                    logger.info(f'''[预缓存] 路径替换尝试 123 配置: {config_123}，项目: {item_name}''')
                    get_direct_link_from_path_123 = get_direct_link_from_path_123
                    import pan123
                    direct_link = get_direct_link_from_path_123(converted_path, config_123)
                    if direct_link:
                        mode = 'path'
                        used_config_name = config_123
                    else:
                        logger.warning(f'''[预缓存] 路径替换 123 配置 {config_123} 未找到文件，项目: {item_name}''')
            config_quark = None
            if not direct_link and config_115 and config_123:
                config_quark = emby_manager.get_quark_config_name_for_path(source_file)
                if config_quark:
                    logger.info(f'''[预缓存] 路径替换尝试夸克配置: {config_quark}，项目: {item_name}''')
                    get_direct_link_from_path_quark = get_direct_link_from_path_quark
                    import quark
                    direct_link = get_direct_link_from_path_quark(converted_path, config_quark)
                    if direct_link:
                        mode = 'path'
                        used_config_name = config_quark
                        logger.success(f'''[预缓存] 夸克获取直链成功，项目: {item_name}''')
                    else:
                        logger.warning(f'''[预缓存] 路径替换夸克配置 {config_quark} 未找到文件，项目: {item_name}''')
            config_cloud189 = None
            if not direct_link:
                config_cloud189 = emby_manager.get_cloud189_config_name_for_path(source_file)
                if config_cloud189:
                    logger.info(f'''[预缓存] 路径替换尝试天翼配置: {config_cloud189}，项目: {item_name}''')
                    get_direct_link_from_path_cloud189 = get_direct_link_from_path_cloud189
                    import cloud189
                    direct_link = get_direct_link_from_path_cloud189(converted_path, config_cloud189)
                    if direct_link:
                        mode = 'path'
                        used_config_name = config_cloud189
                        logger.success(f'''[预缓存] 天翼获取直链成功，项目: {item_name}''')
                    else:
                        logger.warning(f'''[预缓存] 路径替换天翼配置 {config_cloud189} 未找到文件，项目: {item_name}''')
            if not direct_link and config_115 and config_123 and config_quark and config_cloud189:
                logger.warning(f'''[预缓存] 路径替换未找到匹配的网盘配置，项目: {item_name}''')
            elif not direct_link and is_path and emby_manager.path_mode_enabled:
                logger.info(f'''[预缓存] 检测到本地路径但路径替换模式未开启，项目: {item_name}''')
        if direct_link and is_pickcode and emby_manager.pickcode_mode_enabled:
            config_name = emby_manager.pickcode_mode_115_config
            use_115_open_pc = emby_manager.config.get('use_115_open', False)
            if config_name:
                logger.info(f'''[预缓存] 匹配 Pickcode 模式，115 配置: {config_name}，项目: {item_name}''')
                get_direct_link_from_pickcode = get_direct_link_from_pickcode
                extract_pickcode_from_url = extract_pickcode_from_url
                import pickcode_302
                concurrent_play_manager = concurrent_play_manager
                import concurrent_play
                (is_concurrent, _) = concurrent_play_manager.check_concurrent_play(source_file, user_agent)
                if is_concurrent and concurrent_play_manager.is_enabled(config_name):
                    pickcode = extract_pickcode_from_url(source_file)
                    if pickcode:
                        logger.info(f'''[预缓存] 检测到同播（Pickcode 模式），执行同播复制，项目: {item_name}''')
                        if not source_file.split('/')[-1].split('?')[0]:
                            source_file.split('/')[-1].split('?')[0]
                        filename = f'''file_{pickcode}'''
                        copy_url = concurrent_play_manager.handle_concurrent_play_pickcode(source_file, user_agent, pickcode, filename, config_name, use_open = use_115_open_pc)
                        if copy_url:
                            direct_link = copy_url
                            mode = 'pickcode'
                            used_config_name = config_name
                            logger.success(f'''[预缓存] 同播复制获取直链成功（Pickcode 模式），项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] 同播复制失败（Pickcode 模式），项目: {item_name}''')
                    else:
                        direct_link = get_direct_link_from_pickcode(source_file, config_name, user_agent, use_open = use_115_open_pc)
                        if direct_link:
                            mode = 'pickcode'
                            used_config_name = config_name
                            if concurrent_play_manager.is_enabled(config_name):
                                concurrent_play_manager.register_play(source_file, user_agent, direct_link, config_name)
                            else:
                                logger.warning(f'''[预缓存] Pickcode 模式获取直链失败，115 配置: {config_name}，项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] Pickcode 模式未配置 115 账号，项目: {item_name}''')
                elif not direct_link and is_pickcode and emby_manager.pickcode_mode_enabled:
                    logger.info(f'''[预缓存] 检测到 Pickcode 链接但 Pickcode 模式未开启，项目: {item_name}''')
        if direct_link and is_123_strm and emby_manager.strm_123_mode_enabled:
            config_name = emby_manager.strm_123_mode_config
            if config_name:
                logger.info(f'''[预缓存] 匹配 123 STRM 模式，123 配置: {config_name}，项目: {item_name}''')
                parse_qs = parse_qs
                urlparse = urlparse
                import urllib.parse
                parsed = urlparse(source_file)
                params = parse_qs(parsed.query)
                file_name = params.get('name', [
                    ''])[0]
                file_size = params.get('size', [
                    ''])[0]
                md5 = params.get('md5', [
                    ''])[0]
                s3_key_flag = params.get('s3_key_flag', [
                    ''])[0]
                if file_size and md5 and s3_key_flag:
                    config_123 = config_manager.get_123_config_by_name(config_name)
                    if config_123 and config_123.get('token'):
                        P123Client = P123Client
                        import p123client
                        client = P123Client(token = config_123['token'])
                        if not file_name:
                            file_name
                        payload = {
                            'Etag': md5,
                            'FileName': 'unknown.file',
                            'S3KeyFlag': s3_key_flag,
                            'Size': int(file_size) }
                        direct_link = client.download_url(payload)
                        if direct_link:
                            mode = '123_strm'
                            used_config_name = config_name
                        else:
                            logger.warning(f'''[预缓存] 123 STRM 模式获取直链失败，123 配置: {config_name}，项目: {item_name}''')
                    else:
                        logger.warning(f'''[预缓存] 123 STRM 模式未找到配置或缺少 token: {config_name}，项目: {item_name}''')
                else:
                    logger.warning(f'''[预缓存] 123 STRM URL 参数不完整，项目: {item_name}''')
            else:
                logger.warning(f'''[预缓存] 123 STRM 模式未配置 123 账号，项目: {item_name}''')
        elif not direct_link and is_123_strm and emby_manager.strm_123_mode_enabled:
            logger.info(f'''[预缓存] 检测到 123 STRM 链接但 123 STRM 模式未开启，项目: {item_name}''')
        if direct_link and is_ed2k and emby_manager.ed2k_mode_enabled:
            config_name = emby_manager.ed2k_mode_115_config
            if config_name:
                use_115_open_ed2k = emby_manager.config.get('use_115_open', False)
                logger.info(f'''[预缓存] 匹配 ed2k 模式，115 配置: {config_name}，项目: {item_name}''')
                parse_qs = parse_qs
                urlparse = urlparse
                import urllib.parse
                parsed = urlparse(source_file)
                params = parse_qs(parsed.query)
                file_hash = params.get('hash', [
                    ''])[0]
                file_size = params.get('size', [
                    ''])[0]
                file_name = params.get('name', [
                    ''])[0]
                if file_hash and file_size:
                    concurrent_play_manager = concurrent_play_manager
                    import concurrent_play
                    (is_concurrent, _) = concurrent_play_manager.check_concurrent_play(source_file, user_agent)
                    if is_concurrent and concurrent_play_manager.is_enabled(config_name):
                        logger.info(f'''[预缓存] 检测到同播（ed2k 模式），执行同播复制，项目: {item_name}''')
                        if not file_name:
                            file_name
                        copy_url = concurrent_play_manager.handle_concurrent_play_ed2k(source_file, user_agent, file_hash, file_size, f'''ed2k_{file_hash}''', config_name, use_open = use_115_open_ed2k)
                        if copy_url:
                            direct_link = copy_url
                            mode = 'ed2k'
                            used_config_name = config_name
                            logger.success(f'''[预缓存] ed2k 同播复制获取直链成功，项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] ed2k 同播复制失败，项目: {item_name}''')
                    else:
                        ed2k_strm_manager = ed2k_strm_manager
                        import ed2k_strm
                        if not file_name:
                            file_name
                        result = ed2k_strm_manager.get_download_url_for_emby(filehash = file_hash, filesize = file_size, filename = f'''ed2k_{file_hash}''', config_name = config_name, use_open = use_115_open_ed2k, user_agent = user_agent)
                        if result.get('success') and result.get('download_url'):
                            direct_link = result['download_url']
                            mode = 'ed2k'
                            used_config_name = config_name
                            if concurrent_play_manager.is_enabled(config_name):
                                concurrent_play_manager.register_play(source_file, user_agent, direct_link, config_name)
                            else:
                                logger.warning(f'''[预缓存] ed2k 模式获取直链失败: {result.get('error', '')}，项目: {item_name}''')
                        else:
                            logger.warning(f'''[预缓存] ed2k STRM URL 参数不完整，项目: {item_name}''')
                else:
                    logger.warning(f'''[预缓存] ed2k 模式未配置 115 账号，项目: {item_name}''')
            elif not direct_link and is_ed2k and emby_manager.ed2k_mode_enabled:
                logger.info(f'''[预缓存] 检测到 ed2k 链接但 ed2k 模式未开启，项目: {item_name}''')
        if direct_link and source_file.startswith('http') and emby_manager.http_fallback_enabled:
            RedirectHandler = RedirectHandler
            import redirect
            logger.info(f'''[预缓存] 尝试 HTTP 回退模式，源文件: {source_file}，项目: {item_name}''')
            (fallback_link, error_msg) = RedirectHandler._try_http_fallback(source_file, user_agent)
            if fallback_link:
                direct_link = fallback_link
                mode = 'http_fallback'
                used_config_name = None
            else:
                logger.warning(f'''[预缓存] HTTP 回退模式获取直链失败: {error_msg}，项目: {item_name}''')
        elif not direct_link and source_file.startswith('http') and emby_manager.http_fallback_enabled:
            logger.info(f'''[预缓存] 源文件为 HTTP 链接但 HTTP 回退模式未开启，项目: {item_name}''')
        if direct_link:
            if mode == 'path' and used_config_name:
                if config_manager.get_115_config_by_name(used_config_name):
                    source_type = '115'
                elif config_manager.get_123_config_by_name(used_config_name):
                    source_type = '123'
                else:
                    source_type = None
            elif mode in ('share', 'pickcode', 'ed2k'):
                source_type = '115'
            elif mode == '123_strm':
                source_type = '123'
            else:
                source_type = None
            mode_names = {
                'share': '分享模式',
                'path': '路径替换模式',
                'pickcode': 'Pickcode 模式',
                '123_strm': '123 STRM 模式',
                'ed2k': 'ed2k 模式',
                'http_fallback': 'HTTP 回退模式' }
            mode_display = mode_names.get(mode, mode)
            cache_manager.set(source_file, direct_link, host, user_agent, used_config_name, source_type, is_fast_transfer = False, emby_user_name = emby_user_name)
            logger.success(f'''[预缓存] {mode_display}获取直链成功，已缓存: {item_name}''')
            cache_manager.finish_transfer(source_file, host, user_agent, is_fast_transfer = False)
            return True
        return True
        logger.warning(f'''[预缓存] 所有模式均未获取到直链: {item_name}''')
        cache_manager.finish_transfer(source_file, host, user_agent, is_fast_transfer = False)
        return False
        return False
    # WARNING: Decompyle incomplete

    
    def _precache_fast_transfer(self, config_id, source_file, is_share, is_pickcode, is_path, is_123_strm, is_ed2k, emby_manager, user_agent, host, emby_user_id, emby_user_name, item_name):
        '''秒传播放模式预缓存 - 按播放时的逻辑获取直链'''
        '__pyarmor_enter_4336__(...)'
        ft_config = config_manager.get_fast_transfer_config(config_id)
        if not ft_config:
            return False
        return False
        get_fast_transfer_play_manager = get_fast_transfer_play_manager
        import fast_transfer_play
        ft_manager = get_fast_transfer_play_manager(config_id, user_agent, emby_user_id, emby_user_name)
        if not ft_manager:
            logger.debug('[预缓存] 无法创建秒传管理器')
            return False
        return False
        direct_link = None
        if is_share and ft_config.get('use_115_open', False):
            logger.info(f'''[预缓存] Open API 模式不支持分享下载接口，跳过秒传分享预缓存，项目: {item_name}''')
            return False
        return False
        if is_share and ft_config.get('share_mode_enabled', False):
            logger.info(f'''[预缓存] 秒传分享模式: {item_name}''')
            direct_link = ft_manager.get_download_url_from_share(source_file, host)
        elif is_pickcode and ft_config.get('pickcode_mode_enabled', False):
            extract_pickcode_from_url = extract_pickcode_from_url
            import pickcode_302
            pickcode = extract_pickcode_from_url(source_file)
            if pickcode:
                logger.info(f'''[预缓存] 秒传Pickcode模式: {item_name}''')
                direct_link = ft_manager.get_download_url_from_pickcode(pickcode, host, source_file)
            elif is_path and ft_config.get('path_mode_enabled', False):
                converted_path = emby_manager.convert_path(source_file)
                logger.info(f'''[预缓存] 秒传路径模式: {item_name}''')
                direct_link = ft_manager.get_download_url_from_path(converted_path, host, source_file)
            elif is_123_strm and ft_config.get('strm_123_mode_enabled', False):
                logger.info(f'''[预缓存] 秒传123STRM模式: {item_name}''')
                direct_link = ft_manager.get_download_url_from_123_strm(source_file, host)
            elif is_ed2k and ft_config.get('ed2k_mode_enabled', False):
                logger.info(f'''[预缓存] 秒传ed2k模式: {item_name}''')
                direct_link = ft_manager.get_download_url_from_ed2k(source_file, host)
        if direct_link:
            logger.success(f'''[预缓存] 秒传已缓存直链: {item_name}''')
            return True
        return True
        logger.warning(f'''[预缓存] 秒传无法获取直链: {item_name}''')
        return False
        return False
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_4310__(...)'
    '__pyarmor_exit_4310__(...)'

precache_manager = PrecacheManager()
return None
return None
'__pyarmor_exit_4307__(...)'
'__pyarmor_exit_4307__(...)'
