# File: reshare_strm.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: reshare_strm.py.1shot.das

'''115 转存再分享再生成 STRM 模块'''
'__pyarmor_enter_4540__(...)'
import time
import random
import string
import asyncio
from pathlib import Path
from typing import List, Tuple, Dict, Optional
from concurrent.futures import ThreadPoolExecutor, as_completed
from itertools import cycle
from p115client import P115Client, check_response
from p115client.tool.attr import normalize_attr
from p115client.tool.iterdir import iter_files_with_path_skim
from logger import Logger
from config_manager import config_manager
from ua import UserAgentUtils, ShareP115Client
from share_strm import ApiEndpointCooldown, run_share_strm_task, iter_share_files_with_path, StrmGenerator, MetadataDownloader, ThreadRecursiveScanner, check_share_task_stopped
logger_strm = Logger('strm.log')

def generate_random_code(length):
    '''生成随机字母数字混合码'''
    '__pyarmor_enter_4543__(...)'
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k = length))
    None(None)
    return None
    '__pyarmor_exit_4544__(...)'
    '__pyarmor_exit_4544__(...)'


def api_delay():
    '''API调用间隔延迟，防止风控'''
    '__pyarmor_enter_4546__(...)'
    delay = random.uniform(0.3, 0.8)
    time.sleep(delay)
    return None
    return None
    '__pyarmor_exit_4547__(...)'
    '__pyarmor_exit_4547__(...)'


def format_size(size_bytes):
    '''格式化文件大小'''
    '__pyarmor_enter_4549__(...)'
    if size_bytes < 1024:
        return f'''{size_bytes}B'''
    None(None)
    return None
    if size_bytes < 1048576:
        return f'''{size_bytes / 1024:.2f}KB'''
    None(None)
    return None
    if size_bytes < 1073741824:
        return f'''{size_bytes / 1048576:.2f}MB'''
    None(None)
    return None
    if size_bytes < 0x10000000000:
        return f'''{size_bytes / 1073741824:.2f}GB'''
    None(None)
    return None
    if size_bytes < 0x4000000000000:
        return f'''{size_bytes / 0x10000000000:.2f}TB'''
    None(None)
    return None
    return f'''{size_bytes / 0x4000000000000:.2f}PB'''
    None(None)
    return None
    '__pyarmor_exit_4550__(...)'
    '__pyarmor_exit_4550__(...)'


def count_share_files_fast(client, share_code, receive_code, speed_mode, collect_files):
    '''使用 NanShare 的模式统计分享中的文件数量
    
    Args:
        collect_files: 如果为 True，则收集并返回所有文件信息
    
    Returns:
        如果 collect_files=False: (file_count, folder_count, total_size)
        如果 collect_files=True: (file_count, folder_count, total_size, all_files_list)
    '''
    '__pyarmor_enter_4552__(...)'
    file_count = 0
    folder_count = 0
    total_size = 0
    folder_ids = set()
    all_files = [] if collect_files else None
    ios_ua_kwargs = UserAgentUtils.get_ios_ua_app()
    ios_ua_kwargs_no_app = UserAgentUtils.get_ios_ua_app(app = False)
    speed_configs = {
        0: (0.25, 0.25, 0.75, 30),
        1: (0.5, 0.5, 1.2, 13) }
    (_, app_https_cooldown, api_cooldown, max_workers) = speed_configs.get(speed_mode, speed_configs[0])
    snap_app_https = None(api_callable = (lambda p: pass# WARNING: Decompyle incomplete
), cooldown = app_https_cooldown)
    
    def _snap_cookie(p):
        '__pyarmor_enter_4555__(...)'
        kwargs = UserAgentUtils.get_ios_ua_app(app = False)
    # WARNING: Decompyle incomplete

    snap_api = ApiEndpointCooldown(api_callable = _snap_cookie, cooldown = api_cooldown)
    first_page_api_pool = [
        snap_app_https] * 12
    first_page_api_pool.insert(6, snap_api)
    first_page_api_cycler = cycle(first_page_api_pool)
    
    def _job(api_endpoint, _cid, offset, path_prefix):
        '__pyarmor_enter_4558__(...)'
        if speed_mode == 1:
            limit = 7000
        elif offset == 0:
            pass
        
        limit = 7000
        payload = {
            'share_code': share_code,
            'receive_code': receive_code,
            'cid': _cid,
            'limit': limit,
            'offset': offset,
            'asc': 1,
            'o': 'user_ptime' }
        resp = api_endpoint(payload)
        check_response(resp)
        data = resp.get('data', { })
        count = data.get('count', 0)
        items = data.get('list', [])
        files_found = 0
        size_found = 0
        subdirs_to_scan = []
        files_list = []
        for attr in items:
            if not isinstance(attr, dict):
                continue
            original_thumb = attr.get('thumb', '')
            original_sha1 = attr.get('sha1', '')
            attr['share_code'] = share_code
            attr['receive_code'] = receive_code
            attr = normalize_attr(attr)
            path = f'''{path_prefix}/{attr['name']}''' if path_prefix else f'''/{attr['name']}'''
            if attr['is_dir']:
                folder_ids.add(int(attr['id']))
                subdirs_to_scan.append((int(attr['id']), 0, path))
                continue
            files_found += 1
            size_found += attr.get('size', 0)
            if not collect_files:
                continue
            attr['path'] = path
            attr['thumb'] = original_thumb
            attr['sha1'] = original_sha1
            attr['file_id'] = attr['id']
            files_list.append(attr)
        new_offset = offset + len(items)
        if new_offset < count and len(items) > 0:
            subdirs_to_scan.append((_cid, new_offset, path_prefix))
        return (files_found, size_found, subdirs_to_scan, files_list)
        None(None)
        return None
        '__pyarmor_exit_4559__(...)'
        '__pyarmor_exit_4559__(...)'

    seen_dir_ids = set()
    seen_file_ids = set()
# WARNING: Decompyle incomplete


def count_folder_files(client, cid, video_exts, metadata_exts):
    '''递归统计网盘文件夹中的文件数量（包括所有子文件夹）
    
    如果传入 video_exts 和 metadata_exts，则返回:
        (file_count, folder_count, video_count, meta_count, other_count)
    否则返回: (file_count, folder_count)
    '''
    '__pyarmor_enter_4561__(...)'
    file_count = 0
    folder_count = 0
    video_count = 0
    meta_count = 0
    other_count = 0
    if video_exts is not None:
        video_exts is not None
    categorize = metadata_exts is not None
    iter_fs_files = iter_fs_files
    import p115client.tool.iterdir
    ios_ua_kwargs = UserAgentUtils.get_ios_ua_app(app = False)
    dirs_to_scan = [
        cid]
# WARNING: Decompyle incomplete


class ReshareStrmManager:
    '''转存再分享再生成 STRM 管理器'''
    '__pyarmor_enter_4564__(...)'
    
    def __init__(self):
        '__pyarmor_enter_4567__(...)'
        return None
        return None
        '__pyarmor_exit_4568__(...)'
        '__pyarmor_exit_4568__(...)'

    
    async def process_reshare_strm(self, share_links, config_115, strm_config, local_path, first_parse_mode, new_link_parse_mode, enable_strm_log, verify_method):
        '''
        处理转存再分享再生成 STRM 的完整流程
        
        Args:
            share_links: 分享链接列表
            config_115: 115 配置
            strm_config: STRM 配置
            local_path: 本地 STRM 路径
            first_parse_mode: 首次解析模式 (0=最快, 1=大包模式)
            new_link_parse_mode: 新链接解析模式 (0=最快, 1=大包模式)
            enable_strm_log: 是否输出生成 STRM 详细日志
            verify_method: 校验方法 (0=cookie扫描, 1=115open扫描)
        
        Returns:
            结果字典
        '''
        pass
    # WARNING: Decompyle incomplete

    
    def process_reshare_strm_sync(self, share_links, config_115, strm_config, local_path, first_parse_mode, new_link_parse_mode, enable_strm_log, verify_method):
        '''同步版本的 process_reshare_strm，用于在线程中调用'''
        '__pyarmor_enter_4579__(...)'
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.close()
        return loop.run_until_complete(self.process_reshare_strm(share_links = share_links, config_115 = config_115, strm_config = strm_config, local_path = local_path, first_parse_mode = first_parse_mode, new_link_parse_mode = new_link_parse_mode, enable_strm_log = enable_strm_log, verify_method = verify_method))
        None(None)
        return None
        loop.close()
        '__pyarmor_exit_4580__(...)'
        '__pyarmor_exit_4580__(...)'

    return None
    return None
    '__pyarmor_exit_4565__(...)'
    '__pyarmor_exit_4565__(...)'

reshare_strm_manager = ReshareStrmManager()
return None
return None
'__pyarmor_exit_4541__(...)'
'__pyarmor_exit_4541__(...)'
