# File: service.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: service.py.1shot.das

__doc__ = 'NanShare 主服务模块'
'__pyarmor_enter_4768__(...)'
import os
from flask import Flask, request, jsonify, send_from_directory, redirect, Response
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB_DIR = os.path.join(PROJECT_ROOT, 'web')
app = Flask(__name__, static_folder = None)
NO_AUTH_PATHS = [
    '/login.html',
    '/api/auth/login',
    '/api/version',
    '/api/login/wallpapers']
handle_preflight = (lambda : '__pyarmor_enter_4771__(...)'if request.method == 'OPTIONS':
path = request.path.lower()if path.startswith('/emby/') and path.startswith('/videos/') and path.startswith('/audio/') and path.startswith('/web/') or path.startswith('/users/'):
resp = app.make_default_options_response()origin = request.headers.get('Origin', '*')resp.headers['Access-Control-Allow-Origin'] = originresp.headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE, PATCH, OPTIONS'resp.headers['Access-Control-Allow-Headers'] = 'Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization, X-Playback-Session-Id'if origin and origin != '*':
resp.headers['Access-Control-Allow-Credentials'] = 'true'resp.headers['Access-Control-Allow-Private-Network'] = 'true'resp.headers['Access-Control-Max-Age'] = '86400'respNone(None)NoneNoneNone'__pyarmor_exit_4772__(...)''__pyarmor_exit_4772__(...)')()
check_auth = (lambda : '__pyarmor_enter_4774__(...)'if request.path in NO_AUTH_PATHS:
NoneNoneif request.path.startswith('/assets/') and request.path.startswith('/css/') or request.path.startswith('/js/'):
NoneNoneif request.path.startswith('/emby/') and request.path.startswith('/Videos/') or request.path.startswith('/videos/'):
NoneNoneif request.path.startswith('/Users/') or request.path.startswith('/users/'):
NoneNoneif request.path == '/api/' and request.path.startswith('/api/share_115') or request.path == '/api/cd2/webhook':
NoneNoneif request.path == '/api/douban/img':
NoneNoneif request.path == '/api/ed2k_strm':
NoneNoneif request.path.startswith('/api/') and request.path not in ('/api/auth/login', '/api/auth/config'):
auth_header = request.headers.get('Authorization', '')token_param = request.args.get('token', '')if auth_header or token_param:
NoneNone(jsonify({
'success': False,
'message': '未授权访问' }), 401)None(None)NoneNoneNone'__pyarmor_exit_4775__(...)''__pyarmor_exit_4775__(...)')()
after_request = (lambda response: '__pyarmor_enter_4777__(...)'path = request.path.lower()if path.startswith('/emby/') and path.startswith('/videos/') and path.startswith('/audio/') and path.startswith('/web/') or path.startswith('/users/'):
origin = request.headers.get('Origin', '*')response.headers.setdefault('Access-Control-Allow-Origin', origin)response.headers.setdefault('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS')response.headers.setdefault('Access-Control-Allow-Headers', 'Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization')if origin and origin != '*':
response.headers.setdefault('Access-Control-Allow-Credentials', 'true')response.headers.setdefault('Access-Control-Allow-Private-Network', 'true')response.headers.setdefault('Cross-Origin-Resource-Policy', 'cross-origin')responseNone(None)None'__pyarmor_exit_4778__(...)''__pyarmor_exit_4778__(...)')()
index = (lambda : '__pyarmor_enter_4780__(...)'send_from_directory(WEB_DIR, 'index.html')None(None)None'__pyarmor_exit_4781__(...)''__pyarmor_exit_4781__(...)')()
serve_static = (lambda filename: '__pyarmor_enter_4783__(...)'if filename.startswith('api/') and filename.startswith('emby/') and filename.startswith('Videos/') or filename.startswith('videos/'):
('Not Found', 404)('Not Found', 404)if filename.startswith('Users/') or filename.startswith('users/'):
('Not Found', 404)('Not Found', 404)file_path = os.path.join(WEB_DIR, filename)if os.path.isfile(file_path):
send_from_directory(WEB_DIR, filename)None(None)Noneif os.path.splitext(filename)[1]:
('Not Found', 404)('Not Found', 404)send_from_directory(WEB_DIR, 'index.html')None(None)None'__pyarmor_exit_4784__(...)''__pyarmor_exit_4784__(...)')()

def _import_modules():
    '''延迟导入模块'''
    '__pyarmor_enter_4786__(...)'
    RedirectHandler = RedirectHandler
    import redirect
    api_bp = api_bp
    import api
    logger = logger
    logger_302 = logger_302
    import logger
    return (api_bp, RedirectHandler, logger_302)
    None(None)
    return None
    '__pyarmor_exit_4787__(...)'
    '__pyarmor_exit_4787__(...)'

RedirectHandler = None
logger_302 = None
from api import api_bp
app.register_blueprint(api_bp)
(_, RedirectHandler, logger_302) = _import_modules()
handle_share_link = (lambda video_path, ext: '__pyarmor_enter_4789__(...)'if logger_302:
logger_302.info(f'''收到 302 请求: /emby/videos/{video_path}/original.{ext}''')if RedirectHandler:
RedirectHandler.handle_request(video_path, ext, request)None(None)None(jsonify({
'error': '服务未初始化' }), 500)None(None)None# WARNING: Decompyle incomplete
)()
handle_stream_request = (lambda item_id, ext: '__pyarmor_enter_4792__(...)'if logger_302:
logger_302.info(f'''收到 stream 请求: item_id={item_id}, args={dict(request.args)}''')if RedirectHandler:
media_source_id = request.args.get('MediaSourceId', '')if media_source_id and media_source_id.startswith('mediasource_'):
item_id = media_source_id.replace('mediasource_', '')video_path = item_idext = 'mp4'RedirectHandler.handle_request(video_path, ext, request)None(None)None(jsonify({
'error': '服务未初始化' }), 500)None(None)None# WARNING: Decompyle incomplete
)()()()()()()()()()()()()()()()()
handle_subtitle_request = (lambda item_id, media_source_id, subtitle_path: '__pyarmor_enter_4795__(...)'import requests as reqResponse = Responseimport flaskEmbyManager = EmbyManagerimport embyif not request.headers.get('X-Emby-Config-Id'):
request.headers.get('X-Emby-Config-Id')config_id = request.headers.get('X-FastTransfer-Config-Id')emby_manager = EmbyManager(config_id)emby_url = f'''{emby_manager.server}/emby/Videos/{item_id}/{media_source_id}/Subtitles/{subtitle_path}'''if request.query_string:
emby_url += f'''?{request.query_string.decode('utf-8')}'''if logger_302:
logger_302.debug(f'''字幕请求转发到 Emby: {emby_url}''')headers = { }for key, value in request.headers:
if not key.lower() not in ('host', 'content-length'):
continueheaders[key] = valueresp = req.request(method = request.method, url = emby_url, headers = headers, data = request.get_data(), stream = True, timeout = 30)excluded_headers = [
'content-encoding',
'content-length',
'transfer-encoding',
'connection']# WARNING: Decompyle incomplete
)()()()()
handle_precache_detail = (lambda user_id, item_id: '__pyarmor_enter_4798__(...)'import requests as reqif not request.headers.get('X-Emby-Config-Id'):
request.headers.get('X-Emby-Config-Id')config_id = request.headers.get('X-FastTransfer-Config-Id')if config_id and item_id.isdigit():
precache_manager = precache_managerimport precacheprecache_manager.handle_detail_request(config_id = config_id, item_id = item_id, emby_user_id = user_id, request_headers = dict(request.headers))EmbyManager = EmbyManagerimport embyemby_manager = EmbyManager(config_id)emby_url = f'''{emby_manager.server}/emby/Users/{user_id}/Items/{item_id}'''if request.query_string:
emby_url += f'''?{request.query_string.decode('utf-8')}'''headers = { }for key, value in request.headers:
if not key.lower() not in ('host', 'content-length'):
continueheaders[key] = valueif emby_manager.api_key and 'api_key' not in emby_url:
separator = '&' if '?' in emby_url else '?'emby_url += f'''{separator}api_key={emby_manager.api_key}'''resp = req.request(method = request.method, url = emby_url, headers = headers, data = request.get_data(), stream = True, timeout = 30)excluded_headers = [
'content-encoding',
'content-length',
'transfer-encoding',
'connection']# WARNING: Decompyle incomplete
)()
if __name__ == '__main__':
    app.run(host = '0.0.0.0', port = 8115, debug = False)
return None
app.route('/emby/Users/<user_id>/Items/<item_id>', methods = [
    'GET'])
return None
# WARNING: Decompyle incomplete
