# File: share_strm.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: share_strm.py.1shot.das

'''分享 STRM 生成模块（入口模块，实际逻辑拆分到子模块）'''
'__pyarmor_enter_4708__(...)'
import asyncio
import threading
from typing import Dict, List, Tuple, Optional
from logger import Logger
from ua import ShareP115Client
logger_strm_ctrl = Logger('strm.log')
_share_stop_event = threading.Event()

class ShareTaskStoppedError(Exception):
    '''分享任务被用户停止'''
    '__pyarmor_enter_4711__(...)'
    return None
    return None
    '__pyarmor_exit_4712__(...)'
    '__pyarmor_exit_4712__(...)'


def is_share_task_stopped():
    '''检查分享任务是否已被停止'''
    '__pyarmor_enter_4714__(...)'
    return _share_stop_event.is_set()
    None(None)
    return None
    '__pyarmor_exit_4715__(...)'
    '__pyarmor_exit_4715__(...)'


def check_share_task_stopped():
    '''检查并抛出异常（如果任务已被停止）'''
    '__pyarmor_enter_4717__(...)'
    if _share_stop_event.is_set():
        raise ShareTaskStoppedError('任务已被用户停止')
    return None
    return None
    '__pyarmor_exit_4718__(...)'
    '__pyarmor_exit_4718__(...)'


def request_stop_share_tasks():
    '''请求停止所有分享任务'''
    '__pyarmor_enter_4720__(...)'
    _share_stop_event.set()
    logger_strm_ctrl.info('已发送停止信号给所有分享任务')
    return None
    return None
    '__pyarmor_exit_4721__(...)'
    '__pyarmor_exit_4721__(...)'


def reset_share_task_stop():
    '''重置停止信号（提交新任务时调用）'''
    '__pyarmor_enter_4723__(...)'
    _share_stop_event.clear()
    return None
    return None
    '__pyarmor_exit_4724__(...)'
    '__pyarmor_exit_4724__(...)'

from share_scanner import ApiEndpointCooldown, iter_share_files_with_path, ThreadRecursiveScanner
from strm_generator import StrmGenerator, MetadataDownloader
logger_strm = Logger('strm.log')

async def run_share_strm_task(*, share_code, receive_code, share_url, strm_config, config_115, local_path, speed_mode, enable_detail_log, pre_scanned_files, skip_review_check):
    pass
# WARNING: Decompyle incomplete


def run_share_strm_task_sync(*, share_code, receive_code, share_url, strm_config, config_115, local_path, speed_mode, enable_detail_log, pre_scanned_files, skip_review_check):
    '''同步版本的 run_share_strm_task，用于在线程中调用'''
    '__pyarmor_enter_4729__(...)'
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.close()
    return loop.run_until_complete(run_share_strm_task(share_code = share_code, receive_code = receive_code, share_url = share_url, strm_config = strm_config, config_115 = config_115, local_path = local_path, speed_mode = speed_mode, enable_detail_log = enable_detail_log, pre_scanned_files = pre_scanned_files, skip_review_check = skip_review_check))
    None(None)
    return None
    loop.close()
    '__pyarmor_exit_4730__(...)'
    '__pyarmor_exit_4730__(...)'


class TaskQueue:
    '''任务队列管理器'''
    '__pyarmor_enter_4732__(...)'
    
    def __init__(self):
        '__pyarmor_enter_4735__(...)'
        self.queue = None
        self.current_task = None
        self.is_processing = False
        self.processor = None
        return None
        return None
        '__pyarmor_exit_4736__(...)'
        '__pyarmor_exit_4736__(...)'

    
    def set_processor(self, processor):
        '__pyarmor_enter_4738__(...)'
        self.processor = processor
        return None
        return None
        '__pyarmor_exit_4739__(...)'
        '__pyarmor_exit_4739__(...)'

    
    def add_task(self, task):
        '__pyarmor_enter_4741__(...)'
        if self.queue:
            self.queue.put_nowait(task)
            logger_strm.info(f'''任务已加入队列，当前队列: {self.queue.qsize()} 个''')
        return None
        return None
        '__pyarmor_exit_4742__(...)'
        '__pyarmor_exit_4742__(...)'

    
    async def start(self):
        pass
    # WARNING: Decompyle incomplete

    
    async def stop(self):
        pass
    # WARNING: Decompyle incomplete

    
    def clear_all(self):
        '''清除所有任务（队列+当前任务）'''
        '__pyarmor_enter_4750__(...)'
        cleared_count = 0
        if not self.queue and self.queue.empty():
            self.queue.get_nowait()
            self.queue.task_done()
            cleared_count += 1
            if not self.queue.empty():
                continue
        if self.current_task:
            self.current_task = None
            cleared_count += 1
        logger_strm.info(f'''已清除 {cleared_count} 个分享任务''')
        return cleared_count
        None(None)
        return None
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_4733__(...)'
    '__pyarmor_exit_4733__(...)'

task_queue = TaskQueue()
return None
return None
'__pyarmor_exit_4709__(...)'
'__pyarmor_exit_4709__(...)'
