# File: strm_generator.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: strm_generator.py.1shot.das

'''STRM 文件生成器和元数据下载器模块'''
'__pyarmor_enter_4957__(...)'
import asyncio
import os
import threading
import time
from pathlib import Path
from typing import Dict, Set, List, Tuple
from config_manager import config_manager
from logger import Logger
from ua import UserAgentUtils
from share_strm import check_share_task_stopped
logger_strm = Logger('strm.log')

class StrmGenerator:
    '''STRM 文件生成器'''
    '__pyarmor_enter_4960__(...)'
    
    def __init__(self, config, client, enable_detail_log):
        '__pyarmor_enter_4963__(...)'
        self.config = config
        self.client = client
        self.enable_detail_log = enable_detail_log
        self.total_count = 0
        self.strm_count = 0
        self.strm_fail_count = 0
        self.download_success = 0
        self.download_fail = 0
        video_ext_str = config.get('video_extensions', '')
    # WARNING: Decompyle incomplete

    
    def should_generate_strm(self, filename, filesize):
        '''判断文件是否应该生成 STRM'''
        '__pyarmor_enter_4966__(...)'
        min_size = self.config.get('min_file_size', 0)
        if min_size > 0 and filesize < min_size:
            return ('文件大小小于最小限制', False)
        return ('文件大小小于最小限制', False)
        file_ext = Path(filename).suffix.lower()
        if file_ext not in self.video_extensions:
            return (f'''文件扩展名 {file_ext} 不在支持列表中''', False)
        None(None)
        return None
        return ('', True)
        return ('', True)
        '__pyarmor_exit_4967__(...)'
        '__pyarmor_exit_4967__(...)'

    get_strm_filename = (lambda file_path: '__pyarmor_enter_4969__(...)'if file_path.suffix.lower() == '.iso':
f'''{file_path.stem}.iso.strm'''None(None)Nonef'''{file_path.stem}.strm'''None(None)None'__pyarmor_exit_4970__(...)''__pyarmor_exit_4970__(...)')()
    
    def get_strm_url(self, share_code, receive_code, file_id, file_name):
        '''生成 STRM URL'''
        '__pyarmor_enter_4972__(...)'
        request_url = self.config.get('request_url', '')
        base_url = request_url.rstrip('/')
        url = f'''{base_url}/api/?share_code={share_code}&id={file_id}&receive_code={receive_code}'''
        if not self.config.get('strm_exclude_filename', True):
            url += f'''&{file_name}'''
        return url
        None(None)
        return None
        '__pyarmor_exit_4973__(...)'
        '__pyarmor_exit_4973__(...)'

    
    async def process_single_file_async(self, item, share_code, receive_code, share_path, local_path):
        '''异步处理单个文件'''
        pass
    # WARNING: Decompyle incomplete

    
    async def generate_from_share(self, share_code, receive_code, share_path, local_path, speed_mode, pre_scanned_files, share_url, skip_review_check):
        '''
        从分享链接生成 STRM 文件，返回 (总数, 成功, 失败, 元数据成功, 元数据失败, 耗时)
        
        :param speed_mode: 运行速度模式 (0=最快, 1=大包模式, 2=线程递归, 3=葵花宝典)
        :param pre_scanned_files: 预扫描的文件列表，如果提供则跳过扫描步骤
        :param share_url: 完整的分享链接 URL（用于日志显示）
        :param skip_review_check: 跳过审核状态检测（转存再分享的新链接无需检测）
        '''
        pass
    # WARNING: Decompyle incomplete

    return None
    staticmethod
    return None
    '__pyarmor_exit_4961__(...)'
    '__pyarmor_exit_4961__(...)'


class MetadataDownloader:
    '''元数据文件下载器（统一使用 share/downurl API）'''
    '__pyarmor_enter_5002__(...)'
    
    def __init__(self, config, client, enable_detail_log):
        '__pyarmor_enter_5005__(...)'
        self.config = config
        self.client = client
        self.enable_detail_log = enable_detail_log
        self.metadata_count = 0
        self.metadata_fail_count = 0
        config_name = config.get('use_115_config', '')
        self.cookie = ''
        if config_name:
            config_115 = config_manager.get_115_config_by_name(config_name)
            if config_115:
                self.cookie = config_115.get('cookie', '')
        self.ios_ua = UserAgentUtils.generate_u115_ios()
        self.headers = {
            'User-Agent': self.ios_ua,
            'Cookie': self.cookie }
        return None
        return None
        '__pyarmor_exit_5006__(...)'
        '__pyarmor_exit_5006__(...)'

    
    async def download_metadata_async(self, downloads_list, share_code, receive_code):
        '''下载元数据文件（统一使用 share/downurl API 直接获取下载链接）'''
        pass
    # WARNING: Decompyle incomplete

    
    async def _download_via_share_downurl(self, file_list, share_code, receive_code):
        '''使用 share/downurl API 直接获取下载链接（无需转存，参考 share_302）'''
        pass
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_5003__(...)'
    '__pyarmor_exit_5003__(...)'

return None
return None
'__pyarmor_exit_4958__(...)'
'__pyarmor_exit_4958__(...)'
