# File: subscribe.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: subscribe.py.1shot.das

'''订阅模块 - 操作基类 + 核心逻辑（资源搜索、识别匹配、转存、STRM生成）'''
'__pyarmor_enter_5014__(...)'
import re
import time
import random
import threading
from typing import Optional, Dict, Any, List, Tuple
from datetime import datetime
from logger import logger_subscribe as logger, logger_nameparser, use_log_file
from config_manager import config_manager
from media_info_builder import apply_recognize_result, build_recognize_result, build_torrent_info, recognize_media
from nanshare_db import subscribe_db
from transfer_115 import Transfer115
RECOGNIZE_META_LOG_KEYS = ('name', 'year', 'type', 'begin_season', 'begin_episode', 'end_episode', 'season_episode', 'edition', 'tmdb_id', 'imdb_id', 'douban_id')
TORRENT_LOG_KEYS = ('resolution', 'effect', 'resource_type', 'release_group', 'video_codec', 'audio_codec', 'frame_rate', 'web_source', 'custom_capture', 'part')
SUBSCRIBE_FILTER_LOG_KEYS = ('resolution', 'effect', 'resource_type', 'release_group')
FFPROBE_MAPPED_KEYS = ('resolution', 'effect', 'video_codec', 'audio_codec', 'frame_rate')

def _format_size(size_bytes):
    '''格式化文件大小为可读格式（KB/MB/GB/TB/PB）'''
    '__pyarmor_enter_5017__(...)'
    if size_bytes < 1024:
        return f'''{size_bytes}B'''
    None(None)
    return None
    if size_bytes < 1048576:
        return f'''{size_bytes / 1024:.2f}KB'''
    None(None)
    return None
    if size_bytes < 1073741824:
        return f'''{size_bytes / 1048576:.2f}MB'''
    None(None)
    return None
    if size_bytes < 0x10000000000:
        return f'''{size_bytes / 1073741824:.2f}GB'''
    None(None)
    return None
    if size_bytes < 0x4000000000000:
        return f'''{size_bytes / 0x10000000000:.2f}TB'''
    None(None)
    return None
    return f'''{size_bytes / 0x4000000000000:.2f}PB'''
    None(None)
    return None
    '__pyarmor_exit_5018__(...)'
    '__pyarmor_exit_5018__(...)'


def _build_media_folder_name(sub):
    '''构建媒体文件夹名称: 名字 (年份) {tmdbid-ID}
    例: 侏罗纪世界3 (2022) {tmdbid-507086}
    '''
    '__pyarmor_enter_5020__(...)'
    if not sub.get('name', ''):
        sub.get('name', '')
    name = sub.get('title', '')
    year = sub.get('year', '')
    tmdb_id = sub.get('tmdb_id', '')
    if not name or tmdb_id:
        return ''
    return ''
    name = re.sub('[\\\\/:*?"<>|]', '', name).strip()
    parts = [
        name]
    if year:
        parts.append(f'''({year})''')
    parts.append(f'''{{tmdbid-{tmdb_id}}}''')
    return ' '.join(parts)
    None(None)
    return None
    '__pyarmor_exit_5021__(...)'
    '__pyarmor_exit_5021__(...)'


class SubscribeEngineBase:
    '''订阅引擎操作基类 - 转存/STRM/扫描/ffprobe/通知'''
    '__pyarmor_enter_5023__(...)'
    
    def _get_share_link(self, resource, sub):
        '''从影巢资源获取 115 分享链接'''
        '__pyarmor_enter_5026__(...)'
        if resource.get('share_link'):
            return resource['share_link']
        None(None)
        return None
        hdhive_url = resource.get('hdhive_url', '')
        if not hdhive_url:
            resource_id = resource.get('resource_id', '')
            if resource_id:
                hdhive_url = f'''https://hdhive.com/resource/115/{resource_id}'''
            else:
                logger.warning('影巢资源缺少 URL 和 slug')
                return ''
            return ''
        get_hdhive_unlocker = get_hdhive_unlocker
        import hdhive
        unlocker = get_hdhive_unlocker()
        if not (unlocker or unlocker.open_client) and unlocker.client:
            logger.warning('影巢未初始化（未配置凭据或 API Key）')
            return ''
        return ''
        result = unlocker.process_url(hdhive_url)
        if result.get('success') and result.get('final_url'):
            link = result['final_url']
            points_used = result.get('points_used', 0)
            res_type = result.get('resource_type', '')
            if res_type == 'free':
                logger.info(f'''影巢解析成功 (免费): {link}''')
            elif res_type == 'unlocked' and points_used > 0:
                logger.info(f'''影巢解析成功 (消耗 {points_used} 积分): {link}''')
            elif res_type == 'unlocked':
                logger.info(f'''影巢解析成功 (已解锁): {link}''')
            else:
                logger.info(f'''影巢解析成功: {link}''')
            return link
        None(None)
        return None
        reason = result.get('reason', result.get('message', '未知'))
        if reason == 'points_exceed_limit':
            required = result.get('required_points', 0)
            pl = config_manager.get_hdhive_config().get('points_limit', 20)
            if pl == 0:
                logger.warning(f'''影巢解析跳过: 付费资源（需 {required} 积分），积分限制为 0 不解锁''')
            else:
                logger.warning(f'''影巢解析跳过: 需要 {required} 积分，超出积分限制 ({pl})''')
        else:
            logger.warning(f'''影巢解析失败: {reason}''')
        return ''
        return ''
    # WARNING: Decompyle incomplete

    
    def _prepare_transfer_target(self, sub):
        '''准备转存目标：创建 Transfer115 实例 + 追更文件夹（含季文件夹）。
        返回 (transferer, target_cid)，失败返回 None。
        仅需调用一次，后续多个文件直接复用返回的 transferer 和 target_cid。
        '''
        '__pyarmor_enter_5029__(...)'
        global_config = config_manager.get_subscribe_config()
        config_name = global_config.get('use_115_config', '')
        if not config_name:
            logger.error('未配置 115 账号（请在订阅设置中配置）')
            return None
        return None
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115:
            logger.error(f'''115 配置 {config_name} 不存在''')
            return None
        return None
        cookie = config_115.get('cookie', '')
        if not cookie:
            logger.error('115 Cookie 为空')
            return None
        return None
        if not sub.get('transfer_folders'):
            sub.get('transfer_folders')
        transfer_folders = global_config.get('transfer_folders', [])
        if not transfer_folders:
            logger.error('未配置转存文件夹')
            return None
        return None
        target_cid = str(transfer_folders[0].get('cid', '0'))
        transferer = Transfer115(cookie, target_cid)
        folder_name = _build_media_folder_name(sub)
        if not folder_name:
            logger.error('无法构建媒体文件夹名称（缺少名称或 TMDB ID）')
            return None
        return None
        result = transferer.create_folder(target_cid, folder_name)
        if not result.get('success'):
            logger.error(f'''创建追更文件夹失败: {folder_name} - {result.get('message', '')}''')
            return None
        return None
        target_cid = str(result['cid'])
        logger.info(f'''追更文件夹: {folder_name} (CID: {target_cid})''')
        if sub.get('type') == 'tv':
            season_num = sub.get('current_season', 1)
            season_folder = f'''Season {season_num}'''
            sr = transferer.create_folder(target_cid, season_folder)
            if not sr.get('success'):
                logger.error(f'''创建季文件夹失败: {season_folder} - {sr.get('message', '')}''')
                return None
            return None
            target_cid = str(sr['cid'])
            logger.info(f'''季文件夹: {season_folder} (CID: {target_cid})''')
        return (transferer, target_cid)
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _do_transfer(self, sub, share_link, selected, transferer, target_cid):
        '''执行 115 转存，返回是否成功。TV 订阅时按文件转存匹配的集数。
        若提供 transferer 和 target_cid，则跳过文件夹创建，直接转存。
        '''
        '__pyarmor_enter_5032__(...)'
        logger.info('开始 115 转存...')
        if transferer and target_cid:
            pass
        else:
            prepared = self._prepare_transfer_target(sub)
            if not prepared:
                return False
            return False
            (transferer, target_cid) = prepared
        (share_code, receive_code) = Transfer115.parse_share_link(share_link)
        if not share_code or receive_code:
            logger.error('无法解析分享链接')
            return False
        return False
        return self._do_transfer_per_file(transferer, share_code, receive_code, target_cid, sub, selected)
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _do_transfer_per_file(self, transferer, share_code, receive_code, target_cid, sub, selected):
        '''按文件转存：用订阅解析模式扫描分享，找到匹配的视频文件，逐个转存'''
        '__pyarmor_enter_5035__(...)'
        import os as _os
        VIDEO_EXTS = {
            '.ts',
            '.avi',
            '.flv',
            '.iso',
            '.mkv',
            '.mov',
            '.mp4',
            '.wmv',
            '.m2ts',
            '.rmvb'}
        global_sub_config = config_manager.get_subscribe_config()
        parse_mode = global_sub_config.get('parse_mode', 3)
        speed_mode = 0 if parse_mode == 3 else parse_mode
        mode_names = {
            0: '最快',
            1: '大包',
            2: '线程递归' }
        logger.info(f'''按文件转存，扫描分享文件（{mode_names.get(speed_mode, '最快')}模式）...''')
        iter_share_files_with_path = iter_share_files_with_path
        import share_scanner
        all_files = []
        for file_info in iter_share_files_with_path(client = transferer.client, share_code = share_code, receive_code = receive_code, cid = 0, speed_mode = speed_mode):
            name = file_info.get('name', '')
            path = file_info.get('path', '')
            ext = _os.path.splitext(name)[1].lower()
            is_video = ext in VIDEO_EXTS
            all_files.append({
                'fid': str(file_info.get('id', '')),
                'name': name,
                'path': path,
                'size': file_info.get('size', 0),
                'is_video': is_video })
    # WARNING: Decompyle incomplete

    
    def _do_transfer_by_fid(self, sub, items, transferer, target_cid):
        '''直接按 fid 转存文件，无需重新扫描分享链接。
        items: 包含 fid/share_code/receive_code/filename 的文件列表。
        若提供 transferer 和 target_cid，则跳过文件夹创建，直接转存。
        '''
        '__pyarmor_enter_5038__(...)'
        import time as _time
        import random as _random
        if transferer and target_cid:
            pass
        else:
            prepared = self._prepare_transfer_target(sub)
            if not prepared:
                return False
            return False
            (transferer, target_cid) = prepared
        success_count = 0
        for item in items:
            fid = item.get('fid', '')
            share_code = item.get('share_code', '')
            receive_code = item.get('receive_code', '')
            fname = item.get('filename', '')
            if not fid and share_code or receive_code:
                logger.warning(f'''缺少转存参数，跳过: {fname}''')
                continue
            share_params = f'''(share_code={share_code}&id={fid}&receive_code={receive_code})'''
            _time.sleep(_random.uniform(0.3, 0.8))
            result = transferer.transfer_single_file(share_code, receive_code, fid, target_cid)
            if result.get('success'):
                success_count += 1
                logger.info(f'''转存成功: {fname} {share_params}''')
                continue
            logger.warning(f'''转存失败: {fname} {share_params} ({result.get('message', '')})''')
        total = len(items)
        logger.info(f'''转存完成: {success_count}/{total} 成功''')
        return success_count > 0
        None(None)
        return None
        '__pyarmor_exit_5039__(...)'
        '__pyarmor_exit_5039__(...)'

    
    def _do_share_strm(self, sub, share_link, matched_items):
        '''执行分享 STRM 生成（复用 115 分享 STRM 模块），返回 STRM 结果描述（空字符串表示失败）'''
        '__pyarmor_enter_5041__(...)'
        logger.info('开始分享 STRM 生成流程...')
        self._last_strm_files = []
        (share_code, receive_code) = Transfer115.parse_share_link(share_link)
        if not share_code or receive_code:
            logger.error('无法解析分享链接的分享码或密码')
            return ''
        return ''
        strm_config = config_manager.get_share_strm_config()
        config_name = strm_config.get('use_115_config', '')
        if not config_name:
            logger.error('未配置 115 账号（请在 115 分享 STRM 设置中配置）')
            return ''
        return ''
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115:
            logger.error(f'''115 配置 [{config_name}] 不存在''')
            return ''
        return ''
        local_path = sub.get('strm_folder_path', '')
        if not local_path:
            strm_folders = config_manager.get_share_strm_folders()
            if strm_folders:
                local_path = strm_folders[0].get('path', '')
            else:
                local_path = strm_config.get('local_strm_path', '')
        if not local_path:
            logger.error('未配置 STRM 输出目录，请在 115 分享 STRM 设置中配置路径')
            return ''
        return ''
        import os as _os
        folder_name = _build_media_folder_name(sub)
        if not folder_name:
            logger.error('无法构建媒体文件夹名称（缺少名称或 TMDB ID）')
            return ''
        return ''
        local_path = _os.path.join(local_path, folder_name)
        if sub.get('type') == 'tv':
            season_num = sub.get('current_season', 1)
            local_path = _os.path.join(local_path, f'''Season {season_num}''')
        _os.makedirs(local_path, exist_ok = True)
        logger.info(f'''追更 STRM 文件夹: {local_path}''')
        reshare_enabled = sub.get('reshare_enabled', False)
        if reshare_enabled:
            return self._do_share_strm_reshare(sub, share_link, strm_config, config_115, local_path, matched_items)
        None(None)
        return None
        return self._do_share_strm_normal(sub, share_link, share_code, receive_code, strm_config, config_115, local_path, matched_items)
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _do_share_strm_reshare(self, sub, share_link, strm_config, config_115, local_path, matched_items):
        '''转存再分享模式：只转存命中的文件（单文件逐个转存）→ 分享 → 生成 STRM'''
        '__pyarmor_enter_5044__(...)'
        import os as _os
        import time as _time
        import random as _random
        import string as _string
        sub_name = sub.get('name', '')
        cookie = config_115.get('cookie', '')
        if not cookie:
            logger.error('115 Cookie 为空')
            return ''
        return ''
        logger.info(f'''订阅 [{sub_name}] 使用转存再分享模式（单文件转存）''')
        UserAgentUtils = UserAgentUtils
        import ua
        (share_code, receive_code) = Transfer115.parse_share_link(share_link)
        if not share_code or receive_code:
            logger.error('无法解析分享链接')
            return ''
        return ''
        transferer = Transfer115(cookie, '0')
        tmp_folder_name = f'''Nanshare-{''.join(_random.choices(_string.ascii_lowercase + _string.digits, k = 4))}'''
        result = transferer.create_folder('0', tmp_folder_name)
        if not result.get('success'):
            logger.error(f'''创建临时文件夹失败: {result.get('message')}''')
            return ''
        return ''
        target_cid = result['cid']
        logger.info(f'''创建临时文件夹: {tmp_folder_name} (CID: {target_cid})''')
        nested_cid = target_cid
        media_folder = _build_media_folder_name(sub)
    # WARNING: Decompyle incomplete

    
    def _do_tv_reshare_strm(self, sub, selected_items, link_groups, strm_config, config_115, local_path):
        '''TV 转存再分享模式：按文件转存选定集数 → 分享 → 生成 STRM
        使用订阅的单文件转存逻辑，只转存匹配的集数文件。
        '''
        '__pyarmor_enter_5047__(...)'
        import os as _os
        import time as _time
        import random as _random
        import string as _string
        sub_name = sub.get('name', '')
        cookie = config_115.get('cookie', '')
        if not cookie:
            logger.error('115 Cookie 为空')
            return ''
        return ''
        UserAgentUtils = UserAgentUtils
        import ua
        transferer = Transfer115(cookie, '0')
        folder_name = f'''Nanshare-{''.join(_random.choices(_string.ascii_lowercase + _string.digits, k = 4))}'''
        result = transferer.create_folder('0', folder_name)
        if not result.get('success'):
            logger.error(f'''创建临时文件夹失败: {result.get('message')}''')
            return ''
        return ''
        target_cid = result['cid']
        logger.info(f'''创建临时文件夹: {folder_name} (CID: {target_cid})''')
        nested_cid = target_cid
        media_folder = _build_media_folder_name(sub)
    # WARNING: Decompyle incomplete

    
    def _do_share_strm_normal(self, sub, share_link, share_code, receive_code, strm_config, config_115, local_path, matched_items):
        '''普通分享模式：预扫描 + 生成 STRM'''
        '__pyarmor_enter_5050__(...)'
        import os as _os
        global_sub_config = config_manager.get_subscribe_config()
        parse_mode = global_sub_config.get('parse_mode', 3)
        speed_mode = parse_mode
        mode_names = {
            0: '最快',
            1: '大包',
            2: '线程递归',
            3: '葵花宝典' }
        logger.info(f'''订阅 [{sub.get('name')}] STRM解析模式: {mode_names.get(speed_mode, speed_mode)}模式''')
        cookie = config_115.get('cookie', '')
        all_files = self._scan_share_files(cookie, share_code, receive_code, speed_mode, strm_config)
        if not all_files:
            logger.error('分享中无文件，终止生成')
            return ''
        return ''
    # WARNING: Decompyle incomplete

    
    def _do_batch_reshare_strm(self, share_links):
        '''批量转存再分享：将多个分享链接一起转存，创建新分享，再生成 STRM'''
        '__pyarmor_enter_5053__(...)'
        import asyncio
        strm_config = config_manager.get_share_strm_config()
        config_name = strm_config.get('use_115_config', '')
        if not config_name:
            logger.error('转存再分享: 未配置 115 账号')
            return None
        return None
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115:
            logger.error(f'''转存再分享: 115 配置 {config_name} 不存在''')
            return None
        return None
        strm_folders = config_manager.get_share_strm_folders()
        if strm_folders:
            local_path = strm_folders[0].get('path', '')
        else:
            local_path = strm_config.get('local_strm_path', '')
        if not local_path:
            logger.error('转存再分享: 未配置 STRM 输出目录')
            return None
        return None
        first_parse_mode = strm_config.get('reshare_first_parse_mode', 0)
        new_link_parse_mode = strm_config.get('reshare_new_link_parse_mode', 1)
        enable_strm_log = strm_config.get('enable_strm_detail_log', True)
        verify_method = strm_config.get('reshare_verify_method', 0)
        ReshareStrmManager = ReshareStrmManager
        import reshare_strm
        reset_share_task_stop = reset_share_task_stop
        import share_strm
        reset_share_task_stop()
        manager = ReshareStrmManager()
        coro = manager.process_reshare_strm(share_links = share_links, config_115 = config_115, strm_config = strm_config, local_path = local_path, first_parse_mode = first_parse_mode, new_link_parse_mode = new_link_parse_mode, enable_strm_log = enable_strm_log, verify_method = verify_method)
        loop = asyncio.get_running_loop()
    # WARNING: Decompyle incomplete

    
    def _ffprobe_from_share(self, share_link, sub):
        '''从 115 分享链接获取视频直链并 ffprobe 识别'''
        '__pyarmor_enter_5056__(...)'
        is_ffprobe_available = is_ffprobe_available
        ffprobe_url = ffprobe_url
        import ffprobe_helper
        if not is_ffprobe_available():
            logger.warning('ffprobe 未安装，跳过识别')
            return None
        return None
        share_code_match = re.search('/s/([a-zA-Z0-9]+)', share_link)
        receive_code_match = re.search('password=([a-zA-Z0-9]{4})', share_link)
        if not share_code_match or receive_code_match:
            logger.warning('无法从分享链接解析参数用于 ffprobe')
            return None
        return None
        share_code = share_code_match.group(1)
        receive_code = receive_code_match.group(1)
        global_config = config_manager.get_subscribe_config()
        config_name = global_config.get('share_parse_use_115_config', '')
        if not config_name:
            mode = sub.get('mode', 'share_strm')
            if mode == 'transfer':
                if not sub.get('transfer_use_115_config'):
                    sub.get('transfer_use_115_config')
                config_name = global_config.get('use_115_config', '')
            else:
                strm_config = config_manager.get_share_strm_config()
                config_name = strm_config.get('use_115_config', '')
        if not config_name:
            logger.warning('无 115 配置，跳过 ffprobe')
            return None
        return None
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115 or config_115.get('cookie'):
            logger.warning('115 Cookie 不可用，跳过 ffprobe')
            return None
        return None
        cookie = config_115['cookie']
        file_id = self._find_video_file_in_share(cookie, share_code, receive_code)
        if not file_id:
            logger.warning('分享中未找到视频文件，跳过 ffprobe')
            return None
        return None
        get_download_url = get_download_url
        import share_302
        video_url = get_download_url(share_code, receive_code, file_id, config_name)
        if not video_url:
            logger.warning('视频直链为空')
            return None
        return None
        logger.info('正在 ffprobe 识别视频...')
        result = ffprobe_url(video_url, timeout = 10)
        return result
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _find_video_file_in_share(self, cookie, share_code, receive_code):
        '''在 115 分享中查找第一个视频文件的 file_id（使用 share_scanner，统一 UA）'''
        '__pyarmor_enter_5059__(...)'
        import os as _os
        VIDEO_EXTS = {
            '.ts',
            '.avi',
            '.flv',
            '.iso',
            '.mkv',
            '.mov',
            '.mp4',
            '.wmv',
            '.m2ts',
            '.rmvb'}
        ShareP115Client = ShareP115Client
        import ua
        client = ShareP115Client(cookie, check_for_relogin = True)
        iter_share_files_with_path = iter_share_files_with_path
        import share_scanner
        for file_info in iter_share_files_with_path(client = client, share_code = share_code, receive_code = receive_code, cid = 0, speed_mode = 0):
            name = file_info.get('name', '')
            ext = _os.path.splitext(name)[1].lower()
            if not ext in VIDEO_EXTS:
                continue
            
            return iter_share_files_with_path(client = client, share_code = share_code, receive_code = receive_code, cid = 0, speed_mode = 0), str(file_info.get('id', ''))
            None(None)
            return None
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _scan_share_files(self, cookie, share_code, receive_code, speed_mode, strm_config, quiet):
        '''扫描分享文件列表（同步，支持所有速度模式）。返回文件列表。'''
        '__pyarmor_enter_5062__(...)'
        import time as _time
        scan_start = _time.time()
        mode_names = {
            0: '最快',
            1: '大包',
            2: '线程递归',
            3: '葵花宝典' }
        if not quiet:
            logger.info(f'''开始扫描分享文件（{mode_names.get(speed_mode, '未知')}模式）...''')
    # WARNING: Decompyle incomplete

    
    def _parse_filename_meta(self, item):
        '''搜索阶段：仅用简单正则提取季集号，不做完整识别。
        完整识别（分辨率/特效/流媒体/制作组等）统一在识别阶段通过 parse_title 处理。
        '''
        '__pyarmor_enter_5065__(...)'
        if not item.get('filename', ''):
            item.get('filename', '')
        filename = item.get('title', '')
        if not filename:
            return None
        return None
        m = re.search('[Ss](\\d{1,4})\\s*[._\\-]?\\s*[Ee][Pp]?(\\d{1,4})', filename)
        if m:
            if not item.get('meta_info'):
                item.get('meta_info')
            meta_info = dict({ })
            meta_info['begin_season'] = int(m.group(1))
            meta_info['begin_episode'] = int(m.group(2))
            item['meta_info'] = meta_info
        else:
            m = re.search('(?:^|[\\W_])[Ee][Pp]?(\\d{1,4})(?:[\\W_]|$)', filename)
            if m:
                if not item.get('meta_info'):
                    item.get('meta_info')
                meta_info = dict({ })
                meta_info['begin_episode'] = int(m.group(1))
                item['meta_info'] = meta_info
        self._normalize_item_payload(item)
        return None
        return None
    # WARNING: Decompyle incomplete

    _item_meta_info = (lambda item: '__pyarmor_enter_5068__(...)'if not item:
itemif not { }.get('meta_info'):
{ }.get('meta_info')dict({ })None(None)None'__pyarmor_exit_5069__(...)''__pyarmor_exit_5069__(...)')()
    _item_media_info = (lambda item: '__pyarmor_enter_5071__(...)'if not item:
itemif not { }.get('media_info'):
{ }.get('media_info')dict({ })None(None)None'__pyarmor_exit_5072__(...)''__pyarmor_exit_5072__(...)')()
    _item_torrent_info = (lambda item: '__pyarmor_enter_5074__(...)'if not item:
itemif not { }.get('torrent_info'):
{ }.get('torrent_info')dict({ })None(None)None'__pyarmor_exit_5075__(...)''__pyarmor_exit_5075__(...)')()
    _item_season = (lambda cls, item, default: '__pyarmor_enter_5077__(...)'season = cls._item_meta_info(item).get('begin_season')# WARNING: Decompyle incomplete
)()
    _item_episode = (lambda cls, item: '__pyarmor_enter_5080__(...)'cls._item_meta_info(item).get('begin_episode')None(None)None'__pyarmor_exit_5081__(...)''__pyarmor_exit_5081__(...)')()
    _item_end_episode = (lambda cls, item: '__pyarmor_enter_5083__(...)'cls._item_meta_info(item).get('end_episode')None(None)None'__pyarmor_exit_5084__(...)''__pyarmor_exit_5084__(...)')()
    _item_episode_numbers = (lambda cls, item: '__pyarmor_enter_5086__(...)'ep_start = cls._item_episode(item)ep_end = cls._item_end_episode(item)# WARNING: Decompyle incomplete
)()
    _item_torrent_value = (lambda cls, item, key: '__pyarmor_enter_5089__(...)'value = cls._item_torrent_info(item).get(key)'' if value in (None, '') else str(value)None(None)None'__pyarmor_exit_5090__(...)''__pyarmor_exit_5090__(...)')()
    _set_item_torrent_value = (lambda item, key, value: '__pyarmor_enter_5092__(...)'if item or value in (None, ''):
NoneNoneif not item.get('torrent_info'):
item.get('torrent_info')torrent_info = dict({ })torrent_info[key] = valueitem['torrent_info'] = torrent_infoNoneNone'__pyarmor_exit_5093__(...)''__pyarmor_exit_5093__(...)')()
    _log_field_value = (lambda value: '__pyarmor_enter_5095__(...)'if value in (None, '', [], { }):
'null''null'str(value)None(None)None'__pyarmor_exit_5096__(...)''__pyarmor_exit_5096__(...)')()
    _format_log_fields = (lambda cls, payload, keys: '__pyarmor_enter_5098__(...)'if not payload:
payloadvalues = { }(lambda .0: pass# WARNING: Decompyle incomplete
)(keys())
        None(None)
        return None
        '__pyarmor_exit_5099__(...)'
        '__pyarmor_exit_5099__(...)'
)()
    _meta_log_payload = (lambda cls, meta: '__pyarmor_enter_5101__(...)'{
'name': getattr(meta, 'name', None) if meta else None,
'year': getattr(meta, 'year', None) if meta else None,
'type': getattr(getattr(meta, 'type', None), 'value', None) if meta else None,
'begin_season': getattr(meta, 'begin_season', None) if meta else None,
'begin_episode': getattr(meta, 'begin_episode', None) if meta else None,
'end_episode': getattr(meta, 'end_episode', None) if meta else None,
'season_episode': getattr(meta, 'season_episode', None) if meta else None,
'edition': getattr(meta, 'edition', None) if meta else None,
'tmdb_id': getattr(meta, 'tmdbid', None) if meta else None,
'imdb_id': getattr(meta, 'imdbid', None) if meta else None,
'douban_id': getattr(meta, 'doubanid', None) if meta else None }None(None)None'__pyarmor_exit_5102__(...)''__pyarmor_exit_5102__(...)')()
    _item_log_payload = (lambda cls, item: '__pyarmor_enter_5104__(...)'meta_info = cls._item_meta_info(item)media_info = cls._item_media_info(item)if not media_info.get('tmdb_id'):
media_info.get('tmdb_id'){
'name': meta_info.get('name'),
'year': meta_info.get('year'),
'type': meta_info.get('type'),
'begin_season': meta_info.get('begin_season'),
'begin_episode': meta_info.get('begin_episode'),
'end_episode': meta_info.get('end_episode'),
'season_episode': meta_info.get('season_episode'),
'edition': meta_info.get('edition'),
'tmdb_id': meta_info.get('tmdbid'),
'imdb_id': meta_info.get('imdbid'),
'douban_id': meta_info.get('doubanid') }None(None)None'__pyarmor_exit_5105__(...)''__pyarmor_exit_5105__(...)')()
    _meta_log_fields = (lambda cls, meta: '__pyarmor_enter_5107__(...)'cls._format_log_fields(cls._meta_log_payload(meta), RECOGNIZE_META_LOG_KEYS)None(None)None'__pyarmor_exit_5108__(...)''__pyarmor_exit_5108__(...)')()
    _meta_torrent_log_fields = (lambda cls, meta: '__pyarmor_enter_5110__(...)'cls._format_log_fields(build_torrent_info(meta) if meta else { }, TORRENT_LOG_KEYS)None(None)None'__pyarmor_exit_5111__(...)''__pyarmor_exit_5111__(...)')()
    _item_meta_log_fields = (lambda cls, item: '__pyarmor_enter_5113__(...)'cls._format_log_fields(cls._item_log_payload(item), RECOGNIZE_META_LOG_KEYS)None(None)None'__pyarmor_exit_5114__(...)''__pyarmor_exit_5114__(...)')()
    _item_torrent_log_fields = (lambda cls, item: '__pyarmor_enter_5116__(...)'cls._format_log_fields(cls._item_torrent_info(item), TORRENT_LOG_KEYS)None(None)None'__pyarmor_exit_5117__(...)''__pyarmor_exit_5117__(...)')()
    _sub_filter_log_fields = (lambda cls, sub: '__pyarmor_enter_5119__(...)'if not sub:
subcls._format_log_fields({ }, SUBSCRIBE_FILTER_LOG_KEYS)None(None)None'__pyarmor_exit_5120__(...)''__pyarmor_exit_5120__(...)')()
    _normalize_item_payload = (lambda item: '__pyarmor_enter_5122__(...)'if not item:
NoneNoneif not item.get('meta_info'):
item.get('meta_info')meta_info = dict({ })season = item.pop('parsed_season', None)episode = item.pop('parsed_episode', None)end_episode = item.pop('parsed_end_episode', None)# WARNING: Decompyle incomplete
)()
    
    def _auto_delete_if_enabled(self, sub_id, sub_name):
        '''订阅完成后，若开启了自动删除则删除该订阅'''
        '__pyarmor_enter_5125__(...)'
        cfg = config_manager.get_subscribe_config()
        if cfg.get('auto_delete_completed', False):
            subscribe_db.delete_subscribe(sub_id)
            logger.info(f'''订阅 [{sub_name}] 已完成，自动删除订阅''')
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _update_episode_progress(self, sub_id, sub, selected):
        '''更新剧集追踪进度：从 lack_episode 移除已找到的集数，完成时标记 completed。返回进度描述。'''
        '__pyarmor_enter_5128__(...)'
        lack = list(sub.get('lack_episode', []))
        if not lack:
            return ''
        return ''
        ep_start = self._item_episode(selected)
    # WARNING: Decompyle incomplete

    
    def _get_notify_image(self, sub, selected):
        '''获取通知图片URL - 必须优先使用横图(backdrop)，无横图时才回退到竖版海报'''
        '__pyarmor_enter_5131__(...)'
        TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p'
        media_type = sub.get('type', 'movie')
        backdrop = sub.get('backdrop_path', '')
        if backdrop:
            if not backdrop.startswith('http'):
                backdrop = f'''{TMDB_IMAGE_BASE}/w780{backdrop}'''
            return backdrop
        None(None)
        return None
        if media_type == 'tv':
            tmdb_id = sub.get('tmdb_id')
            current_season = sub.get('current_season', 1)
            if tmdb_id:
                TmdbDiscover = TmdbDiscover
                import tmdb_discover
                tmdb = TmdbDiscover()
                images_data = tmdb._api_get(f'''/tv/{tmdb_id}/season/{current_season}/images''')
                if images_data:
                    backdrops = images_data.get('backdrops', [])
                    if backdrops:
                        path = backdrops[0].get('file_path', '')
                        if path:
                            return f'''{TMDB_IMAGE_BASE}/w780{path}'''
                        None(None)
                        return None
                ep_num = self._item_episode(selected)
                if ep_num:
                    ep_data = tmdb._api_get(f'''/tv/{tmdb_id}/season/{current_season}/episode/{ep_num}''')
                    if ep_data:
                        still = ep_data.get('still_path', '')
                        if still:
                            return f'''{TMDB_IMAGE_BASE}/w780{still}'''
                        None(None)
                        return None
                tv_data = tmdb._api_get(f'''/tv/{tmdb_id}''')
                if tv_data:
                    tv_backdrop = tv_data.get('backdrop_path', '')
                    if tv_backdrop:
                        return f'''{TMDB_IMAGE_BASE}/w780{tv_backdrop}'''
                    None(None)
                    return None
        poster = sub.get('poster_path', '')
        if poster:
            if poster.startswith('/api/douban/'):
                return ''
            return ''
            if not poster.startswith('http'):
                poster = f'''{TMDB_IMAGE_BASE}/w500{poster}'''
            return poster
        None(None)
        return None
        return ''
        return ''
    # WARNING: Decompyle incomplete

    _send_tg_notification = (lambda message, photo_url: '__pyarmor_enter_5134__(...)'tg_config = config_manager.get_telegram_config()if not tg_config.get('enabled', False):
NoneNonebot_token = tg_config.get('bot_token', '')chat_id = tg_config.get('chat_id', '')if not bot_token or chat_id:
NoneNoneimport requestsproxy = config_manager.get_global_proxy()proxies = {
'http': proxy,
'https': proxy } if proxy else Noneif photo_url:
url = f'''https://api.telegram.org/bot{bot_token}/sendPhoto'''if len(message) <= 1024:
requests.post(url, json = {
'chat_id': chat_id,
'photo': photo_url,
'caption': message }, timeout = 15, proxies = proxies)else:
short_caption = message[:1000] + '...'requests.post(url, json = {
'chat_id': chat_id,
'photo': photo_url,
'caption': short_caption }, timeout = 15, proxies = proxies)msg_url = f'''https://api.telegram.org/bot{bot_token}/sendMessage'''requests.post(msg_url, json = {
'chat_id': chat_id,
'text': message }, timeout = 10, proxies = proxies)else:
url = f'''https://api.telegram.org/bot{bot_token}/sendMessage'''requests.post(url, json = {
'chat_id': chat_id,
'text': message }, timeout = 10, proxies = proxies)NoneNone# WARNING: Decompyle incomplete
)()
    
    def _build_notify_message(self, sub, selected, share_link, mode, strm_result, ep_progress, strm_files, all_items, done_eps):
        '''构建订阅通知消息
        all_items: 本次处理的所有文件项（用于汇总季集范围和版本信息）
        done_eps: 本次实际完成的集数列表（从 lack_episode 中移除的集数）
        '''
        '__pyarmor_enter_5137__(...)'
        sub_name = sub.get('name', '')
        year = sub.get('year', '')
        media_type = sub.get('type', 'movie')
        current_season = sub.get('current_season', 1)
        season_ep = ''
        if media_type == 'tv':
            s = self._item_season(selected, current_season)
            season_ep = f'''S{s:02d}'''
            if done_eps:
                sorted_eps = sorted(done_eps)
            else:
                all_eps = set()
                items_for_eps = all_items if all_items else [
                    selected]
                for item in items_for_eps:
                    all_eps.update(self._item_episode_numbers(item))
                sorted_eps = sorted(all_eps) if all_eps else []
            if sorted_eps:
                season_ep += ' ' + self._format_episode_range(sorted_eps)
        if mode == 'transfer':
            mode_text = '订阅转存'
        else:
            mode_text = '分享追更'
        ref_item = selected
        if all_items:
            ref_item = all_items[0]
        version_parts = []
        if self._item_torrent_value(ref_item, 'resolution'):
            version_parts.append(self._item_torrent_value(ref_item, 'resolution'))
        if self._item_torrent_value(ref_item, 'effect'):
            version_parts.append(self._item_torrent_value(ref_item, 'effect'))
        if self._item_torrent_value(ref_item, 'resource_type'):
            version_parts.append(self._item_torrent_value(ref_item, 'resource_type'))
        if self._item_torrent_value(ref_item, 'video_codec'):
            version_parts.append(self._item_torrent_value(ref_item, 'video_codec'))
        if self._item_torrent_value(ref_item, 'audio_codec'):
            version_parts.append(self._item_torrent_value(ref_item, 'audio_codec'))
        if self._item_torrent_value(ref_item, 'release_group'):
            version_parts.append(self._item_torrent_value(ref_item, 'release_group'))
        version_text = '\xc2\xb7'.join(version_parts) if version_parts else ''
        custom_template = self._get_notify_template(mode)
    # WARNING: Decompyle incomplete

    _format_episode_range = (lambda eps: '__pyarmor_enter_5140__(...)'if not eps:
''''ranges = []start = eps[0]end = eps[0]for e in eps[1:]:
if e == end + 1:
end = econtinueranges.append((start, end))start = eend = eranges.append((start, end))parts = []for s, e in ranges:
if s == e:
parts.append(f'''E{s:02d}''')continueparts.append(f'''E{s:02d}-{e:02d}''')' '.join(parts)None(None)None'__pyarmor_exit_5141__(...)''__pyarmor_exit_5141__(...)')()
    _build_ep_progress = (lambda cls, sub, prefix: '__pyarmor_enter_5143__(...)'lack_after = sub.get('lack_episode', [])total_ep = sub.get('total_episode', 0)if not total_ep:
''''done = total_ep - len(lack_after)if done <= 0:
''''if not lack_after:
f'''当前季完结 ({done}/{total_ep})'''None(None)Noneif not sub.get('start_episode', 1):
sub.get('start_episode', 1)start_ep = 1lack_set = set(lack_after)# WARNING: Decompyle incomplete
)()
    
    def _get_notify_template(self, mode):
        '''获取自定义通知模板'''
        '__pyarmor_enter_5146__(...)'
        config = config_manager.get_subscribe_config()
        return config.get('notify_template', '')
        None(None)
        return None
    # WARNING: Decompyle incomplete

    _render_jinja2_template = (lambda template_str, context: '__pyarmor_enter_5149__(...)'Template = Templateimport jinja2tpl = Template(template_str)# WARNING: Decompyle incomplete
)()
    return None
    staticmethod
    return None
    '__pyarmor_exit_5024__(...)'
    '__pyarmor_exit_5024__(...)'
    return staticmethod


class SubscribeEngine(SubscribeEngineBase):
    '''订阅执行引擎'''
    '__pyarmor_enter_5152__(...)'
    
    def __init__(self):
        '__pyarmor_enter_5155__(...)'
        self._running = False
        self._lock = threading.Lock()
        self._last_strm_files = []
        return None
        return None
        '__pyarmor_exit_5156__(...)'
        '__pyarmor_exit_5156__(...)'

    
    def is_running(self):
        '__pyarmor_enter_5158__(...)'
        return self._running
        None(None)
        return None
        '__pyarmor_exit_5159__(...)'
        '__pyarmor_exit_5159__(...)'

    
    def run_all(self):
        '''执行所有活跃订阅（定时触发 → 统一处理流程）'''
        '__pyarmor_enter_5161__(...)'
        if self._running:
            logger.warning('订阅任务正在运行中，跳过本次执行')
            return None
        return None
    # WARNING: Decompyle incomplete

    
    def run_single(self, subscribe_id):
        '''手动执行单个订阅（走独立处理流程，非统一处理）'''
        '__pyarmor_enter_5164__(...)'
        if self._running:
            logger.warning('订阅任务正在运行中，跳过本次手动执行')
            return None
        return None
    # WARNING: Decompyle incomplete

    
    def run_batch(self, subscribe_ids):
        '''批量执行多个订阅（与定时任务走完全相同的处理流程）'''
        '__pyarmor_enter_5167__(...)'
        if self._running:
            logger.warning('订阅任务正在运行中，跳过本次批量执行')
            return None
        return None
    # WARNING: Decompyle incomplete

    
    def _process_subscribe(self, sub, collect_reshare):
        '''处理单个订阅。collect_reshare=True 时只搜索匹配并返回链接，不执行最终操作'''
        '__pyarmor_enter_5170__(...)'
        sub_id = sub['subscribe_id']
        sub_name = sub['name']
        media_type = sub['type']
        tmdb_id = sub.get('tmdb_id')
        mode = sub.get('mode', 'share_strm')
        presets = self._load_presets_for_sub(sub)
        start_time = time.time()
    # WARNING: Decompyle incomplete

    
    def _process_tv_subscribe(self, sub, resources, mode, collect_reshare, start_time, presets):
        '''剧集订阅专用处理流程：
        1. 扫描所有分享 → 逐文件识别（提交到识别接口）
        2. 按 lack_episode 筛选需要的集
        3. ffprobe 补全缺失参数（仅对候选文件）
        4. 订阅参数筛选（支持多预设按序匹配）
        5. 每集选一个（或全部）
        6. 按分享链接分组处理（转存再分享模式合并为一个任务）
        '''
        '__pyarmor_enter_5173__(...)'
        sub_id = sub['subscribe_id']
        sub_name = sub['name']
        global_sub_config = config_manager.get_subscribe_config()
        all_file_items = self._recognize_tv_resources(resources, sub)
        if not all_file_items:
            subscribe_db.update_subscribe(sub_id, {
                'last_run_time': datetime.now().isoformat() })
            logger.info(f'''订阅 [{sub_name}] 无匹配文件''')
            return None
        return None
        lack = list(sub.get('lack_episode', []))
        if lack:
            needed = []
            for item in all_file_items:
                episode_numbers = self._item_episode_numbers(item)
                if len(episode_numbers) > 1:
                    if not (lambda .0: pass# WARNING: Decompyle incomplete
)(episode_numbers()):
                        continue
                    needed.append(item)
                    continue
                if not episode_numbers:
                    continue
                if not episode_numbers[0] in lack:
                    continue
                needed.append(item)
            logger.info(f'''订阅 [{sub_name}] 缺集筛选: {len(needed)}/{len(all_file_items)} 个文件覆盖缺失集 (缺 {len(lack)} 集)''')
        else:
            needed = all_file_items
            logger.info(f'''订阅 [{sub_name}] 无集数追踪，保留全部 {len(needed)} 个文件''')
        if not needed:
            subscribe_db.update_subscribe(sub_id, {
                'last_run_time': datetime.now().isoformat() })
            logger.info(f'''订阅 [{sub_name}] 无缺失集匹配文件''')
            return None
        return None
    # WARNING: Decompyle incomplete

    
    def _process_all_unified(self, all_subs):
        '''统一处理所有订阅：
        1. 统一搜索所有订阅的资源
        2. 统一获取分享链接（去重）
        3. 统一扫描分享链接（每个链接只扫一次）
        4. 统一识别文件 → 记录属于哪个订阅、电影/电视剧
        5. 统一季集预筛选（电影跳过，电视剧按 lack_episode 筛选）
        6. 按订阅分组执行最终操作（转存/普通分享STRM/转存再分享）
        '''
        '__pyarmor_enter_5176__(...)'
        import os as _os
        _Path = Path
        import pathlib
        global_sub_config = config_manager.get_subscribe_config()
        start_time = time.time()
    # WARNING: Decompyle incomplete

    
    def _unified_post_success(self, sub, selected_items, lack_before, mode, strm_result, start_time):
        '''统一流程：操作成功后的通用处理（更新集数追踪、状态、通知）'''
        '__pyarmor_enter_5179__(...)'
        sub_id = sub['subscribe_id']
        sub_name = sub['name']
        media_type = sub['type']
        if media_type == 'tv':
            for item in selected_items:
                self._update_episode_progress(sub_id, sub, item)
        if media_type == 'movie':
            subscribe_db.update_subscribe(sub_id, {
                'status': 'completed' })
            logger.info(f'''订阅 [{sub_name}] 电影订阅已完成''')
            self._auto_delete_if_enabled(sub_id, sub_name)
        ep_progress = ''
        if media_type == 'tv':
            ep_progress = self._build_ep_progress(sub)
        actually_done_eps = sorted(lack_before - set(sub.get('lack_episode', [])))
        final_selected = selected_items[0]
        final_share_link = final_selected.get('share_link', '')
        notify_msg = self._build_notify_message(sub, final_selected, final_share_link, mode, strm_result, ep_progress, self._last_strm_files, all_items = selected_items, done_eps = actually_done_eps)
        photo_url = self._get_notify_image(sub, final_selected)
        self._send_tg_notification(notify_msg, photo_url = photo_url)
        elapsed = time.time() - start_time
        logger.info(f'''订阅 [{sub_name}] 处理完成 ({elapsed:.1f}s)''')
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _unified_do_transfer(self, sub, selected_items):
        '''统一流程：单文件直接转存（不跟分享链接路径），遵循嵌套文件夹开关'''
        '__pyarmor_enter_5182__(...)'
        import time as _time
        import random as _random
        sub_name = sub.get('name', '')
        prepared = self._prepare_transfer_target(sub)
        if not prepared:
            return False
        return False
        (transferer, target_cid) = prepared
        success_count = 0
        for item in selected_items:
            fid = item.get('fid', '')
            share_code = item.get('share_code', '')
            receive_code = item.get('receive_code', '')
            fname = item.get('filename', '')
            if not fid and share_code or receive_code:
                logger.warning(f'''转存跳过（缺少 fid/share_code/receive_code）: {fname}''')
                continue
            _time.sleep(_random.uniform(0.3, 0.8))
            share_params = f'''(share_code={share_code}&id={fid}&receive_code={receive_code})'''
            result = transferer.transfer_single_file(share_code, receive_code, fid, target_cid)
            if result.get('success'):
                success_count += 1
                logger.info(f'''转存成功: {fname} {share_params}''')
                continue
            logger.warning(f'''转存失败: {fname} {share_params} ({result.get('message', '')})''')
        logger.info(f'''订阅 [{sub_name}] 转存完成: {success_count}/{len(selected_items)} 成功''')
        return success_count > 0
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _unified_do_share_strm(self, sub, selected_items):
        '''统一流程：直接生成 STRM（不跟分享链接路径），遵循嵌套文件夹开关。
        直接用 share_code/receive_code/fid 为每个文件生成对应的 STRM。
        '''
        '__pyarmor_enter_5185__(...)'
        import os as _os
        _Path = Path
        import pathlib
        sub_name = sub.get('name', '')
        strm_config = config_manager.get_share_strm_config()
        config_name = strm_config.get('use_115_config', '')
        if not config_name:
            logger.error('未配置 115 账号（请在 115 分享 STRM 设置中配置）')
            return ''
        return ''
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115:
            logger.error(f'''115 配置 [{config_name}] 不存在''')
            return ''
        return ''
        local_path = sub.get('strm_folder_path', '')
        if not local_path:
            strm_folders = config_manager.get_share_strm_folders()
            if strm_folders:
                local_path = strm_folders[0].get('path', '')
            else:
                local_path = strm_config.get('local_strm_path', '')
        if not local_path:
            logger.error('未配置 STRM 输出目录')
            return ''
        return ''
        folder_name = _build_media_folder_name(sub)
        if not folder_name:
            logger.error('无法构建媒体文件夹名称（缺少名称或 TMDB ID）')
            return ''
        return ''
        local_path = _os.path.join(local_path, folder_name)
        if sub.get('type') == 'tv':
            season_num = sub.get('current_season', 1)
            local_path = _os.path.join(local_path, f'''Season {season_num}''')
        _os.makedirs(local_path, exist_ok = True)
        logger.info(f'''追更 STRM 文件夹: {local_path}''')
        request_url = strm_config.get('request_url', '')
        if not request_url:
            logger.error('未配置 STRM 请求地址（request_url）')
            return ''
        return ''
        base_url = request_url.rstrip('/')
        strm_success = 0
        strm_fail = 0
        meta_success = 0
        meta_fail = 0
        video_ext_str = strm_config.get('video_extensions', 'mp4,mkv,ts,iso,rmvb,avi,mov,mpeg,mpg,wmv,3gp,asf,m4v,flv,m2ts,tp,f4v')
    # WARNING: Decompyle incomplete

    
    def _unified_do_reshare_strm_batch(self, reshare_group, all_items):
        '''统一流程（批量）：多个订阅合并为一次转存 + 一次分享 → 按各订阅路径生成 STRM
        修复bug：单文件转存而非整个链接转存，遵循嵌套文件夹开关。

        Args:
            reshare_group: [(sub, selected_items, lack_before), ...]
            all_items: 合并后的所有选定文件（每个 item 包含 _reshare_sub 指回所属订阅）

        Returns:
            { sub_id: result_msg } 每个订阅的 STRM 生成结果
        '''
        '__pyarmor_enter_5188__(...)'
        import os as _os
        import time as _time
        import random as _random
        import string as _string
        _Path = Path
        import pathlib
        UserAgentUtils = UserAgentUtils
        import ua
        result_map = { }
        strm_config = config_manager.get_share_strm_config()
        config_name = strm_config.get('use_115_config', '')
        if not config_name:
            logger.error('未配置 115 账号')
            return result_map
        None(None)
        return None
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115 or config_115.get('cookie'):
            logger.error('115 配置不可用')
            return result_map
        None(None)
        return None
        cookie = config_115['cookie']
        sub_local_paths = { }
        for sub, _, _ in reshare_group:
            sub_id = sub['subscribe_id']
            local_path = sub.get('strm_folder_path', '')
            if not local_path:
                strm_folders = config_manager.get_share_strm_folders()
            if not local_path:
                logger.error(f'''订阅 [{sub['name']}] 未配置 STRM 输出目录''')
                continue
            folder_name = _build_media_folder_name(sub)
            if not folder_name:
                logger.error(f'''订阅 [{sub['name']}] 无法构建媒体文件夹名称（缺少名称或 TMDB ID）''')
                continue
            local_path = _os.path.join(local_path, folder_name)
            if sub.get('type') == 'tv':
                season_num = sub.get('current_season', 1)
                local_path = _os.path.join(local_path, f'''Season {season_num}''')
            _os.makedirs(local_path, exist_ok = True)
            sub_local_paths[sub_id] = local_path
        if not sub_local_paths:
            logger.error('所有转存再分享订阅均无有效 STRM 输出路径')
            return result_map
        None(None)
        return None
        transferer = Transfer115(cookie, '0')
        tmp_folder_name = f'''Nanshare-{''.join(_random.choices(_string.ascii_lowercase + _string.digits, k = 4))}'''
        result = transferer.create_folder('0', tmp_folder_name)
        if not result.get('success'):
            logger.error(f'''创建临时文件夹失败: {result.get('message')}''')
            return result_map
        None(None)
        return None
        target_cid = result['cid']
        logger.info(f'''创建临时文件夹: {tmp_folder_name} (CID: {target_cid})''')
        sub_nested_cids = { }
        sub_has_nested = { }
        for sub, _, _ in reshare_group:
            sub_id = sub['subscribe_id']
            media_folder = _build_media_folder_name(sub)
            nested_cid = target_cid
            has_nested = False
            if media_folder:
                _time.sleep(_random.uniform(0.3, 0.6))
                nest_result = transferer.create_folder(str(target_cid), media_folder)
                if nest_result.get('success'):
                    nested_cid = nest_result['cid']
                    has_nested = True
                    logger.info(f'''创建嵌套文件夹: {media_folder} [订阅: {sub['name']}]''')
                    if sub.get('type') == 'tv':
                        season_num = sub.get('current_season', 1)
                        season_folder = f'''Season {season_num}'''
                        _time.sleep(_random.uniform(0.3, 0.6))
                        nest_result = transferer.create_folder(str(nested_cid), season_folder)
                        if nest_result.get('success'):
                            nested_cid = nest_result['cid']
                            logger.info(f'''创建季文件夹: {season_folder}''')
                        else:
                            logger.error(f'''创建季文件夹失败: {nest_result.get('message')} [订阅: {sub['name']}]''')
                        logger.error(f'''创建嵌套文件夹失败: {nest_result.get('message')} [订阅: {sub['name']}]''')
                        continue
            sub_nested_cids[sub_id] = nested_cid
            sub_has_nested[sub_id] = has_nested
        total_transferred = 0
        total_failed = 0
        for item in all_items:
            fid = item.get('fid', '')
            share_code = item.get('share_code', '')
            receive_code = item.get('receive_code', '')
            fname = item.get('filename', '')
            belong_sub = item.get('_reshare_sub', { })
            belong_sub_id = belong_sub.get('subscribe_id', '')
            if not fid and share_code or receive_code:
                logger.warning(f'''缺少转存参数，跳过: {fname} [{belong_sub.get('name', '')}]''')
                total_failed += 1
                continue
            if belong_sub_id not in sub_nested_cids:
                logger.warning(f'''跳过（嵌套文件夹不可用）: {fname} [{belong_sub.get('name', '')}]''')
                total_failed += 1
                continue
            item_target_cid = sub_nested_cids[belong_sub_id]
            _time.sleep(_random.uniform(0.3, 0.8))
            share_params = f'''(share_code={share_code}&id={fid}&receive_code={receive_code})'''
            result = transferer.transfer_single_file(share_code, receive_code, fid, item_target_cid)
            if result.get('success'):
                total_transferred += 1
                logger.info(f'''  转存成功: {fname} [{belong_sub.get('name', '')}] {share_params}''')
                continue
            total_failed += 1
            logger.warning(f'''  转存失败: {fname} [{belong_sub.get('name', '')}] {share_params} - {result.get('message')}''')
    # WARNING: Decompyle incomplete

    
    def _search_resources(self, sub, source):
        '''搜索资源'''
        '__pyarmor_enter_5191__(...)'
        tmdb_id = sub.get('tmdb_id')
        media_type = sub.get('type', 'movie')
        name = sub.get('name', '')
        results = []
        if source in ('tg_hdhive', 'hdhive'):
            hdhive_results = self._search_hdhive(tmdb_id, media_type)
            results.extend(hdhive_results)
        if source in ('tg_hdhive', 'tg'):
            tg_results = self._search_tgapi(name)
            results.extend(tg_results)
        return results
        None(None)
        return None
        '__pyarmor_exit_5192__(...)'
        '__pyarmor_exit_5192__(...)'

    
    def _search_hdhive(self, tmdb_id, media_type):
        '''通过影巢搜索（优先 Open API，回退 Server Action）'''
        '__pyarmor_enter_5194__(...)'
        get_hdhive_unlocker = get_hdhive_unlocker
        import hdhive
        unlocker = get_hdhive_unlocker()
        if not (unlocker or unlocker.open_client) and unlocker.client:
            logger.warning('影巢未初始化（未配置凭据或 API Key）')
            return []
        None(None)
        return None
        res = unlocker.get_resources(tmdb_id, media_type, website_filter = '115')
        if not res.get('success') or res.get('data'):
            logger.info(f'''影巢: {res.get('message', '无结果')}''')
            return []
        None(None)
        return None
        sub_config = config_manager.get_subscribe_config()
        kw_enabled = sub_config.get('hdhive_search_keywords_enabled', False)
        kw_list = sub_config.get('hdhive_search_keywords', [])
        official_only = sub_config.get('hdhive_official_only', False)
        raw_data = res['data']
    # WARNING: Decompyle incomplete

    
    def _search_tgapi(self, name):
        '''通过 TGAPI 搜索'''
        '__pyarmor_enter_5197__(...)'
        tg_search_client = tg_search_client
        import tg_search
        extract_telegraph_links = extract_telegraph_links
        fetch_telegraph_share_links = fetch_telegraph_share_links
        import telegraph
        status = tg_search_client.get_status()
        if not status.get('logged_in'):
            logger.warning('Telegram 未登录')
            return []
        None(None)
        return None
        config = config_manager.get_tg_search_config()
        channels = config.get('channels', [])
        if not channels:
            logger.warning('未配置 TG 搜索频道')
            return []
        None(None)
        return None
        sub_config = config_manager.get_subscribe_config()
    # WARNING: Decompyle incomplete

    _normalize_effect = (lambda effect: '__pyarmor_enter_5200__(...)'if not effect:
''''eff_upper = effect.upper()has_dv = (lambda .0: pass# WARNING: Decompyle incomplete
)(('DV', 'DOVI', 'DOLBY')())
        has_hdr = (lambda .0: pass# WARNING: Decompyle incomplete
)(('HDR', 'HLG', 'EDR')())
        if has_dv and has_hdr:
            return 'DV HDR'
        return 'DV HDR'
        if has_dv:
            return 'DV'
        return 'DV'
        if has_hdr:
            return 'HDR'
        return 'HDR'
        if 'SDR' in eff_upper:
            return 'SDR'
        return 'SDR'
        return effect
        None(None)
        return None
        '__pyarmor_exit_5201__(...)'
        '__pyarmor_exit_5201__(...)'
)()
    _normalize_fps = (lambda fps_str: '__pyarmor_enter_5203__(...)'if not fps_str:
''''cleaned = re.sub('[Ff][Pp][Ss]$', '', str(fps_str).strip())val = float(cleaned)if val <= 0:
''''f'''{round(val)}fps'''None(None)None# WARNING: Decompyle incomplete
)()
    
    def _match_resources(self, resources, sub):
        '''根据订阅条件匹配资源'''
        '__pyarmor_enter_5206__(...)'
        want_resolution = sub.get('resolution', '')
        want_effect = sub.get('effect', '')
        want_resource_type = sub.get('resource_type', '')
        want_group = sub.get('release_group', '')
        want_fps = sub.get('frame_rate', '')
        if not want_resolution and want_effect and want_resource_type and want_group and want_fps:
            return resources
        None(None)
        return None
        want_fps_norm = self._normalize_fps(want_fps) if want_fps else ''
        matched = []
        for r in resources:
            self._normalize_item_payload(r)
            res = self._item_torrent_value(r, 'resolution')
            eff = self._item_torrent_value(r, 'effect')
            rtype = self._item_torrent_value(r, 'resource_type')
            grp = self._item_torrent_value(r, 'release_group')
            if want_resolution:
                if res or want_resolution.lower() != res.lower():
                    continue
            if want_effect:
                if eff or self._normalize_effect(want_effect) != self._normalize_effect(eff):
                    continue
            if want_resource_type:
                if rtype or want_resource_type.lower() != rtype.lower():
                    continue
            if want_group:
                if grp or want_group.lower() != grp.lower():
                    continue
            if want_fps_norm:
                file_fps = self._item_torrent_value(r, 'frame_rate')
                file_fps_norm = self._normalize_fps(file_fps)
                if not file_fps_norm:
                    pass
                elif file_fps_norm != want_fps_norm:
                    continue
            matched.append(r)
        logger.info(f'''条件匹配: {len(matched)}/{len(resources)} 通过''')
        return matched
        None(None)
        return None
        '__pyarmor_exit_5207__(...)'
        '__pyarmor_exit_5207__(...)'

    
    def _load_presets_for_sub(self, sub):
        '''从订阅的 preset_ids 加载预设配置列表（按顺序），跳过不存在的预设'''
        '__pyarmor_enter_5209__(...)'
        preset_ids = sub.get('preset_ids', [])
        if not preset_ids:
            return []
        None(None)
        return None
        all_presets = config_manager.get_subscribe_presets()
    # WARNING: Decompyle incomplete

    
    def _match_resource_against_preset(self, resource, preset):
        '''检查单个资源是否匹配某个预设的筛选条件'''
        '__pyarmor_enter_5212__(...)'
        want_resolution = preset.get('resolution', '')
        want_effect = preset.get('effect', '')
        want_resource_type = preset.get('resource_type', '')
        want_group = preset.get('release_group', '')
        want_fps = preset.get('frame_rate', '')
        if not want_resolution and want_effect and want_resource_type and want_group and want_fps:
            return True
        return True
        self._normalize_item_payload(resource)
        res = self._item_torrent_value(resource, 'resolution')
        eff = self._item_torrent_value(resource, 'effect')
        rtype = self._item_torrent_value(resource, 'resource_type')
        grp = self._item_torrent_value(resource, 'release_group')
        if want_resolution:
            if res or want_resolution.lower() != res.lower():
                return False
            return False
        if want_effect:
            if eff or self._normalize_effect(want_effect) != self._normalize_effect(eff):
                return False
            return False
        if want_resource_type:
            if rtype or want_resource_type.lower() != rtype.lower():
                return False
            return False
        if want_group:
            if grp or want_group.lower() != grp.lower():
                return False
            return False
        if want_fps:
            want_fps_norm = self._normalize_fps(want_fps)
            if want_fps_norm:
                file_fps = self._item_torrent_value(resource, 'frame_rate')
                file_fps_norm = self._normalize_fps(file_fps)
                if file_fps_norm and file_fps_norm != want_fps_norm:
                    return False
                return False
        return True
        return True
        '__pyarmor_exit_5213__(...)'
        '__pyarmor_exit_5213__(...)'

    
    def _match_resources_by_presets(self, resources, presets):
        '''按预设顺序匹配资源，每个资源只归属第一个匹配的预设。
        返回 [(preset, [matched_resources]), ...] 按预设顺序排列，只包含有匹配资源的预设。
        '''
        '__pyarmor_enter_5215__(...)'
        remaining = list(resources)
        result = []
        for preset in presets:
            if not remaining:
                presets
            else:
                matched = []
                still_remaining = []
                for r in remaining:
                    if self._match_resource_against_preset(r, preset):
                        matched.append(r)
                        continue
                    still_remaining.append(r)
                if matched:
                    result.append((preset, matched))
                    logger.info(f'''预设 [{preset.get('name', preset.get('id'))}] 匹配 {len(matched)} 个资源''')
                remaining = still_remaining
        if remaining:
            logger.info(f'''多预设匹配后剩余 {len(remaining)} 个资源未匹配任何预设，跳过''')
        return result
        None(None)
        return None
        '__pyarmor_exit_5216__(...)'
        '__pyarmor_exit_5216__(...)'

    
    def _apply_preset_to_sub(self, sub, preset):
        '''将预设配置应用到订阅副本，返回新的 sub dict（不修改原始 sub）'''
        '__pyarmor_enter_5218__(...)'
        temp_sub = dict(sub)
        field_map = {
            'resolution': 'resolution',
            'effect': 'effect',
            'resource_type': 'resource_type',
            'release_group': 'release_group',
            'frame_rate': 'frame_rate',
            'mode': 'mode',
            'transfer_use_115_config': 'transfer_use_115_config',
            'search_source': 'search_source',
            'cron_expression': 'cron_expression',
            'reshare_enabled': 'reshare_enabled',
            'transfer_all_matches': 'transfer_all_matches' }
    # WARNING: Decompyle incomplete

    
    def _acquire_all_links(self, resources, sub):
        '''为所有资源预先获取 115 分享链接，返回带链接的资源列表（自动去重）'''
        '__pyarmor_enter_5221__(...)'
        sub_name = sub.get('name', '')
        linked = []
        for idx, r in enumerate(resources):
            share_link = r.get('share_link', '')
            if share_link and r.get('source') == 'hdhive':
                share_link = self._get_share_link(r, sub)
                r['share_link'] = share_link
            if not share_link:
                continue
            linked.append(r)
        seen_keys = set()
        deduped = []
        for r in linked:
            share_link = r.get('share_link', '')
            (share_code, receive_code) = Transfer115.parse_share_link(share_link)
            if share_code and receive_code:
                key = f'''{share_code}:{receive_code}'''
                if key in seen_keys:
                    continue
                seen_keys.add(key)
            deduped.append(r)
        dup_count = len(linked) - len(deduped)
        if dup_count > 0:
            logger.info(f'''订阅 [{sub_name}] 获取链接: {len(linked)}/{len(resources)} 成功，去重 {dup_count} 个重复链接''')
        else:
            logger.info(f'''订阅 [{sub_name}] 获取链接: {len(linked)}/{len(resources)} 成功''')
        return deduped
        None(None)
        return None
        '__pyarmor_exit_5222__(...)'
        '__pyarmor_exit_5222__(...)'

    
    def _get_115_cookie(self, sub):
        '''获取 115 Cookie（使用 115 分享 STRM 设置中的账号）'''
        '__pyarmor_enter_5224__(...)'
        strm_config = config_manager.get_share_strm_config()
        config_name = strm_config.get('use_115_config', '')
        if not config_name:
            return ''
        return ''
        config_115 = config_manager.get_115_config_by_name(config_name)
        if not config_115 or config_115.get('cookie'):
            return ''
        return ''
        return config_115['cookie']
        None(None)
        return None
    # WARNING: Decompyle incomplete

    _looks_like_media_path = (lambda value: '__pyarmor_enter_5227__(...)'if not value:
valuenormalized_value = str('').strip()if not normalized_value:
FalseFalseif normalized_value.startswith('/') or normalized_value.startswith('\\'):
TrueTrueif len(normalized_value) > 2 and normalized_value[1:3] in (':\\', ':/'):
TrueTrueif '/' not in normalized_value and '\\' not in normalized_value:
FalseFalsenormalized_path = normalized_value.replace('\\', '/')(parent_text, _, name_text) = normalized_path.rpartition('/')if parent_text:
parent_textbool(name_text)None(None)None'__pyarmor_exit_5228__(...)''__pyarmor_exit_5228__(...)')()
    _recognize_title_result = (lambda cls, title, skip_tmdb, force_gpt, prefer_path: '__pyarmor_enter_5230__(...)'if not title:
titlenormalized_title = str('').strip()if not normalized_title:
NoneNonerecognize_kwargs = {
'skip_tmdb': skip_tmdb,
'force_gpt': force_gpt,
'config': config_manager.get_transfer_basic_config(),
'include_internal': True }if prefer_path or cls._looks_like_media_path(normalized_title):
recognize_kwargs['path'] = normalized_titleelse:
recognize_kwargs['title'] = normalized_title# WARNING: Decompyle incomplete
)()
    _recognize_title_meta = (lambda cls, title, skip_tmdb, force_gpt, prefer_path: '__pyarmor_enter_5233__(...)'recognize_result = cls._recognize_title_result(title, skip_tmdb = skip_tmdb, force_gpt = force_gpt, prefer_path = prefer_path)if not recognize_result:
NoneNonerecognize_result.get('_meta')None(None)None'__pyarmor_exit_5234__(...)''__pyarmor_exit_5234__(...)')()
    
    def _recognize_resources(self, resources, sub):
        '''逐个识别资源：先用所选解析模式扫描每个分享的实际文件，再用真实文件名识别。'''
        '__pyarmor_enter_5236__(...)'
        import os as _os
        sub_name = sub.get('name', '')
        sub_tmdb_id = sub.get('tmdb_id')
        global_sub_config = config_manager.get_subscribe_config()
        parse_mode = global_sub_config.get('parse_mode', 3)
        gpt_cfg = config_manager.get_gpt_config()
        if gpt_cfg.get('enabled'):
            gpt_cfg.get('enabled')
        gpt_fallback_available = bool(gpt_cfg.get('api_key'))
        logger.info(f'''订阅 [{sub_name}] 开始逐个识别验证 {len(resources)} 个资源''')
        cookie = self._get_115_cookie(sub)
        if not cookie:
            logger.error(f'''订阅 [{sub_name}] 无法获取 115 Cookie，无法扫描分享文件''')
            return []
        None(None)
        return None
        strm_config = config_manager.get_share_strm_config()
        video_ext_str = strm_config.get('video_extensions', 'mp4,mkv,ts,iso,rmvb,avi,mov,mpeg,mpg,wmv,3gp,asf,m4v,flv,m2ts,tp,f4v')
    # WARNING: Decompyle incomplete

    
    def _recognize_tv_resources(self, resources, sub):
        '''剧集专用识别：扫描所有分享 → 逐文件识别 → 按集汇总。
        返回文件级别的匹配列表，每项包含 share_link, filename, parsed_episode 等。
        '''
        '__pyarmor_enter_5239__(...)'
        import os as _os
        sub_name = sub.get('name', '')
        sub_tmdb_id = sub.get('tmdb_id')
        current_season = sub.get('current_season', 1)
        global_sub_config = config_manager.get_subscribe_config()
        parse_mode = global_sub_config.get('parse_mode', 3)
        gpt_cfg = config_manager.get_gpt_config()
        if gpt_cfg.get('enabled'):
            gpt_cfg.get('enabled')
        gpt_fallback_available = bool(gpt_cfg.get('api_key'))
        logger.info(f'''订阅 [{sub_name}] 剧集识别模式: 扫描所有分享 → 逐文件识别''')
        cookie = self._get_115_cookie(sub)
        if not cookie:
            logger.error(f'''订阅 [{sub_name}] 无法获取 115 Cookie，无法扫描分享文件''')
            return []
        None(None)
        return None
        strm_config = config_manager.get_share_strm_config()
        video_ext_str = strm_config.get('video_extensions', 'mp4,mkv,ts,iso,rmvb,avi,mov,mpeg,mpg,wmv,3gp,asf,m4v,flv,m2ts,tp,f4v')
    # WARNING: Decompyle incomplete

    _apply_meta_to_resource = (lambda resource, meta: '__pyarmor_enter_5245__(...)'if not meta:
NoneNoneSubscribeEngine._normalize_item_payload(resource)if not getattr(meta, 'title', None):
getattr(meta, 'title', None)if not getattr(meta, 'org_string', None):
getattr(meta, 'org_string', None)if not resource.get('filename'):
resource.get('filename')if not resource.get('title'):
resource.get('title')recognize_result = build_recognize_result(meta = meta, original_name = '', config = config_manager.get_transfer_basic_config())apply_recognize_result(resource, recognize_result, overwrite = True)SubscribeEngine._normalize_item_payload(resource)NoneNone'__pyarmor_exit_5246__(...)''__pyarmor_exit_5246__(...)')()
    return None
    staticmethod
    return None
    '__pyarmor_exit_5153__(...)'
    '__pyarmor_exit_5153__(...)'
    return classmethod

_subscribe_engine = None

def get_subscribe_engine():
    '__pyarmor_enter_5248__(...)'
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_5015__(...)'
'__pyarmor_exit_5015__(...)'
