# File: system_monitor.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: system_monitor.py.1shot.das

'''系统监控模块'''
'__pyarmor_enter_5251__(...)'
import os
import psutil
import time
import subprocess
from pathlib import Path

def is_docker_env():
    '''检查是否在 Docker 环境中运行'''
    '__pyarmor_enter_5254__(...)'
    if os.environ.get('DOCKER_ENV') == 'true':
        return True
    return True
    if Path('/.dockerenv').exists():
        return True
    return True
# WARNING: Decompyle incomplete


class SystemMonitor:
    '''系统监控器'''
    '__pyarmor_enter_5257__(...)'
    _instance = None
    _last_net_io = None
    _last_net_time = None
    _is_docker = None
    _last_container_cpu = None
    _last_container_cpu_time = None
    _last_proc_stat = None
    _last_proc_stat_time = None
    
    def __new__(cls):
        '__pyarmor_enter_5260__(...)'
    # WARNING: Decompyle incomplete

    
    def get_cpu_usage(self):
        '''获取 CPU 使用率（Docker 环境下获取容器的 CPU 使用率）'''
        '__pyarmor_enter_5263__(...)'
        if self._is_docker:
            return self._get_container_cpu_usage()
        None(None)
        return None
        return psutil.cpu_percent(interval = None)
        None(None)
        return None
        '__pyarmor_exit_5264__(...)'
        '__pyarmor_exit_5264__(...)'

    
    def _get_container_cpu_usage(self):
        '''获取容器 CPU 使用率（单核百分比）'''
        '__pyarmor_enter_5266__(...)'
        cpu_count = psutil.cpu_count()
    # WARNING: Decompyle incomplete

    
    def get_memory_usage(self):
        '''获取内存使用情况（Docker 环境下获取容器的内存使用）'''
        '__pyarmor_enter_5269__(...)'
        if self._is_docker:
            return self._get_container_memory_usage()
        None(None)
        return None
        mem = psutil.virtual_memory()
        return {
            'total': mem.total,
            'used': mem.used,
            'free': mem.available,
            'percent': mem.percent,
            'total_gb': round(mem.total / 1073741824, 2),
            'used_gb': round(mem.used / 1073741824, 2),
            'used_mb': round(mem.used / 1048576, 0),
            'total_mb': round(mem.total / 1048576, 0) }
        None(None)
        return None
        '__pyarmor_exit_5270__(...)'
        '__pyarmor_exit_5270__(...)'

    
    def _get_container_memory_usage(self):
        '''获取容器内存使用（减去页缓存，与 docker stats 一致）'''
        '__pyarmor_enter_5272__(...)'
        memory_current = Path('/sys/fs/cgroup/memory.current')
        memory_max = Path('/sys/fs/cgroup/memory.max')
        memory_stat = Path('/sys/fs/cgroup/memory.stat')
    # WARNING: Decompyle incomplete

    
    def get_disk_usage(self, path):
        '''获取磁盘使用情况（多种备用方法）'''
        '__pyarmor_enter_5275__(...)'
        disk = psutil.disk_usage(path)
        if disk.total > 0 and disk.free >= 0:
            return {
                'total': disk.total,
                'used': disk.used,
                'free': disk.free,
                'percent': disk.percent,
                'total_gb': round(disk.total / 1073741824, 1),
                'used_gb': round(disk.used / 1073741824, 1),
                'free_gb': round(disk.free / 1073741824, 1) }
        None(None)
        return None
        st = os.statvfs(path)
        total = st.f_blocks * st.f_frsize
        free = st.f_bavail * st.f_frsize
        used = total - st.f_bfree * st.f_frsize
        if total > 0:
            percent = (used / total) * 100
            return {
                'total': total,
                'used': used,
                'free': free,
                'percent': round(percent, 1),
                'total_gb': round(total / 1073741824, 1),
                'used_gb': round(used / 1073741824, 1),
                'free_gb': round(free / 1073741824, 1) }
        None(None)
        return None
        result = subprocess.run([
            'df',
            '-B1',
            path], capture_output = True, text = True, timeout = 5)
        if result.returncode == 0:
            lines = result.stdout.strip().split('\n')
            if len(lines) >= 2:
                parts = lines[-1].split()
                total = int(parts[1])
                used = int(parts[2])
                free = int(parts[3])
                percent = (used / total) * 100 if total > 0 else 0
                return {
                    'total': total,
                    'used': used,
                    'free': free,
                    'percent': round(percent, 1),
                    'total_gb': round(total / 1073741824, 1),
                    'used_gb': round(used / 1073741824, 1),
                    'free_gb': round(free / 1073741824, 1) }
            None(None)
            return None
        return {
            'total': 0,
            'used': 0,
            'free': 0,
            'percent': 0,
            'total_gb': 0,
            'used_gb': 0,
            'free_gb': 0 }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def get_network_speed(self):
        '''获取网络速度（上行/下行）- 始终获取宿主机网速'''
        '__pyarmor_enter_5278__(...)'
        current_net = psutil.net_io_counters()
        current_time = time.time()
    # WARNING: Decompyle incomplete

    
    def get_uptime(self):
        '''获取系统运行时间（秒）'''
        '__pyarmor_enter_5281__(...)'
        return int(time.time() - psutil.boot_time())
        None(None)
        return None
        '__pyarmor_exit_5282__(...)'
        '__pyarmor_exit_5282__(...)'

    
    def format_speed(self, bytes_per_sec):
        '''格式化网速'''
        '__pyarmor_enter_5284__(...)'
        if bytes_per_sec < 1024:
            return f'''{bytes_per_sec:.0f} B/s'''
        None(None)
        return None
        if bytes_per_sec < 1048576:
            return f'''{bytes_per_sec / 1024:.1f} KB/s'''
        None(None)
        return None
        if bytes_per_sec < 1073741824:
            return f'''{bytes_per_sec / 1048576:.1f} MB/s'''
        None(None)
        return None
        return f'''{bytes_per_sec / 1073741824:.2f} GB/s'''
        None(None)
        return None
        '__pyarmor_exit_5285__(...)'
        '__pyarmor_exit_5285__(...)'

    
    def format_uptime(self, seconds):
        '''格式化运行时间'''
        '__pyarmor_enter_5287__(...)'
        days = seconds // 86400
        hours = (seconds % 86400) // 3600
        minutes = (seconds % 3600) // 60
        if days > 0:
            return f'''{days}天{hours}时{minutes}分'''
        None(None)
        return None
        if hours > 0:
            return f'''{hours}小时{minutes}分钟'''
        None(None)
        return None
        return f'''{minutes}分钟'''
        None(None)
        return None
        '__pyarmor_exit_5288__(...)'
        '__pyarmor_exit_5288__(...)'

    
    def _get_host_cpu_usage(self):
        '''获取宿主机 CPU 使用率（多种备用方法）'''
        '__pyarmor_enter_5290__(...)'
        cpu = psutil.cpu_percent(interval = None)
    # WARNING: Decompyle incomplete

    
    def _get_host_memory_usage(self):
        '''获取宿主机内存使用情况（多种备用方法）'''
        '__pyarmor_enter_5293__(...)'
        mem = psutil.virtual_memory()
        if mem.total > 0:
            return {
                'total': mem.total,
                'used': mem.used,
                'percent': mem.percent,
                'total_gb': round(mem.total / 1073741824, 2),
                'used_gb': round(mem.used / 1073741824, 2),
                'used_mb': round(mem.used / 1048576, 0),
                'total_mb': round(mem.total / 1048576, 0) }
        None(None)
        return None
        meminfo = { }
    # WARNING: Decompyle incomplete

    
    def _get_process_usage(self):
        '''获取当前进程（项目）的 CPU 和内存占用（多种备用方法）'''
        '__pyarmor_enter_5296__(...)'
        proc = psutil.Process(os.getpid())
        rss_total = proc.memory_info().rss
        cpu_pct = proc.cpu_percent(interval = None)
        for child in proc.children(recursive = True):
            rss_total += child.memory_info().rss
            cpu_pct += child.cpu_percent(interval = None)
        return {
            'cpu_percent': round(cpu_pct, 1),
            'memory_bytes': rss_total,
            'memory_mb': round(rss_total / 1048576, 1),
            'memory_gb': round(rss_total / 1073741824, 2) }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    
    def _format_memory(self, used_gb, used_mb):
        '''格式化内存显示：小于 1GB 用 MB，否则用 GB'''
        '__pyarmor_enter_5299__(...)'
        if used_gb < 1:
            return f'''{int(used_mb)}MB'''
        None(None)
        return None
        return f'''{used_gb:.1f}GB'''
        None(None)
        return None
        '__pyarmor_exit_5300__(...)'
        '__pyarmor_exit_5300__(...)'

    
    def _format_total_memory(self, total_gb):
        '''格式化总内存显示'''
        '__pyarmor_enter_5302__(...)'
        if total_gb < 1:
            return f'''{int(total_gb * 1024)}MB'''
        None(None)
        return None
        return f'''{total_gb:.1f}GB'''
        None(None)
        return None
        '__pyarmor_exit_5303__(...)'
        '__pyarmor_exit_5303__(...)'

    
    def get_all_stats(self):
        '''获取所有系统状态（包含宿主机和项目级数据）'''
        '__pyarmor_enter_5305__(...)'
        host_cpu = self._get_host_cpu_usage()
        host_mem = self._get_host_memory_usage()
        if self._is_docker:
            project_cpu = self.get_cpu_usage()
            container_mem = self.get_memory_usage()
            project_mem_mb = container_mem.get('used_mb', 0)
            project_mem_gb = container_mem.get('used_gb', 0)
        else:
            proc = self._get_process_usage()
            project_cpu = proc['cpu_percent']
            project_mem_mb = proc['memory_mb']
            project_mem_gb = proc['memory_gb']
        disk = self.get_disk_usage('/')
        net = self.get_network_speed()
        uptime = self.get_uptime()
        return {
            'cpu': {
                'percent': round(host_cpu, 1),
                'display': f'''{host_cpu:.1f}%''',
                'project_percent': round(project_cpu, 1),
                'project_display': f'''{project_cpu:.1f}%''' },
            'memory': {
                'percent': host_mem.get('percent', 0),
                'used_gb': host_mem.get('used_gb', 0),
                'total_gb': host_mem.get('total_gb', 0),
                'display': f'''{self._format_memory(host_mem.get('used_gb', 0), host_mem.get('used_mb', 0))} / {self._format_total_memory(host_mem.get('total_gb', 0))}''',
                'project_mb': round(project_mem_mb, 1),
                'project_gb': round(project_mem_gb, 2),
                'project_display': self._format_memory(project_mem_gb, project_mem_mb) },
            'disk': {
                'percent': round(disk.get('percent', 0), 1),
                'used_gb': disk.get('used_gb', 0),
                'total_gb': disk.get('total_gb', 0),
                'free_gb': disk.get('free_gb', 0),
                'display': f'''{disk.get('used_gb', 0)} GB / {disk.get('total_gb', 0)} GB''',
                'free_display': f'''{disk.get('free_gb', 0)} GB''' },
            'network': {
                'upload': net.get('upload_display', '0 B/s'),
                'download': net.get('download_display', '0 B/s') },
            'uptime': {
                'seconds': uptime,
                'display': self.format_uptime(uptime) } }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_5258__(...)'
    '__pyarmor_exit_5258__(...)'

system_monitor = SystemMonitor()
return None
return None
'__pyarmor_exit_5252__(...)'
'__pyarmor_exit_5252__(...)'
