# File: task_queue.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: task_queue.py.1shot.das

__doc__ = '任务队列管理器 - 统一管理 HDHive 解析、STRM 生成任务和定时任务调度'
'__pyarmor_enter_5308__(...)'
import threading
import queue
import time
import uuid
import logging
from typing import Dict, Any, Callable, Optional
from dataclasses import dataclass
from enum import Enum
from datetime import datetime
logger = logging.getLogger('task_queue')
logging.getLogger('apscheduler').setLevel(logging.WARNING)
logging.getLogger('apscheduler.scheduler').setLevel(logging.WARNING)
logging.getLogger('apscheduler.executors').setLevel(logging.WARNING)
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.jobstores.memory import MemoryJobStore
APSCHEDULER_AVAILABLE = True

class TaskType(Enum):
    '''任务类型'''
    '__pyarmor_enter_5311__(...)'
    HDHIVE = 'hdhive'
    STRM = 'strm'
    return None
    return None
    '__pyarmor_exit_5312__(...)'
    '__pyarmor_exit_5312__(...)'


class TaskStatus(Enum):
    '''任务状态'''
    '__pyarmor_enter_5314__(...)'
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    return None
    return None
    '__pyarmor_exit_5315__(...)'
    '__pyarmor_exit_5315__(...)'

Task = <NODE:12>()

class TaskQueueManager:
    '''任务队列管理器'''
    '__pyarmor_enter_5323__(...)'
    _instance = None
    
    def __new__(cls):
        '__pyarmor_enter_5326__(...)'
    # WARNING: Decompyle incomplete

    
    def __init__(self):
        '__pyarmor_enter_5329__(...)'
        if self._initialized:
            return None
        return None
        self._queue = queue.Queue()
        self._tasks = { }
        self._running = False
        self._worker_thread = None
        self._lock = threading.Lock()
        self._handlers = { }
        self._initialized = True
        return None
        return None
        '__pyarmor_exit_5330__(...)'
        '__pyarmor_exit_5330__(...)'

    
    def register_handler(self, task_type, handler):
        '''注册任务处理器'''
        '__pyarmor_enter_5332__(...)'
        self._handlers[task_type] = handler
        logger.info(f'''已注册任务处理器: {task_type.value}''')
        return None
        return None
        '__pyarmor_exit_5333__(...)'
        '__pyarmor_exit_5333__(...)'

    
    def add_task(self, task_type, data, callback):
        '''添加任务到队列'''
        '__pyarmor_enter_5335__(...)'
        task_id = str(uuid.uuid4())[:8]
        task = Task(id = task_id, type = task_type, data = data, callback = callback)
    # WARNING: Decompyle incomplete

    
    def get_task_status(self, task_id):
        '''获取任务状态'''
        '__pyarmor_enter_5338__(...)'
    # WARNING: Decompyle incomplete

    
    def get_queue_stats(self):
        '''获取队列统计'''
        '__pyarmor_enter_5341__(...)'
    # WARNING: Decompyle incomplete

    
    def start(self):
        '''启动任务队列处理'''
        '__pyarmor_enter_5344__(...)'
        if self._running:
            return None
        return None
        self._running = True
        self._worker_thread = threading.Thread(target = self._worker_loop, daemon = True, name = 'TaskQueueWorker')
        self._worker_thread.start()
        logger.info('任务队列管理器已启动')
        return None
        return None
        '__pyarmor_exit_5345__(...)'
        '__pyarmor_exit_5345__(...)'

    
    def stop(self):
        '''停止任务队列处理'''
        '__pyarmor_enter_5347__(...)'
        self._running = False
        if self._worker_thread:
            self._worker_thread.join(timeout = 5)
        logger.info('任务队列管理器已停止')
        return None
        return None
        '__pyarmor_exit_5348__(...)'
        '__pyarmor_exit_5348__(...)'

    
    def _worker_loop(self):
        '''工作线程循环'''
        '__pyarmor_enter_5350__(...)'
        if self._running:
            task = self._queue.get(timeout = 1)
            self._process_task(task)
            if self._running:
                continue
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _process_task(self, task):
        '''处理单个任务'''
        '__pyarmor_enter_5353__(...)'
        handler = self._handlers.get(task.type)
        if not handler:
            logger.error(f'''未找到任务处理器: {task.type.value}''')
            task.status = TaskStatus.FAILED
            task.error = '未找到任务处理器'
            return None
        return None
        task.status = TaskStatus.RUNNING
        logger.info(f'''开始处理任务: {task.type.value} - {task.id}''')
        result = handler(task.data)
        task.status = TaskStatus.COMPLETED
        task.result = result
        logger.info(f'''任务完成: {task.type.value} - {task.id}''')
        if task.callback:
            task.callback(task)
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def clear_completed_tasks(self, max_age):
        '''清理已完成的任务（默认保留 1 小时）'''
        '__pyarmor_enter_5356__(...)'
        current_time = time.time()
    # WARNING: Decompyle incomplete

    __classcell__ = None
    return None
    __classcell__ = None
    return None
    '__pyarmor_exit_5324__(...)'
    '__pyarmor_exit_5324__(...)'


class CronParser:
    '''Cron 表达式解析器'''
    '__pyarmor_enter_5359__(...)'
    check_cron = (lambda cron_expr, now: '__pyarmor_enter_5362__(...)'parts = cron_expr.split()if len(parts) < 5:
FalseFalse(minute_expr, hour_expr, day_expr, month_expr, weekday_expr) = parts[:5]if not CronParser._match_cron_field(minute_expr, now.minute, 0, 59):
FalseFalseif not CronParser._match_cron_field(hour_expr, now.hour, 0, 23):
FalseFalseif not CronParser._match_cron_field(day_expr, now.day, 1, 31):
FalseFalseif not CronParser._match_cron_field(month_expr, now.month, 1, 12):
FalseFalseweekday = now.weekday()cron_weekday = 0 if weekday == 6 else weekday + 1if not CronParser._match_cron_field(weekday_expr, cron_weekday, 0, 6):
FalseFalseTrueTrue# WARNING: Decompyle incomplete
)()
    _match_cron_field = (lambda expr, value, min_val, max_val: '__pyarmor_enter_5365__(...)'if expr == '*':
TrueTrueif expr.startswith('*/'):
step = int(expr[2:])(value - min_val) % step == 0None(None)Noneif '/' in expr and '-' in expr:
(range_part, step) = expr.split('/')(start, end) = range_part.split('-')step = int(step)end = int(end)start = int(start)if  <= start, value or start, value <= end:
passelse:
(value - start) % step == 0None(None)NoneFalseFalseif '-' in expr:
(start, end) = expr.split('-')None if  <= int(start), value else None, int(start), value <= int(end)None(None)None# WARNING: Decompyle incomplete
)()
    return None
    staticmethod
    return None
    '__pyarmor_exit_5360__(...)'
    '__pyarmor_exit_5360__(...)'

ScheduledTask = <NODE:12>()

class TaskScheduler:
    '''定时任务调度器'''
    '__pyarmor_enter_5371__(...)'
    
    def __init__(self):
        '__pyarmor_enter_5374__(...)'
        self._tasks = { }
        self._running = False
        self._scheduler_thread = None
        self._executed_tasks = { }
        self._lock = threading.Lock()
        self._use_apscheduler = APSCHEDULER_AVAILABLE
        self._apscheduler = None
        if self._use_apscheduler:
            jobstores = {
                'default': MemoryJobStore() }
            executors = {
                'default': ThreadPoolExecutor(max_workers = 10) }
            job_defaults = {
                'coalesce': True,
                'max_instances': 1,
                'misfire_grace_time': 60 }
            self._apscheduler = BackgroundScheduler(jobstores = jobstores, executors = executors, job_defaults = job_defaults, timezone = 'Asia/Shanghai')
            logger.info('定时任务调度器初始化完成')
        else:
            logger.info('定时任务调度器初始化完成')
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def add_scheduled_task(self, name, cron_expr, handler, enabled):
        '''添加定时任务'''
        '__pyarmor_enter_5377__(...)'
    # WARNING: Decompyle incomplete

    
    def remove_scheduled_task(self, name):
        '''移除定时任务'''
        '__pyarmor_enter_5383__(...)'
    # WARNING: Decompyle incomplete

    
    def remove_all_tasks(self):
        '''移除所有定时任务'''
        '__pyarmor_enter_5386__(...)'
    # WARNING: Decompyle incomplete

    
    def enable_task(self, name):
        '''启用定时任务'''
        '__pyarmor_enter_5389__(...)'
    # WARNING: Decompyle incomplete

    
    def disable_task(self, name):
        '''禁用定时任务'''
        '__pyarmor_enter_5392__(...)'
    # WARNING: Decompyle incomplete

    
    def start(self):
        '''启动定时任务调度器'''
        '__pyarmor_enter_5395__(...)'
        if self._running:
            return None
        return None
        self._running = True
        if self._use_apscheduler and self._apscheduler:
            self._apscheduler.start()
            logger.info('定时任务调度器已启动')
        else:
            self._scheduler_thread = threading.Thread(target = self._scheduler_loop, daemon = True, name = 'TaskScheduler')
            self._scheduler_thread.start()
            logger.info('定时任务调度器已启动')
        return None
        return None
        '__pyarmor_exit_5396__(...)'
        '__pyarmor_exit_5396__(...)'

    
    def stop(self):
        '''停止定时任务调度器'''
        '__pyarmor_enter_5398__(...)'
        self._running = False
        if self._use_apscheduler and self._apscheduler:
            self._apscheduler.shutdown(wait = False)
        elif self._scheduler_thread:
            self._scheduler_thread.join(timeout = 5)
        logger.info('定时任务调度器已停止')
        return None
        return None
    # WARNING: Decompyle incomplete

    
    def _scheduler_loop(self):
        '''调度器循环'''
        '__pyarmor_enter_5401__(...)'
        last_check_minute = -1
    # WARNING: Decompyle incomplete

    
    def _execute_task(self, task):
        '''执行定时任务'''
        '__pyarmor_enter_5404__(...)'
        task.handler()
        task.last_run = time.time()
        return None
        return None
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_5372__(...)'
    '__pyarmor_exit_5372__(...)'

task_queue_manager = TaskQueueManager()
task_scheduler = TaskScheduler()
return None
dataclass
return None
# WARNING: Decompyle incomplete
