# File: telegraph.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: telegraph.py.1shot.das

'''Telegraph 链接解析 - 从 telegra.ph 页面提取115分享链接'''
'__pyarmor_enter_5833__(...)'
import re
import requests
from typing import List, Dict
from logger import logger
_SHARE_115_PATTERN = re.compile('https?://115(?:cdn)?\\.com/s/[a-zA-Z0-9]+(?:\\?password=[a-zA-Z0-9]+)?')
_ED2K_PATTERN = re.compile('ed2k://\\|file\\|[^\\r\\n]+?\\|/')
TELEGRAPH_PATTERN = re.compile('https?://(?:telegra\\.ph|graph\\.org)/[^\\s\\)）\\]】"\\\']+')

def extract_telegraph_links(text):
    '''从文本中提取 Telegraph 链接'''
    '__pyarmor_enter_5836__(...)'
    if not text:
        return []
    None(None)
    return None
    links = TELEGRAPH_PATTERN.findall(text)
    seen = set()
    result = []
    for link in links:
        link = link.rstrip('.,;!?，。；！？')
        if not link not in seen:
            continue
        seen.add(link)
        result.append(link)
    return result
    None(None)
    return None
    '__pyarmor_exit_5837__(...)'
    '__pyarmor_exit_5837__(...)'


def _extract_content_recursive(nodes, texts, links):
    '''递归提取 Telegraph API 返回的 content 节点中的文本和链接'''
    '__pyarmor_enter_5839__(...)'
    if isinstance(nodes, str):
        texts.append(nodes)
        return None
    return None
    if isinstance(nodes, list):
        for node in nodes:
            _extract_content_recursive(node, texts, links)
        return None
    return None
    if isinstance(nodes, dict):
        attrs = nodes.get('attrs', { })
        children = nodes.get('children', [])
        tag = nodes.get('tag', '')
        if 'href' in attrs:
            links.append(attrs['href'])
        if 'src' in attrs:
            links.append(attrs['src'])
        _extract_content_recursive(children, texts, links)
        if tag in ('p', 'br', 'div', 'h3', 'h4', 'blockquote', 'li'):
            texts.append('\n')
    return None
    return None
    '__pyarmor_exit_5840__(...)'
    '__pyarmor_exit_5840__(...)'


def fetch_telegraph_share_links(url, proxy):
    """抓取 Telegraph 页面，提取115分享链接和ed2k链接
    
    Returns:
        {
            'success': bool,
            'share_links': List[str],  # 去重后的115分享链接
            'ed2k_links': List[str],   # 去重后的ed2k链接
            'title': str,
        }
    """
    '__pyarmor_enter_5842__(...)'
    proxies = {
        'http': proxy,
        'https': proxy } if proxy else None
    path = url.split('telegra.ph/')[-1] if 'telegra.ph/' in url else ''
    if path and 'graph.org/' in url:
        path = url.split('graph.org/')[-1]
    if path:
        api_url = f'''https://api.telegra.ph/getPage/{path}?return_content=true'''
        resp = requests.get(api_url, timeout = 15, proxies = proxies)
        if resp.status_code == 200:
            data = resp.json()
            if data.get('ok'):
                result = data.get('result', { })
                title = result.get('title', '')
                content = result.get('content', [])
                texts = []
                href_links = []
                _extract_content_recursive(content, texts, href_links)
                full_text = '\n'.join(texts)
                share_links = set()
                for m in _SHARE_115_PATTERN.finditer(full_text):
                    share_links.add(m.group(0).rstrip('.,;!?#'))
                for link in href_links:
                    for m in _SHARE_115_PATTERN.finditer(link):
                        share_links.add(m.group(0).rstrip('.,;!?#'))
                ed2k_links = set()
                for m in _ED2K_PATTERN.finditer(full_text):
                    ed2k_links.add(m.group(0))
                for link in href_links:
                    for m in _ED2K_PATTERN.finditer(link):
                        ed2k_links.add(m.group(0))
                return {
                    'success': True,
                    'share_links': list(share_links),
                    'ed2k_links': list(ed2k_links),
                    'title': title }
            None(None)
            return None
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Accept': 'text/html,*/*' }
    resp = requests.get(url, headers = headers, timeout = 15, proxies = proxies)
    if resp.status_code == 200:
        share_links = set()
        for m in _SHARE_115_PATTERN.finditer(resp.text):
            share_links.add(m.group(0).rstrip('.,;!?#"\''))
        ed2k_links = set()
        for m in _ED2K_PATTERN.finditer(resp.text):
            ed2k_links.add(m.group(0))
        return {
            'success': True,
            'share_links': list(share_links),
            'ed2k_links': list(ed2k_links),
            'title': '' }
    None(None)
    return None
    return {
        'success': False,
        'share_links': [],
        'ed2k_links': [],
        'title': '' }
    None(None)
    return None
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_5834__(...)'
'__pyarmor_exit_5834__(...)'
