# File: transfer_115.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: transfer_115.py.1shot.das

'''115 转存模块'''
'__pyarmor_enter_6175__(...)'
import re
import threading
import time
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
from p115client import P115Client
from logger import hdhive_logger as logger
from ua import ShareP115Client, UserAgentUtils
from config_manager import config_manager
BASE_URL = 'https://webapi.115.com'

class Transfer115:
    '''115 网盘转存器'''
    '__pyarmor_enter_6178__(...)'
    
    def __init__(self, cookie, target_cid):
        '__pyarmor_enter_6181__(...)'
        self.cookie = cookie
        self.target_cid = target_cid
        self.client = ShareP115Client(cookie, check_for_relogin = True)
        return None
        return None
        '__pyarmor_exit_6182__(...)'
        '__pyarmor_exit_6182__(...)'

    
    def _parse_cookies(self):
        '''解析 cookie 字符串为字典（仅用于 share 相关的兼容调用）'''
        '__pyarmor_enter_6184__(...)'
        cookies = { }
        for item in self.cookie.split(';'):
            if not '=' in item:
                continue
            (k, v) = item.strip().split('=', 1)
            cookies[k] = v
        return cookies
        None(None)
        return None
        '__pyarmor_exit_6185__(...)'
        '__pyarmor_exit_6185__(...)'

    human_readable = (lambda size: '__pyarmor_enter_6187__(...)'if size < 1024:
f'''{size}B'''None(None)Noneif size < 1048576:
f'''{size / 1024:.2f}KB'''None(None)Noneif size < 1073741824:
f'''{size / 1024 / 1024:.2f}MB'''None(None)Noneif size < 0x10000000000:
f'''{size / 1024 / 1024 / 1024:.2f}GB'''None(None)Noneif size < 0x4000000000000:
f'''{size / 1024 / 1024 / 1024 / 1024:.2f}TB'''None(None)Nonef'''{size / 1024 / 1024 / 1024 / 1024 / 1024:.2f}PB'''None(None)None'__pyarmor_exit_6188__(...)''__pyarmor_exit_6188__(...)')()
    parse_share_link = (lambda share_link: '__pyarmor_enter_6190__(...)'share_code_match = re.search('/s/([^?]+)', share_link)receive_code_match = re.search('password=(\\w{4})', share_link)if not share_code_match or receive_code_match:
(None, None)(None, None)(share_code_match.group(1), receive_code_match.group(1))None(None)None'__pyarmor_exit_6191__(...)''__pyarmor_exit_6191__(...)')()
    
    def get_share_snap(self, share_code, receive_code, cid):
        '''获取分享文件快照信息（文件列表和大小）'''
        '__pyarmor_enter_6193__(...)'
        payload = {
            'share_code': share_code,
            'receive_code': receive_code,
            'cid': cid,
            'limit': 100,
            'offset': 0 }
        ios_ua_kwargs = UserAgentUtils.get_ios_ua_app(app = False)
    # WARNING: Decompyle incomplete

    
    def transfer_single_file(self, share_code, receive_code, file_id, target_cid):
        '''转存单个文件'''
        '__pyarmor_enter_6196__(...)'
    # WARNING: Decompyle incomplete

    
    def list_dir_files(self, cid, limit):
        '''列出指定目录下的所有文件和文件夹'''
        '__pyarmor_enter_6199__(...)'
        all_items = []
        offset = 0
    # WARNING: Decompyle incomplete

    
    def find_item_in_dir(self, parent_cid, name):
        '''在指定目录中查找文件或文件夹'''
        '__pyarmor_enter_6202__(...)'
        items = self.list_dir_files(parent_cid)
        for item in items:
            if not isinstance(item, dict):
                continue
            if not item.get('n') == name:
                continue
            
            return items, item
            None(None)
            return None
        return None
        return None
        '__pyarmor_exit_6203__(...)'
        '__pyarmor_exit_6203__(...)'

    
    def create_folder(self, parent_cid, folder_name):
        '''在网盘中创建文件夹，返回 {success, cid, message}'''
        '__pyarmor_enter_6205__(...)'
    # WARNING: Decompyle incomplete

    
    def rename_file(self, file_id, new_name):
        '''重命名网盘中的文件'''
        '__pyarmor_enter_6208__(...)'
    # WARNING: Decompyle incomplete

    
    def transfer(self, share_link, target_cid):
        '''执行转存
        
        Args:
            share_link: 分享链接
            target_cid: 目标文件夹 ID，如果不指定则使用初始化时的 target_cid
        '''
        '__pyarmor_enter_6211__(...)'
        (share_code, receive_code) = self.parse_share_link(share_link)
        if not share_code or receive_code:
            logger.error('无法解析分享链接或密码')
            return {
                'success': False,
                'message': '❌ 无法解析分享链接或密码',
                'file_size': '',
                'raw_response': { } }
        None(None)
        return None
    # WARNING: Decompyle incomplete

    is_115_link = (lambda url: '__pyarmor_enter_6214__(...)'if not '115cdn.com' in url:
'115cdn.com' in url'115.com' in urlNone(None)None'__pyarmor_exit_6215__(...)''__pyarmor_exit_6215__(...)')()
    return None
    staticmethod
    return None
    '__pyarmor_exit_6179__(...)'
    '__pyarmor_exit_6179__(...)'
    return staticmethod


def get_transfer_115_for_hdhive():
    '''获取用于 HDHive 的 115 转存器'''
    '__pyarmor_enter_6217__(...)'
    hdhive_config = config_manager.get_hdhive_config()
    config_name = hdhive_config.get('use_115_config', '')
    target_cid = hdhive_config.get('target_cid', '0')
    if not config_name:
        return None
    return None
    config_115 = config_manager.get_115_config_by_name(config_name)
    if not config_115:
        return None
    return None
    cookie = config_115.get('cookie', '')
    if not cookie:
        return None
    return None
    return Transfer115(cookie, target_cid)
    None(None)
    return None
    '__pyarmor_exit_6218__(...)'
    '__pyarmor_exit_6218__(...)'

_TG_TRANSFER_LOCK = threading.Lock()
_TG_LAST_TRANSFER_DONE_TS = 0
_TG_TRANSFER_MIN_GAP = 1

def tg_throttled_transfer(transfer_instance, share_link, target_cid):
    '''TG Bot 全局 115 转存节流入口

    内部串行执行,相邻两次转存之间至少间隔 _TG_TRANSFER_MIN_GAP 秒。
    若距上次转存完成已超过间隔阈值,则立即开始;否则 sleep 补足后再执行。

    Args:
        transfer_instance: Transfer115 实例
        share_link: 115 分享链接
        target_cid: 目标目录 CID(为 None 时使用实例上的 target_cid)

    Returns:
        Transfer115.transfer() 的返回结果
    '''
    '__pyarmor_enter_6220__(...)'
# WARNING: Decompyle incomplete

return None
return None
'__pyarmor_exit_6176__(...)'
'__pyarmor_exit_6176__(...)'
