# File: ua.py.1shot.seq (Python 3.12)
# Source generated by Pyarmor-Static-Unpack-1shot (v0.3.0), powered by Decompyle++ (pycdc)

# Note: Decompiled code can be incomplete and incorrect.
# Please also check the correct and complete disassembly file: ua.py.1shot.das

'''User-Agent 生成工具'''
'__pyarmor_enter_6151__(...)'
import time
from random import randint, choice
from typing import Optional, Dict, Any
from typing import Literal, Coroutine
from urllib.parse import urljoin
from p115client import P115Client, check_response

def complete_url(path, base_url):
    '''构建完整 URL'''
    '__pyarmor_enter_6154__(...)'
    if callable(base_url):
        base_url = base_url()
    return urljoin(base_url.rstrip('/') + '/', path.lstrip('/'))
    None(None)
    return None
    '__pyarmor_exit_6155__(...)'
    '__pyarmor_exit_6155__(...)'


class ShareP115Client(P115Client):
    '''
    分享同步专用 Client
    '''
    '__pyarmor_enter_6157__(...)'
    
    def share_snap_cookie(self, payload, base_url, *, async_, **request_kwargs):
        '''
        获取分享链接的某个目录中的文件和子目录的列表（包含详细信息）

        GET https://webapi.115.com/share/snap

        :payload:
            - share_code: str
            - receive_code: str
            - cid: int | str = 0
            - limit: int = 32
            - offset: int = 0
            - asc: 0 | 1 = <default> 💡 是否升序排列
            - o: str = <default> 💡 用某字段排序
        '''
        '__pyarmor_enter_6160__(...)'
        api = complete_url('/share/snap', base_url = base_url)
    # WARNING: Decompyle incomplete

    return None
    return None
    '__pyarmor_exit_6158__(...)'
    '__pyarmor_exit_6158__(...)'


class UserAgentUtils:
    '''
    User-Agent 生成工具 - 带 TTL 缓存的 iOS UA 生成
    '''
    '__pyarmor_enter_6163__(...)'
    _cache: Optional[str] = None
    _cache_time: float = 0
    _cache_ttl: int = 3600
    generate_u115_ios = (lambda cls: '__pyarmor_enter_6166__(...)'current_time = time.time()if cls._cache and current_time - cls._cache_time < cls._cache_ttl:
cls._cacheNone(None)Noneresp = P115Client.app_version_list2()check_response(resp)udown_version = resp['data']['iOS-iPhone']['version_code']wangpan_version = resp['data']['115wangpan_iOS']['version_code']ios_versions = [
'15_0',
'15_1',
'15_2',
'15_3',
'15_4',
'15_5',
'15_6',
'15_7',
'15_8',
'16_0',
'16_1',
'16_2',
'16_3',
'16_4',
'16_5',
'16_6',
'16_7',
'17_0',
'17_1',
'17_2',
'17_3',
'17_4',
'17_5',
'18_0',
'18_1']build_num = randint(15, 21)build_letter = choice('ABCDE')build_tail = randint(100, 999)build = f'''{build_num}{build_letter}{build_tail}'''webkit = '605.1.15'os_ver = choice(ios_versions)client = choice([
f'''115wangpan_ios/{wangpan_version}''',
f'''UDown/{udown_version}'''])ua = f'''Mozilla/5.0 (iPhone; CPU iPhone OS {os_ver} like Mac OS X) AppleWebKit/{webkit} (KHTML, like Gecko) Mobile/{build} {client}'''cls._cache = uacls._cache_time = current_timeuaNone(None)None# WARNING: Decompyle incomplete
)()
    get_ios_ua_app = (lambda cls, app: '__pyarmor_enter_6169__(...)'kwargs = {
'headers': {
'user-agent': cls.generate_u115_ios() } }if app:
kwargs['app'] = 'ios'kwargsNone(None)None'__pyarmor_exit_6170__(...)''__pyarmor_exit_6170__(...)')()
    clear_cache = (lambda cls: '__pyarmor_enter_6172__(...)'cls._cache = Nonecls._cache_time = 0NoneNone'__pyarmor_exit_6173__(...)''__pyarmor_exit_6173__(...)')()
    return None
    classmethod
    return None
    '__pyarmor_exit_6164__(...)'
    '__pyarmor_exit_6164__(...)'
    return classmethod

return None
return None
'__pyarmor_exit_6152__(...)'
'__pyarmor_exit_6152__(...)'
